- pcdsdevices/epics/areadetector/plugins.py
but the int value of enable.
At the PCDS version of ADCore the string values of the EnableCallbacks and EnableCallbacks_RBV where changed from Enable -> Enabled and Disable -> Disabled breaking the default stage method at PluginBase on Ophyd.
This fix this issue by using the integer value to set it.
> FIX: Changed stage at PluginBase to not use the string

- pcdsdevices/epics/areadetector/plugins.py
- pcdsdevices/epics/pim.py
- pcdsdevices/sim/areadetector/detectors.py
- pcdsdevices/sim/areadetector/plugins.py
- pcdsdevices/sim/pim.py
- tests/sim/areadetector/test_sim_detectors.py
- tests/sim/areadetector/test_sim_plugins.py
Relatively benign PR. Added a ImagePlugin class to the sim devices so I can have the detectors actually return images for testing psbeam. This PR also fixes all the issues with the image attribute of ImagePlugin not working properly by overriding some ophyd attributes with variants that enforce type casting.
> Added ImagePlugin as a simulated class and a generic SimDetector

- pcdsdevices/epics/mirror.py
Part of the logging cleanup, this way we know when we are waiting for mirror moves
> STY: Added log messages on move and wait

- .gitignore
- pcdsdevices/epics/pim.py
- tests/sim/test_sim_pim.py
Have PIMMotor move in on .stage() and out on .unstage() so we can simplify the pswalker code and more generically check for staged detectors in things like the recovery plan. We can stop relying on prep_img_motors (which is a complicated overoptimization) if we just wrap walk_to_pixel with the stage decorator. This will also help us make sure the pims come all the way out at the end of the alignment. Have stage wait for the pim to go in, but don't wait on unstage because these are basically out of the beam in half a second.
Also a small addition to the .gitignore so an egg-info directory won't show as modified.
> ENH: Pim stage

- .coveragerc
- pcdsdevices/epics/mirror.py
- tests/sim/test_sim_mirror.py
Stage any `OMMotor` that has a `nominal_position`. We will have to put an `@stage_decorator` on before this does anything for S.O.P
Closes: #8
> ENH: Mirror motors stage to nominal position

- pcdsdevices/sim/pim.py
Sometimes this lambda function fails because self.position doesn't have a numerical position associated with it in the self.pos_d dictionary. The quick and dirty fix is to use the get function to return None instead of raising the KeyError. I don't think this creates new issues anywhere else and it should fix one of our pswalker race conditions. The bit of code that enters this block for the race condition in sim/signal Signal.put is checking for a TypeError on str + float, and you also get a TypeError on None + float, so we "might" be able to continue on... or we might learn what the next exception is in the race condition chain.
> BUG: Bandaid fix for race condition

- pcdsdevices/__init__.py
- pcdsdevices/device.py
- pcdsdevices/epics/ipm.py
- pcdsdevices/epics/state.py
- requirements.txt
- run_tests.py
- tests/conftest.py
- tests/test_epics_ipm.py
- tests_live/conftest.py
- All PCDS Devices are now using the LightInterface metaclass. This comes with an explicit dependency on lightpath, which is now in the `requirements.txt`. The defaults for the device are setup in such a way that we should never fail to have all the methods of the interface. The only thing we are risking is some incidental `NotImplementedError` 😄 
- I converted what `ophyd` was using for using_fake_epics_pv and made it more general. I wrote a ton of notes on some pitfalls I stumbled into while putting it together
- Finished a few things I missed cleanup tests
- Tested everything on the IPM device, should be ready for production use
> ENH: LightInterface and EPICS testing

- pcdsdevices/epics/mirror.py
Subclasses of the ophyd PositionerBase class take a timeout argument that sets the default timeout on calls to move and set. Having this on our OffsetMirror and passing the argument down to pitch will allow us to make set a move timeout on a per-mirror basis in pswalker/iterwalk without picking a global timeout for all of the mirror move commands.
> ENH: add arg for default timeout on OffsetMirror

- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/pim.py
- pcdsdevices/epics/state.py
- pcdsdevices/sim/mirror.py
- pcdsdevices/sim/pim.py
- tests/test_sim_mirror.py
- tests/test_sim_pim.py
Transition PIMMotor and OffsetMirror to be subclasses of PositionerBase, adjusting a bit so we have timeouts, move waits, etc. that work properly with states, etc.
Most notable changes are in states, which now can move with proper status objects that can be waited on correctly rather than just looking for puts. This was tested on a live PIM this morning.
There were also a lot of commits where I switched tabs to spaces, etc. as I went, making some of these hard to look through, but I maintain it was needed.
I also added a fix to let us set nominal_position from the top-level OffsetMirror object.
> ENH: Timeouts on PIM moves

- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/state.py
A few quick fixes that were noticed last-minute. My changes to state resulted in a situation where moves to the current position would erroneously time out because they never transitioned. These now end immediately with success. There was also an issue where the real devices being moved by other programs would lead to a situation where an unset move_requested would cause a problem, so I set this at init.
I also bumped up the default position tolerance in the mirrors because we were having issues when a move command for the mirrors would wait until timeout if the position was just outside the tolerance range but still very small.
> FIX: Hotfix from Today

- pcdsdevices/epics/state.py
- pcdsdevices/epics/stopper.py
- tests/test_epics_stopper.py
- tests/test_state.py
Changes
--------
* I changed the way the PVState looks at the signals to interpret the complete state. The way it was it just returned the first valid state it found. This way if multiple signals have conflicting states we will report "unknown" i.e a motor is unplugged both the `out` and `in` limit switches are tripped
* I added a generic `StateStatus` you can just give it one of the state devices and it will create a background thread that marks the status done when you reach the desired state. I felt a little like I was rewriting stuff but I couldn't really see an explicit implementation of what we wanted 
* `PPSStopper` and regular `Stopper`
Mostly requesting an explicit review because I want to make sure there is not a simpler way to do this with the device subscribes. Also @ZLLentz I …
> ENH: PVState improvements and Stoppers

- pcdsdevices/epics/aerotech.py
- pcdsdevices/epics/areadetector/cam.py
- pcdsdevices/epics/areadetector/detectors.py
- pcdsdevices/epics/attocube.py
- pcdsdevices/epics/diode.py
- pcdsdevices/epics/micronix.py
- pcdsdevices/epics/rtd.py
- tests/conftest.py
- tests/test_epics_aerotech.py
- tests/test_epics_attocube.py
- tests/test_epics_diode.py
- tests/test_epics_micronix.py
- tests/test_epics_rtd.py
This PR adds the base classes for the lower level devices to be used in the split and delay system. They are mostly motors and are currently mostly empty but should, in theory, provide basic functionality for their respective motors assuming they all use the motor class correctly.
The classes are currently unfinished but this seemed like a good place to make the initial PR before continuing to work on them since tests pass both here and in SnD. Below are the classes:
**Motors**
`aerotech.py`
- `AeroBase` - Base class for all the aerotech motors
- `RotationAero` - Rotation aerotech motor stage.
- `LinearAero` - Linear aerotech motor. stage.
`attocube.py`
- `EccMotor` - Base class for the attocube ECC motors
- `TranslationEcc` - Linear translation attocube motor.
- `GoniometerEcc` - ECC …
> ENH: Adding base classes for lower level devices to be used in SnD

- pcdsdevices/epics/pim.py
The subscriptions on PIMMotor weren't really doing anything meaningful. What I really wanted was to be able to subscribe to state changes. The quickest way to implement this was to simply pass the subscribe/clear_sub method calls down to the component states object.
> ENH: Make subscriptions on PIMMotor pass down to states. Needed for gui.

- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/pim.py
- pcdsdevices/epics/slits.py
- tests/test_state.py
* Fixed move commands in slits, PIM, Mirror
* Stages stayed the same
* Removed race condition that occasionally knocked out Travis tests
> FIX: Bluesky methods should not wait by default

- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/pim.py
- tests/test_sim_mirror.py
- tests/test_sim_pim.py
If device setup is not fast, we need to explicitly do it in our plan to avoid jamming the RunEngine. To this end, we're removing the move wait=True calls from all stage methods, replacing them with save/restore where appropriate.
> No wait in stage

- pcdsdevices/epics/areadetector/plugins.py
- pcdsdevices/epics/slits.py
I encountered some small things to fix while testing the gui stability.
- AD staging: for the image plugin, stage() would fail on the first call sometimes because the enable PV was not connected prior to the call, and the set_and_wait call runs through a raise_if_disconnected wrapper somewhere early in the stack. We should investigate if this is a bug fixed in the newest Opyhd or if we should submit a suitable PR to address it, but for now I'll just make sure it's connected before proceeding.
- Slit motion: there is a bug in the slits IOC where the EPICS put callback doesn't happen until motion is complete. This means that the put(wait=True) call in PVPositioner was causing the RunEngine to jam up during any slit move, and it also means that our slit moves couldn't do both vertical and …
> Small bugfixes

- pcdsdevices/epics/epicsmotor.py
The default implementation of the limits was returning the lower and upper control limit for the `user_setpoint` signal. I changed it to actually return the limits from the `low_soft_limit` and 'high_soft_limit` signals. This makes interacting with the limits more transparent and easier to work with (when simulating at least).
I also overrode the `check_value` method to also check the soft limits of the motor rather than just the `user_setpoint` limits.
> ENH: Fully overrided the limits properties and check_value to use soft limits

- pcdsdevices/epics/attenuator.py
Found before the run this morning, the all_in function on the attenuators doesn't work because values are missing for a boolean `wait` and a numeric `timeout`
> FIX: Default args on all_in so it works at all

- docs/source/index.rst
- docs/source/interface.rst
- pcdsdevices/device.py
- pcdsdevices/interface.py
- requirements.txt
- tests/test_interface.py
Move the defined interfaces from `lightpath` into this repository. This will prevent circular dependencies as only pcds-devices was dependent on these metaclasses. This also frees `lightpath` to have functions that automatically assemble devices
This will require changes to #59
> MAINT: Move LightInterface

- pcdsdevices/epics/attenuator.py
- pcdsdevices/sim/mirror.py
Simple fix to what we saw at the last beam time. When unstaging the attenuator, put a callback that logs if we have a failure. At the same time, I've dropped the default timeouts to 10s on all_in and all_out, because this is how long it will take for the status to be marked as failed.
As an aside, I've patched the sim object for OffsetMirror to mask the real mps PVs that were added. These PVs are causing a pswalker test to fail at the moment. The sim module could use a rework for stuff like this to avoid this kind of issue so we don't have to keep manually constructing the sim devices for PVs that have nothing interesting to simulate.
> Warn user if att unstage fails

- conda-recipe/meta.yaml
- pcdsdevices/sim/mirror.py
@teddyrendahl this makes pswalker tests pass...
We can think of a better approach for the optional state & mps soon.
> FIX: Add state as a Fake Signal at sim/OffsetMirror

- pcdsdevices/epics/slits.py
Fixes an issue where if there is a problem in staging some other device, this one is unaffected on `unstage`.
> FIX: Check if slits are staged before unstaging

- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/state.py
- tests/test_epics_mirror.py
This should fix the bug that stopped the last run. The issue was I added `mps` and `states` components to the OffsetMirror. This was fine when loading the class and playing around, but when bluesky "stages" the mirror it goes through the tree of components and subcomponents calling stage on everything. This failed when attempting to stage these misconfigured components. The long term issue is not all the mirrors have MPS inputs or state summaries. 
We now have two separate classes for mirrors,`PointingMirror` and `OffsetMirror`. The ladder is for mirrors like the HOMS and XRT M3 where they are necessary for alignment but not necessarily steering between different beamlines. `PointingMirror` is for mirrors that when inserted or removed actually change which beamline gets photons delivered …
> FIX: Remove MPS and states record from OffsetMirror

- pcdsdevices/device.py
- pcdsdevices/epics/areadetector/plugins.py
- tests/test_interface.py
Few quick fixes
---------------
* Lightpath kwargs should be searched for, even if `db_info` is not provided
* AreaDetector plugin should use `pcdsdevices.Component`
> FIX: Happi kwargs and remove ophyd Component

- .gitignore
- .travis.yml
- docs/source/daq.rst
- docs/source/index.rst
- pcdsdevices/__init__.py
- pcdsdevices/daq.py
- pcdsdevices/sim/daq.py
- run_tests.py
- tests/test_daq.py
Configure and run the daq via pydaq, now in a Flyer object. This has been tested on the real pydaq (requires a full daq to test) and has unit tests with a simulated pydaq. This was requested by Diling for Split and Delay.
Also attached to this PR:
- Added bluesky to the testing environment because I needed to check if the Flyer worked
- Added a logging config to the run_tests.py file to help me debug. This creates a new log file for each test run and saves the most recent 10.
> ENH: DAQ device

- pcdsdevices/epics/__init__.py
- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/mps.py
- pcdsdevices/epics/valve.py
- tests/test_epics_mirror.py
- tests/test_mps.py
First time with the factory stuff so please let me know if this makes sense. Made a function called `mps_factory` that takes a regular pcdsdevices class, keywords -> `mps_prefix`, `veto`, `args` and `kwargs`. The function then creates a new instance of the class with a subcomponent `mps`, and passes args and kwargs to the device constructor. The idea is you can make an arbitrary mps device constructor from another class using this and `functools.partial`:
```python
MPSDevice = partial(mps_factory, 'MPSDevice', Device)
d = MPSDevice(prefix='Tst:Prefix', mps_prefix='Tst:Mps:Prefix')
```
**Also**
---
* I made `mps` versions of `Stopper` and` GateValve`. I left `PointingMirror` and `PPSStopper` with explicit `mps` components as these will always have MPS inputs
*  I changed the API so the …
> ENH: MPS Factory

- pcdsdevices/epics/__init__.py
- pcdsdevices/epics/attenuator.py
- pcdsdevices/epics/ipm.py
- pcdsdevices/epics/pulsepicker.py
- tests/test_epics_ipm.py
* Created an IPMMotors class. This is all the lightpath should need, the full IPM with option for `data` key still exists with IPMMotors as a subclass
* I changed the Attenuator prefix handling.  Having just prefix `XPP` or `MFX` in the `happi` config seems like a bad idea, so you must now specify `MFX:ATT:COM`. I also fixed it so that the filter_prefix was being instantiated correctly, as it was not previously
* PickerBlade had no leading `:` for the signal specifications
> MAINT: Devices Odds and Ends

- pcdsdevices/epics/__init__.py
- pcdsdevices/epics/lens.py
- pcdsdevices/epics/mps.py
- pcdsdevices/epics/valve.py
- tests/test_epics_lens.py
Add XFLS class for Berylium Lenses. This class was trickier than first imagined as the `ims` class gives a lot of flexibility to what you name the states of your IOC (in CXI/MFX we name them on the energy that they will most likely be used at). Unfortunately this means I couldn't use the `statesrecord_class`  constructor out of the box. Long term we should probably standardize these IOCs or make a factory of some sort. For now, I opted for the lazy solution of just reading the main mbbi and if the state is not `removed` or `unknown` I assume it is inserted. Kind of a lazy method, but I don't really want to spend time on this until we have a more advanced use case. This is good enough for the lightpath.
@ZLLentz am I being lazy or efficient? Can't tell these days ...
Also, some minor bug …
> ENH: XFLS Class

- pcdsdevices/epics/state.py
Pull the raw source value into factory-created states classes. This can be compared against the setpoints to diagnose an Unknown state. It works by checking the CALC record value being used to output a state string.
I made this addition because all the LODCM states are out of whack and I didn't have a quick way to see why. This makes it very easy to check the raw position from an instantiated states object and may be useful for other devices.
> ENH: Add raw input value to states

- pcdsdevices/epics/lodcm.py
- tests/test_lodcm.py
- Handle Unknown states in destinations, treat as blocking.
- Allow instantiation without happi db if we don't pass a main_line.
- Clean up some attribute names.
- H2N doesn't have an OUT state
- The LODCMs have slightly different foil PVs for different materials. I'm removing all of these from the states for now, because they aren't relevant for lightpath.
> FIX: Misc LODCM

- pcdsdevices/epics/lodcm.py
- tests/test_lodcm.py
Ignore h2n, the states are unreliable. Being an expert device, we assume that beam is passing through the mono entirely if the diagnostics are not blocking and a crystal is inserted at h1n.
> FIX: Simplify LODCM pathing

- pcdsdevices/daq.py
- pcdsdevices/sim/daq.py
- tests/test_daq.py
Between 'create' and 'save' documents, the daq will run. There is an option to use original run-forever features. The 'controls' argument has been reworked to be very similar to the good parts of old python.
Misc bugfixes in cleanup, using correct syntax now instead of bad confluence API docs. Added a bunch of debug statements.
> ENH: DAQ Calibcycles

- pcdsdevices/daq.py
- pcdsdevices/sim/daq.py
- tests/test_daq.py
Changed sim daq to fail in the new ways we discovered from real daq
Remove unnecessary checks from the calibcycle tests
Cover edge case where first calibcycle could fail if starts too soon
> FIX: Testing robustness and edge cases

- pcdsdevices/epics/attenuator.py
- pcdsdevices/epics/ipm.py
- pcdsdevices/epics/lens.py
- pcdsdevices/epics/lodcm.py
- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/pim.py
- pcdsdevices/epics/pulsepicker.py
- pcdsdevices/epics/slits.py
- pcdsdevices/epics/valve.py
- tests/test_epics_attenuator.py
- tests/test_epics_ipm.py
- tests/test_epics_lens.py
- tests/test_epics_mirror.py
- tests/test_epics_pim.py
- tests/test_epics_pulsepicker.py
- tests/test_epics_slits.py
- tests/test_epics_valve.py
- tests/test_lodcm.py
Lots of files touched, very minimal changes.
I was having the issue that many of the lightpath subscription updates were too aggressive. This was largely because `lightpath` just uses the `default_sub`. I opted to make every lightpath device have a subscription called `SUB_STATE`, that we don't have to worry about keeping `default_sub` as a low-volume subscription and can use it for whatever is intuitive for the device.
Also, I took the opportunity to unify how the devices do subscriptions. When we first started making devices we sometimes did it as follows:
```python
class MyDevice:
state = C(DeviceState, ':STATE')
def subscribe(self, *args, **kwargs):
self.state.subscribe(*args, **kwargs)
```
This seemed kind of hacky as that prevented us from having any other subscriptions on the …
> API: Light subscriptions

- pcdsdevices/daq.py
- pcdsdevices/sim/daq.py
- Duration arg now works
- Class will wait to be ready to begin rather than attempting to begin early and stalling forever
- Prevent user from choosing duration < 1 because these cause internal issues in pydaq... sometimes
- Prevent user from configuring during a run because this breaks the session
- Updates to sim class to reflect some things I've learned about pydaq
> FIX: DAQ Class Robustness

- pcdsdevices/epics/epicsmotor.py
Changed epicsmotor import statement to clarify that the ophyd epicsmotor class is the parent class.  This is helpful because just having the class declaration as EpicsMotor(EpicsMotor, Device) is ambiguous.
> MAINT: epicsmotor inheritence clarification

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- pcdsdevices/device.py
- pcdsdevices/epics/attenuator.py
- pcdsdevices/epics/inout.py
- pcdsdevices/epics/ipm.py
- pcdsdevices/epics/lens.py
- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/pim.py
- pcdsdevices/epics/pulsepicker.py
- pcdsdevices/epics/slits.py
- pcdsdevices/epics/valve.py
- pcdsdevices/interface.py
- tests/test_epics_mirror.py
- tests/test_epics_valve.py
- tests/test_inout.py
A number of smaller bugs I found when stress testing the lightpath.
* When devices use `_run_subs` they should pass along a reference to themselves with `obj`. Prior to this, our devices would pass the signal that tripped their own subscription to be run passed as `obj`.
* `InOutDevice` needs to use `SUB_STATE` to specify which event type the lightpath should subscribe to.
* Added tests for `Reflaser` lightpath compatibility
* Remove is no longer required by the `LightInterface`. The main reason being is we do not want `remove` buttons for devices that can be removed by a single button in the lightpath. However, if we have `def remove(self): return NotImplemented`, we have to actually call the method to see if we should create the button. 
* There were a few objects using `.get` in their …
> FIX: Light Subscription Fixes  / Remove is optional

- pcdsdevices/epics/lodcm.py
Separate the destination calculation from the inserted/removed calculation. Use only the the H1N state to pick inserted or removed.
Lightpath needs inserted/removed to be simple and unambiguous. It can make its own decisions about how to interpret these booleans in the context of the destinations attribute.
The was only tested in an ipython session. The code is very simple. I am letting Travis take the wheel.
Docstrings updated
> FIX: Simplify LODCM inserted/removed for lightpath

- pcdsdevices/epics/mirror.py
- tests/test_epics_mirror.py
Two major changes:
1) `PointingMirror.inserted` and `PointingMirror.removed` now use top-level `PointingMirror.state.value` to determine the state. Not sure why I felt the need to use the low-level one
2) Before calling `PointingMirror.remove` or `PointingMirror.insert`, we check that the horizontal gantry is coupled. I had a terrifying thought that people would be pressing this button in the lightpath and not checking the state, even though it should never be decoupled.  In reality, the proper implementation is to make a `Gantry` object, but not sure it is an immediate priority. 
Was crashing the lightpath application
I was naughty and added this change to the release area to get the `lightpath` up and running. Added tests for new methods. 
Notes added in docstrings
> Minor Mirror Additions

- pcdsdevices/epics/pim.py
PIMMotor class has the default sub as readback, as per PositionerBase. I have changed this to SUB_STATE.
The readback sub is not used for this PIMMotor class. We expect the default sub to be something useful. After this change, subscriptions that do not specify a sub type will be run when the PIM state changes between YAG, DIODE, OUT, Unknown.
Double-checked the spelling.
This does not need to be documented. It is largely a bug fix.
> FIX: Make SUB_STATE the default sub for PIMs

- pcdsdevices/component.py
- pcdsdevices/epics/signal.py
- tests/test_base_overrides.py
- tests/test_epics_attenuator.py
- tests/test_epics_ipm.py
- tests/test_epics_lens.py
- tests/test_epics_mirror.py
- tests/test_epics_pim.py
- tests/test_epics_pulsepicker.py
- tests/test_epics_slits.py
- tests/test_epics_valve.py
- tests/test_inout.py
- tests/test_lodcm.py
- tests/test_mps.py
Undo `Component` overrides. Call `get_ctrlvars` when we instantiate a signal.
- `Component` override used currently broken lazy=True option.
- `FormattedComponent` is obsolete, was for our defunct `IOCDevice`
- `get_ctrlvars` cannot be called in some callbacks, calling it early prevents this issue from ever happening.
Skywalker works with these.
No need
> FIX: Reliable Components

- pcdsdevices/epics/areadetector/plugins.py
In `PluginBase.stage` add `atol=0` to the `set_and_wait` call for the `enable` signal.
`self.enable.get` does not guarantee that the `_write_pv` will finish connecting. The first line of `set_and_wait` accesses the `tolerance` property of the `EpicsSignalBase` class if `atol` is not provided. This raises a `DisconnectedError` unless `_read_pv` and `_write_pv` are both connected. We sidestep this by providing the correct tolerance, which is 0 in the case of the `enable` enum. There are no longer any issues because the `put` command that comes next will wait for the connection.
I think there needs to be an ophyd PR to really fix the issue, but this is a very easy fix now that will never get us into trouble later.
Passes tests and allows the skywalker stuff to run
> FIX: Prevent race condition in stage by preventing a tolerance check

- conda-recipe/meta.yaml
Rather than pinning specifically 1.0.0, let's also allow 1.0.1, 1.0.2...
This gives us some flexibility in the recipe as bugs get fixed in ophyd. We still need to manually evaluate releases like 1.1.0.
conda build
> BLD: Make ophyd version more flexible

- .travis.yml
- dev-requirements.txt
Entire build is now done with Conda. This has the following advantages:
1) Checks the accuracy of our conda-recipe. This is more important than checking `pip` with `requirements.txt` as most users will install via Conda.
2) Checks that all the packages from our stack are properly in the Conda channel. Not so important for this package as there are no internal dependencies. In general however, it is nice to know that before we push our build to Anaconda that we have built and passed the tests with the latest `pcds-tag` versions
3) Building the package then makes it very quick to send to Anaconda. We also avoid those annoying errors were everything passes tests with a `pip` install then fails at the very end when trying to build the package for Anaconda.
For packages that will be used …
> Travis by Conda

- .travis.yml
Missed one thing in #127 . We should avoid building the same thing twice. Use the build that we installed instead.
> CI: Avoid duplicate builds in Travis

- pcdsdevices/inout.py
- pcdsdevices/lodcm.py
- tests/test_inout.py
- tests/test_lodcm.py
Clean up all the clutter. Simplify down to a states record with just the H1N (first crystal) state, plus some utilities for clearing the diagnostic path. Minor change to `inout` to cause no action on `remove` if already removed. This is because of the `OUTLOW` state in the diagnostics here.
closes #122 
90% of the time you use the lodcm you just want to get it out of the way. This handles that in a simple, concise way without repeating code. I'd like to defer the rest for later, but it probably just needs some raw motors for alignment tweaking. I expect that an alignment expert just wants the motors, and everyone else just wants to know where H1N is and if the beam passes through the diagnostic stand. If there are no objections, I'll probably just hardcode the motors for the XPP and XCS …
> ENH: Lodcm

- pcdsdevices/epics_motor.py
Something weird in the `EpicsMotor` class in conjunction with the rest of our system spits out pyepics warnings on every move, unless we monitor these values.
> FIX: workaround for pyepics warnings

- pcdsdevices/valve.py
Unhappy discovery while creating a `PPSStopper`. The class constructor overwrites `state_list` and not `states_list` as it should. This means that the `states_enum` is not created correctly which causes a multitude of problems.
> FIX: PPSStopper created state_list not states_list

- conda-recipe/meta.yaml
- pcdsdevices/daq.py
- tests/test_daq.py
- Add calib_at_step that can be safely passed as a `per_step` argument to plans such as `scan`
- Fix bug where under certain conditions the `calib_cycle` plan would have duration zero, instead of the desired duration
- Avoid race conditions where errors spew out at close if `daq.__del__` was called too late
closes #161 
I added a test that makes sure we can use it as a `per_step` hook in `manual` mode and that the scan lasts for three calib cycles.
> ENH: calib_at_step

- pcdsdevices/mirror.py
- tests/test_mirror.py
The tests did not accurately reflect the naming scheme for the `FEE` HOMS mirrors. This caused an issue with the way we load the `YGantry.gantry_prefix`. The tests have been updated to reflect reality and we are able to load the mirror information with:
```python
fee_m1 = OffsetMirror('FEE:M1H', name='fee_m1h', prefix_xy='STEP:M1H', xgantry_prefix='STEP:FEE1:611:MOTR')
xrt_m1 = OffsetMirror('XRT:M1H', name='xrt_m1h')
```
> FIX: Mirror prefixes

- pcdsdevices/__init__.py
`setup_ophyd` installs the `MonitorDispatcher` which makes `pyepics` run more reliably.
We learned about `setup_ophyd` today. We can put it here so that all users of `pcdsdevices` at lcls don't have to worry about setting it up.
> FIX: call setup_ophyd at init

- .travis.yml
- dev-requirements.txt
- docs/Makefile
- docs/source/_templates/autosummary/base.rst
- docs/source/_templates/autosummary/class.rst
- docs/source/_templates/autosummary/module.rst
- docs/source/api.rst
- docs/source/conf.py
- docs/source/epics_types.rst
- docs/source/index.rst
- docs/source/inout.rst
- docs/source/state.rst
- pcdsdevices/attenuator.py
- pcdsdevices/device_types.py
- pcdsdevices/doc_stubs.py
- pcdsdevices/epics_motor.py
- pcdsdevices/inout.py
- pcdsdevices/ipm.py
- pcdsdevices/lens.py
- pcdsdevices/lodcm.py
- pcdsdevices/mirror.py
- pcdsdevices/movablestand.py
- pcdsdevices/mps.py
- pcdsdevices/mv_interface.py
- pcdsdevices/pim.py
- pcdsdevices/pulsepicker.py
- pcdsdevices/signal.py
- pcdsdevices/slits.py
- pcdsdevices/state.py
- pcdsdevices/valve.py
- Rework the docs
- Make sure all top-level boxes have text in them
- Make sure everything links together
- Give everything a once-over
- Full API docs
- Add flake8 check to the CI
- Add devices to `device_types`
- Docs need to be in an ok state prior to thurs
- flake8 is good
Docs build on my machine
This is docs
- I added a `doc_stubs` submodule because I found myself repeating a few bits way too many times. This isn't used everywhere but I think it's an ok inclusion.
- Note that I've done something sneaky here and I've overridden the autosummary templates to generate more layers of linked doc files. So this actually ends up making a `generated/generated/generated` directory, hilariously. I think the result looks nice because you can keep clicking down further and get all of the full …
> DOC: Clean up the docs

- .gitignore
- conda-recipe/meta.yaml
- pcdsdevices/attenuator.py
- pcdsdevices/epics_motor.py
- pcdsdevices/mirror.py
- pcdsdevices/mv_interface.py
- pcdsdevices/slits.py
- tests/test_mv_interface.py
Allow our special interface to save preset positions to yaml files. This is a port/rework of the old hutch python feature.
There will be one of these files per device that has presets, or multiple if we're running out of multiple paths. The file will be called `devicename.yml`.
```
pi:
active: true
comment: the constant
history:
26 Mar 2018 17:33:20: 3.1415926535
last_updated: 26 Mar 2018 17:33:20
value: 3.1415926535
uno:
active: false
history:
26 Mar 2018 17:33:08: 1.023
26 Mar 2018 17:33:11: 1
last_updated: 26 Mar 2018 17:33:11
value: 1
zero:
active: true
history:
26 Mar 2018 17:32:42: 0
26 Mar 2018 17:32:45: 0
26 Mar 2018 17:32:46: 0
26 Mar 2018 17:32:57: 0.0234
last_updated: 26 Mar 2018 17:32:57
value: 0.0234
```
If presets are configured using `setup_prefix_paths`, then there will be …
> ENH: Presets on FltMvInterface

- pcdsdevices/mv_interface.py
Wait for the file lock with a timeout instead of immediately giving up.
The file lock error prevents presets from loading, so if it's a manner of a short wait we shouldn't go straight to throwing an error.
Tests still pass, they just take a little longer because we're waiting more in the file lock test.
> FIX: Wait a second for file lock

- tests/test_epics_motor.py
`wait_for_connection` in fixture to avoid race condition when calling `move`
In response to #189
> TST: wait_for_connection in PCDS motor fixture

- pcdsdevices/epics_motor.py
This PR adds the disabled attribute (.DISP) to the epics_motor class. This will allow users to enable/disable the motor when they see fit.
This was added to disable the motors if needed when changing the CXI beamline configuration (moving the stands). If one of the motors moves to the wrong position, all the motors will stop moving and be disabled. This is also a safety check prior to moving the motors.
> ENH: Add disable puts field (.DISP) to PCDSMotorBase

- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/sequencer.py
- tests/test_sequencer.py
A basic `EventSequencer` object. 
This handles **only** starting and stopping the `EventSequencer` in the various modes of operation. Actually configuring what the sequence loaded is should be discussed outside of this PR. 
I suspect the main controversy will be the fact that this is a `bluesky` flyer. I decided to go this route because the `set` method does not make much sense. In reality most of the time you want to start and stop the Event Sequencer as two entirely separate actions.  This works especially nicely if you just want to run the sequencer the entire time you are scanning:
```python
fly_during_wrapper(my_scan, [sequencer])
```
I do agree that when you want to keep starting and stopping the sequencer during a scan it is a little more awkward, but I don't think the `set` and …
> EventSequencer

- pcdsdevices/epics_motor.py
- tests/test_epics_motor.py
Posting this for discussion now, will add tests later if we decide this is the best way forward.
* Adds a general `_clear_flag` function used by `clear_powerup`, `clear_stall` and `clear_error`
* Add a `reinitialize` function
* Wraps these in a nice `auto_setup` method.
This is pretty much a straight port of the `auto_setup` functionality in the old `blbase.Motor` for setting up IMS motors with the notable exception of the `ParameterManager`. The minor improvements are that these methods all return status objects so they can be done asynchronously and they are pulled from a `bit_flags` dictionary instead of module variables.
Also, should `auto_setup` go in `stage`? Obviously not if we include the ParameterManager but as it is now it might make sense to run this at the start of scans. …
> ENH: Clear flags, reinitialize, autosetup

- tests/test_mv_interface.py
closes #206 
Nearest I can tell, `flock` on NFS doesn't work unless the file is opened in write or append or some equivalent mode... We don't "need" to write to the file to run the test here, but empirically it seems like we do need it to avoid an exception on NFS.
The code bit here is simply starting a second process and locking the file, and checking that the presets behave as expected in this situation. The `mp.Lock` is used to tell the process to release the file lock.
> FIX: flock test on NFS

- pcdsdevices/inout.py
- pcdsdevices/ipm.py
- pcdsdevices/lodcm.py
- pcdsdevices/pim.py
- pcdsdevices/pulsepicker.py
- pcdsdevices/state.py
- tests/test_inout.py
- tests/test_ipm.py
- tests/test_lens.py
- tests/test_lodcm.py
- tests/test_mirror.py
- tests/test_pim.py
- tests/test_pulsepicker.py
- Add EPICS enums as primary aliases
- Put integer instead of str for moves
- Map transmissions with integers
- Adjust IPMs to work with these changes
- Fix bug where readback was broken for all IPM
- Remove redundant docstrings
Force IOCs to have the same PVs for configuring the same devices. Take the EPICS enum so that users can create aliases in EPICS.
closes #203 
closes #150 
Updated tests and it works with the real IPM objects
> ENH: States Updates for IPM and XFLS

- pcdsdevices/mirror.py
- tests/test_mirror.py
The mirrors in the XRT do not use the standard states records from the IMS record. There was a conversion error for the `enum_strs` and `IN` and `OUT` are reversed. After #205 we are no longer using the string to check states but instead use the integer, this uncovered this bug.
It is a little interesting how this bug manifested itself. It looks like the `states_enum` only added `Unknown` and `Inserted`.
Closes #214 
Works on live devices. Updated tests to use proper `enum_strs`
> ENH: Mirror state

- pcdsdevices/state.py
- tests/test_state.py
- Raise a `ValueError` with a helpful string if something has gone wrong in creating the states enum
This is related to #214, to make it more obvious what has happened in these instances.
- Fix a bug where `None` could make it into the `_valid_states` list if used as a skip state
- Fix a bug where transmission would be malformed if `None` used as a skip state
In practice we aren't using this incidental `None` skip state feature, but I wanted to maintain it just in case. I noticed these bugs because other tests started failing after fixing the original bug.
> ENH: fail in an obvious way if state is bad

- pcdsdevices/mv_interface.py
- tests/test_mv_interface.py
Before updating the presets, check the types
I ran into a bug while writing presets documentaiton. If the wrong type slips through here, the exception handling brings the open file into a bad state for the rest of the python session.
Added two tests.
This is innocuous enough that I'll pull it in without review if the travis passes, because Teddy is on vacation.
> FIX: Check for types before doing file ops

- docs/source/api.rst
- pcdsdevices/beam_stats.py
- pcdsdevices/signal.py
- tests/test_beam_stats.py
- tests/test_signal.py
- Port and update `AvgSignal` from `pswalker`
- add `mj_avg` field to `BeamStats`
- `AvgSignal` was useful for suspenders, and it will be useful in `nabs` for the suspend-and-drop construct I'm working on
- The beam mj level is a common thing to be averaged, since an individual reading going bad does not necessarily mean the beam is down.
Tests added, and did "feel" tests on psbuild-rhel7
- `AvgSignal` automatically included in API docs
- `BeamStats` added to API docs
> ENH: Add AvgSignal, add mj_avg to BeamStats

- docs/source/api.rst
- docs/source/index.rst
- docs/source/releases.rst
I went as far back as the release notes were actually good. The idea is that all future PRs add a summary of their changes to this release notes page, so when we make a new release we just have to copy/paste a text blob and maybe change formatting.
I'm going to go through and do this on a bunch of our repos.
> DOC: Add release history page

- pcdsdevices/epics_motor.py
- tests/test_epics_motor.py
Implemented motor SPG field to PCDSMotorBase
Calling <motor>.stop(), <motor>.pause(), and <motor>.go() will put to the EPICS .SPG field and stop pause or resume motion.  <motor>.check_value also considers the .SPG state 
The .SPG field is used by operators all the time from the expert screen.  Having it in Python will help abort moves or contrain motors easily. 
Tested in pcdsdevices test suite (run_tests.py) with a test that checks .SPG puts in test_epics_motor.py
I think Sphinx does this, right?
> PCDSMotorBase .SPG Implementation

- pcdsdevices/beam_stats.py
This PR adds new static components to BeamStats object.
The BeamStats objects now has two additional PVs. `accel_ev` watches the accelerator-reported ev levels and the other, `sxr_gmd`, watches the SXR GMD. The accelerator-reported ev levels, `accel_ev`, update much more quickly than the `ev` component that already exists in the object.
These additions provide the necessary PVs for basic tests of the [auto_monochromator](https://github.com/pcdshub/auto_monochromator). The module uses a tiny event builder and so requires high time-resolution information in order to better generate complete event-built sets with which to generate histograms.
The object has been instantiated in an iPython session and the new components are able to get values and subscribe callbacks.
An in-line comment has …
> Beam stats additions

- conda-recipe/meta.yaml
- pcdsdevices/__init__.py
- pcdsdevices/beam_stats.py
- pcdsdevices/epics_motor.py
- pcdsdevices/mps.py
- pcdsdevices/sequencer.py
- tests/conftest.py
- tests/test_attenuator.py
- tests/test_beam_stats.py
- tests/test_device_types.py
- tests/test_epics_motor.py
- tests/test_inout.py
- tests/test_ipm.py
- tests/test_lens.py
- tests/test_lodcm.py
- tests/test_mirror.py
- tests/test_movablestand.py
- tests/test_mps.py
- tests/test_mv_interface.py
- tests/test_pim.py
- tests/test_pulsepicker.py
- tests/test_sequencer.py
- tests/test_slits.py
- tests/test_state.py
- tests/test_valve.py
- use `make_fake_device` instead of `using_fake_epics_pv` for testing reliability
- force `ophyd>=1.2.0`
- fix minor issues that I found while making tests
- Add a hotfix on top of the fake device maker, should be submitted as an `ophyd` PR but for now it makes the tests work
- more reliable tests
- the tests broke the old way with the new ophyd
It is tests
It doesn't need explicit documentation.
Note that this will possibly necessitate changes in the other open PRs if this one comes first, or this will need additional changes if the other open PRs come first.
> MNT: Update tests for ophyd 1.2.0, fix minor bugs

- pcdsdevices/epics_motor.py
- pcdsdevices/mv_interface.py
- tests/test_epics_motor.py
Implemented the camonitor such that it displays the current position of the motor until Ctrl+C is used.
- Transfering old wm_update into python 3 code.
- addresses issue:  https://github.com/pcdshub/pcdsdevices/issues/183
- used a disconnected moving motor to test current moving position 
- Function was implemented in IMS(PCDSMotorBase)
> Camonitor Implementation 

- .travis.yml
- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/epics_motor.py
- pcdsdevices/mv_interface.py
- tests/test_device_types.py
- tests/test_epics_motor.py
- tests/test_mv_interface.py
- Add the `Beckhoff` class for controlling the motor record from ESS.
- Add specific error classes for things like SPG and DISP
- Pare down unnecessarily wordy docstrings (when your function just sets the property, you don't have to copy the whole thing again...)
- Refactor `epics_motor` module to split the things we voluntarily add to the base `EpicsMotor` class from the things we are forced to add because our "motor-record-like" IOCs aren't quite compliant.
- Refactor the tests to be more thorough
- We needed a `Beckhoff` class that could at least reset the errors. We may need to add more later, but it's unclear.
- The refactor was the cleanest way to include the `Beckhoff` class.
- I felt like the tests were weak here, we didn't even instantiate most of the classes. I parametrized the …
> ENH: Beckhoff Axis Class (and some refactor)

- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/evr.py
- tests/test_evr.py
This was created for an `mfx` experiment and not placed in the common code base ... until now! Expecting that this shouldn't be terribly controversial, this is more of a shell to later add features. The goal was to just put the proper signals in without doing anything too fancy. This PR just contains a Trigger class, valid for either `PMC` or `SLAC` EVR, I left those classes alone for now but could be willing to add them if we thought they would be useful. 
Closes #172 
Add a test for the one function in the class. Verified behavior for all signals on a real `EPICS` EVR.
Added to the `device_types` page.
> ENH: Trigger

- pcdsdevices/areadetector/detectors.py
This means we'll act on the low rate or ROI'd image. This is the most obvious part of #225 to keep.
> FIX: use IMAGE2, matching the docstring.

- pcdsdevices/state.py
- tests/test_state.py
`PVStateSignal` now gives more information about itself in the `describe` dictionary for downstream consumers. This includes the `enum_strs` and which signals it is summarizing. This was largely for compatibility with `Typhon`, but I think it could be a helpful debugging tool.
```python
{'mfx_dg1_vgc_01_state': {'dtype': 'string',
'enum_strs': ['Unknown', 'IN', 'OUT'],
'shape': [],
'source': 'SUM:mfx_dg1_vgc_01_open_limit,mfx_dg1_vgc_01_closed_limit'}}
```
Added a test for the contents of the `describe` dictionary
> MAINT: PVStateSignal Description

- docs/source/api.rst
- docs/source/base_classes.rst
- docs/source/epics_types.rst
- docs/source/index.rst
- pcdsdevices/ccm.py
- pcdsdevices/device_types.py
- pcdsdevices/pseudopos.py
- tests/test_ccm.py
- tests/test_pseudopos.py
- Add `CCM`, which includes two coordinated motor assemblies and an `energy` pseudomotor
- Add `SyncAxes` class factory
Unfortunately, the CCM currently uses a bunch of magic constants for the calcs and kwargs for the in/out positions.
closes #222 
- Need a CCM for XPP (eventually XCS will use theirs again maybe), and for downstream hutches to verify CCM is out
- Need conventions for synchronized axes and calculation motors
Added tests
Added to device docs
> ENH: CCM, Conventions for Combined Axes and Calc Motors

- pcdsdevices/mv_interface.py
closes #260 
Switch the presets registry to be a `WeakSet` instead of a `dict`. This is because names are not unique and we will avoid overwriting another element of the registry. This is not an API break because the registry is marked as an internal-only resource.
Use a `WeakSet` instead of a `set` because we don't want to permanently hold references to dropped devices.
> FIX: do not register by name, names are not unique

- pcdsdevices/lodcm.py
- tests/test_lodcm.py
Basic split between XCS and XPP foils...
closes #137 
classes should work out of the box
Added in_states check.
> FIX: split the XPP and XCS lodcm foils

- pcdsdevices/inout.py
- pcdsdevices/pseudopos.py
- pcdsdevices/state.py
- tests/test_inout.py
- tests/test_pseudopos.py
- tests/test_state.py
Raise a concise, helpful error when a user tries to create a base-class-only device.
This used to give a wide range of unintelligible errors depending on which class you picked.
Added tests
Some docstrings updated to indicate that subclassing is needed
> FIX: Warn user about subclassing base classes

- pcdsdevices/valve.py
External applications may want to check whether a move is possible without requesting one. Because `PPSStopper` and `GateValve` had interlock logic hidden in `_do_move` this was not possible. This places that functionality within `check_value`. 
We may still want to make this process more explicit, but this is the first step.
Related but might not fully close #259 
Existing interlock tests still pass
> MAINT: Interlocks belong in check_value

- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/inout.py
- setup.cfg
* Add a basic `Reflaser` class with an icon
* Change `TTReflaser` to inherit from the new base `Reflaser`
Also added a bit to `setup.cfg` so `flake8` wouldn't search in the `docs` or `pcdsdevices/areadetector` folders. Maybe something we should consider adding to standard packaging
`Reflaser` wants an icon for the `lightpath` but we were just using `InOutRecordPositioner` before. This gives us a way to have a unique icon and also gives a nice blueprint if anyone wants to expand on the class.
Added to `device_types` table
> ENH: Reflaser

- pcdsdevices/epics_motor.py
Add `.DESC` field to standard `EpicsMotor` interface.
Requested by @koglin
> MAINT: Add DESC field on motor interface

- pcdsdevices/attenuator.py
- pcdsdevices/mirror.py
- tests/test_attenuator.py
Both the `OffsetMirror` and the `Attenuator` classes didn't have `SUB_STATE` subscription types. This confused the `lightpath`:
A call to subscribe to the  `SUB_STATE`  method subscribes to all of the filter states. Any change in state of a child filter triggers a call. This is better than the alternative of subscribing to the actual transmission value which jitters with beam energy.
The `OffsetMirror` never changes states. It is always considered inserted. The `SUB_STATE` is never called. This is slightly hacky and I can be convinced to remove it, but it solves my problem for now 😄 
Related to https://github.com/pcdshub/lightpath/issues/75
Added a test in the attenuator class for the `SUB_STATE` subscription call
> MAINT: Subscription States

- pcdsdevices/state.py
- tests/test_state.py
This is a tad bit of a hack but makes life easier for our users (a.k.a me). We now watch for input that looks like `device.move("2")`
> MAINT: StateDevice accepts strings that are numbers

- pcdsdevices/valve.py
- tests/test_valve.py
Noticed today in MFX. I guess we haven't been moving valves in `hutch-python` much...
The PV for the interlock is `OPN_OK` which means a value of 1 is okay to open. This logic was inverted in the class and corresponding tests.
Updated tests and confirmed on real hardware
> FIX: Valve Interlock

- pcdsdevices/slits.py
- tests/test_slits.py
These are some changes to make the Slits nicer to work with in the `lightpath`. Largely reducing complexity and making their behavior easier to understand.
1. No more complex `transmission` calculation based on their `nominal_aperture`. If either dimension of the slit is closed past the `nominal_aperture` they are inserted, otherwise they removed.
2. `nominal_aperture` is now an `AttributeSignal`. This field will be populated by the `happi` database and now contained in the `Typhon` screen 😄
3. I added a few lines in the `Slits.__init__` to change the `Kind` of its children. I think this is the proper way to handle this situation in this case although it looks a bit strange. If you load the `SlitPositioner` by itself the `readback` should be a `hint` and the `setpoint` should be `normal`. …
> MAINT: Slit Interface

- pcdsdevices/sequencer.py
- tests/test_sequencer.py
The EventSequencer now has a `trigger` method that institutes the following behavior:
* If set to run forever, the returns a Status thats is done right away
* If set to a finite run time, wait for the Sequencer to complete its run
Allows for use in of both the DAQ and the EventSequencer together with a simple:
`trigger_and_read` call.
Added a test for new behavior
Docstrings updated. A thorough explanation of how to utilize this object in conjunction with the DAQ is probably owed, but maybe not in this repository
> ENH: EventSequencer Trigger

- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/epics_motor.py
- tests/test_epics_motor.py
Instead of sorting out which kind of motor you have, we should be able to tell based on the prefix it self. To solve this I wrote `Motor`. This snoops the `prefix` finds the correct class and instantiates it
Main motivation is ease of use for `happi`. Instead of having a one to one relationship between containers and classes, we should be building these factories that do the correct thing with the information provided. This simplifies the dependencies between the two libraries as we can repoint the objects by modifying the factories, not changing class specifications on both ends.
Added a test
Add to `device_types` table
> Motor Factory

- pcdsdevices/sequencer.py
- tests/test_sequencer.py
Add in ability to read/write sequences to the event sequencer. 
<sequencer_object>.sequence.read() to read the current sequence,  <sequencer_object>.sequence.write(sequence) to write a new sequence.
Should not require any adjustment to the instantiation of the event sequencer  object. The sequence class initializes itself based on the prefix for the event sequencer. 
Needed for MEC to run the laser in BlueSky/Ophyd hutch python. Should be useful for other hutches as well.
Appears to address issue #198.
Tested it on  MEC event sequencer with my local copy of mecpython and pcdsdevices.
I put in docstrings as I thought appropriate. I'm sure these could be improved.
> ENH: Event Sequence Read/Write

- conda-recipe/meta.yaml
- pcdsdevices/mv_interface.py
- tests/test_mv_interface.py
- Stop using `pylab` directly to simplify things
- Move imports of `pyplot` into methods to avoid selecting a backend early
- Pin `matplotlib` to under 3 because the conda builds are a mess
- No reason to use `matplotlib` indirectly, made things harder to debug
- Backends why
- `3.0.0`+ conflicts with `pmgr` because something something `pyqt` must be `5.9`, but then it also breaks the travis here because it somehow installs `3.0.0` with pyqt `4.11`. I have no idea what is going on, I assume the recipes are broken.
> FIX: The build was broken because Matplotlib/Conda

- pcdsdevices/areadetector/detectors.py
- pcdsdevices/areadetector/plugins.py
- tests/test_pim.py
Adds all common plugins to PCDSDetector
Plugins are available for most (all?) PCDS detectors and should be accessible to the user.
Interactively with CXI inline detectors. Default port chain information from `CXI:SC2:INLINE:` as it appears unmodified - but this may need revision.
See docstrings
The leading `':'` has been stripped from all plugins. The logic is that the prefix should be what all PVs of a device have in common. This could be put back, but I wouldn't recommend it.
This means that beamline configurations need to be updated with the correct prefixes.
PCDSDetector-related local changes should be brought back to ophyd. @teddyrendahl @ZLLentz and I should discuss what should remain for local customizations, if any.
> ENH: add common plugins to PCDSDetector

- pcdsdevices/epics_motor.py
Probably the longest, most complicated pull request from November. Had to get something in before my github contributions grid goes blank.
Originally, there was a dash in here, but I'm going to make it a colon in the L2SI IOC. It's a choice made by the IOC developer. The colon is more consistent with what we do elsewhere in SLAC.
The dash IOC doesn't even exist anymore and was solely a test/prototype.
> MNT: Use a normal separator for BeckhoffAxis

- pcdsdevices/sequencer.py
- tests/test_sequencer.py
Updated the event sequencer to take more readable sequences. Now, instead of giving the event sequencer a list of four lists that contain the beam codes, beam deltas, fiducial deltas, and burst counts for each line, you give the sequencer a list of lists, where each sub-list represents a single line of the event sequence. For example:
> seq = [[182,12,0,0], [170,2,0,0], [169,0,0,0], ....]
> sequencer.sequence.put_seq(seq)
This should make writing code to generate sequences for the event sequencer a little simpler and more straight forward. Also, I like it more.
Tested on MEC event sequencer. I basically wrote in the wrapper that I used in MEC for LU57 into the ophyd device. I wrote a wrapper because the old way was kind of annoying. I updated the tests for the sequencer as well, and they …
> ENH: Update event sequencer to take more human readable event sequences

- conda-recipe/meta.yaml
- tests/conftest.py
- tests/test_epics_motor.py
- tests/test_inout.py
- tests/test_ipm.py
- tests/test_lens.py
- tests/test_lodcm.py
- tests/test_mirror.py
- tests/test_pim.py
- tests/test_pulsepicker.py
- tests/test_valve.py
Removes unnecessary (*) hotfix for FakeEpicsSignal.
\* as of ophyd V1.3.1
All are passing locally except for test_lodcm_destination.
> MNT: remove hotfix

- tests/test_lodcm.py
Call `move` method in lodcm tests so that aliases are respected
Was calling `put` directly on the fake pvs, which fails with enum checking
closes #323 
Same tests, new pass
N/A
> TST: fix lodcm test

- docs/source/api.rst
- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/doc_stubs.py
- pcdsdevices/epics_motor.py
- pcdsdevices/gauge.py
- pcdsdevices/pump.py
- tests/test_gauge.py
- tests/test_pump.py
Adding classes for (ion) pumps and vacuum gauges
new files for (ion) pumps and vacuum gauges have been created w/ tests
shared doc strings have been added to doc__stubs
the old hutch python had classes for these devices and I would like to replicate coverage
additionally, these classes show allow us to inspect the vacuum along a beam line from the command line.
I have checked more complicated functions on a few vacuum devices in the XCS line.
The classes have docstrings.
> Vacuum lcls i

- .travis.yml
See title
All the dependencies are available now, so we should be preparing for the long-delayed migration to 3.7 as the standard version
> CI: require 3.7 build passing

- pcdsdevices/epics_motor.py
Change the PV name for the error reset signal on beckhoff axis, add status string.
These are useful signals. The ethercat motor IOC has these dashes hard-coded, so we'll just live with them.
Working live at my desk.
> ENH: sync BeckhoffAxis with the new IOC, and add status string

- pcdsdevices/ipm.py
- pcdsdevices/lodcm.py
- pcdsdevices/state.py
- tests/test_ipm.py
- tests/test_lodcm.py
- tests/test_pim.py
- tests/test_state.py
As of the newest `IMS` release I did, all state device records contain a convenient `:MOTOR` alias to the motor whose position is associated with the state. This PR replaces the previous janky `readback` signal with this `motor` subcomponent.
This PR adjusts the `IPM` and `LODCM` classes as well, because their previous structures were an unstable abuse of inheritance and doing this change broke the classes entirely. The previous structure was a state positioner that contained other state positioners, but this is not how the PVs are structured at all, giving an awkward class definition. These are now container devices that, while not positioners themselves, contain many subcomponent state positioners.
This was the cleanest way to allow us to have state devices with direct access to the …
> ENH: Add motor to state devices

- pcdsdevices/areadetector/detectors.py
- pcdsdevices/pim.py
- tests/test_pim.py
Use sed to replace `PCDSDetector` with `PCDSAreaDetector`
Requested by @silkenelson to avoid confusion with other pcds-group detectors that are not epics area detectors.
It might pass the tests
It will need to end up in the release notes under API breaks.
Note that this probably needs corresponding changes in some other libraries...
> API: rename PCDSDetector to PCDSAreaDetector

- pcdsdevices/sequencer.py
- tests/test_sequencer.py
The event sequencer's `trigger` method will now correctly look for the sequence done transition instead of the sequence start transition
We are not ready to read our detectors until the sequence is done, so the trigger should not return done until after the sequence
> FIX: Look for end transition instead of start transition

- tests/test_utils.py
Add a newline terminator to the ctrl+c on inputs test.
This test stalls on my local machines without the newline terminator and it's really annoying
> TST: make this test not hang on my local machine

- .travis.yml
- conda-recipe/meta.yaml
- dev-requirements.txt
I want to make one package noarch and py3.8 each day until we catch em all
I put the style checks and the docs build into their own jobs, and I also cleaned up the CI a bit, unfortunately working on a parallel path from @klauer and @n-wbrown on the ci-helpers stuff. Possibly going to contribute to that effort and then redirect this code to call stuff from there.
noarch is more efficient and portable
doing docs build and style checks in their own jobs lets us easily see which is failing
It is tests
> CI: Cleanup and BLD: noarch

- .travis.yml
- setup.cfg
Make sure the tests are the last command run in the `if` blocks
Only the last command in the `if` block has a return code that is elevated to the main test script. This means in the previous setup we could fail the run_tests and succeed on coverage report and the whole thing would be marked as good.
> CI: Fix cases where failed tests marked as passing

- .travis.yml
- conda-recipe/meta.yaml
Pin run version to before 3.7.6
Fix CI to fail on bad build
```
import epics
File "/u1/zlentz/conda/envs/test/lib/python3.7/ctypes/__init__.py", line 97, in CFUNCTYPE
return _c_functype_cache[(restype, argtypes, flags)]
KeyError: (None, (<class 'epics.dbr.access_rights_handler_args'>,), 1)
During handling of the above exception, another exception occurred:
File "<stdin>", line 1, in <module>
File "/afs/slac.stanford.edu/u/lu/zlentz/pyepics/epics/__init__.py", line 29, in <module>
from . import ca
File "/afs/slac.stanford.edu/u/lu/zlentz/pyepics/epics/ca.py", line 761, in <module>
dbr.access_rights_handler_args)
File "/afs/slac.stanford.edu/u/lu/zlentz/pyepics/epics/dbr.py", line 339, in make_callback
return …
```
> BLD: Incompatibility with python 3.7.6

- .travis.yml
In the test environment, we didn't have anaconda-client installed. This meant that at the end of the tests we were unable to upload to anaconda. This commit makes sure we're in the correct conda env (base) and defers the install of anaconda-client until the very end since it's only needed if we are uploading.
v2.1.0 is not on anaconda despite being tagged
I don't think I can actually test this, beyond that it doesn't break the rest of the CI. If it doesn't work I'll try again. If it gets uploaded to `pcds-dev` then I'll feel confident that the re-tag will be uploaded too.
> CI: Fix issue where package was not uploaded

- pcdsdevices/gauge.py
- pcdsdevices/pump.py
- pcdsdevices/valve.py
Added new ophyd devices for vacuum gauges, pumps, and valves.
New classes have been made for various devices. Some overlap with existing classes and will need to be merged. The new classes are also missing some features such as getter functions for interlock and tab_whitelist.
Allows us to accommodate new devices on the beamline and use them in python & typhos.
I was able to create instances of all of the PLC classes and tested that they work on Maggie's tst IOC, including the ability to create a typhos screen with the device object. Will test the non-PLC devices later and create a new pull request from any necessary fixes.
Each class has a simple docstring which needs to be expanded with more information.
> New vacuum ophyd devices

- conda-recipe/meta.yaml
- pcdsdevices/attenuator.py
- pcdsdevices/ccm.py
- pcdsdevices/gauge.py
- pcdsdevices/interface.py
- pcdsdevices/mirror.py
- pcdsdevices/slits.py
- tests/conftest.py
- tests/test_analog_signals.py
- tests/test_attenuator.py
- tests/test_beam_stats.py
- tests/test_ccm.py
- tests/test_dc_devices.py
- tests/test_disconnected.py
- tests/test_epics_motor.py
- tests/test_evr.py
- tests/test_gauge.py
- tests/test_ipm.py
- tests/test_lens.py
- tests/test_lodcm.py
- tests/test_mirror.py
- tests/test_movablestand.py
- tests/test_mps.py
- tests/test_pim.py
- tests/test_pulsepicker.py
- tests/test_pump.py
- tests/test_sequencer.py
- tests/test_slits.py
- tests/test_valve.py
Upgrade to new `ophyd` land a little early.
Correct the arguments on our tab completion `__init_subclass__` and properly pass them through so that new `ophyd` land works properly.
Set up extra tests with timeouts for instantiation of all epics devices. Fix devices so that they pass these tests (every device should instantiate quickly even with no connected PVs). In most cases the issue is that calls to `Signal.subscribe` halt/time out if we don't specify `auto_monitor=True` in the component definition, since `ophyd` tries to force these into `auto_monitor` state if not already there. We have control over our device definitions and know that these should always be monitored because a subscription is planned during init, so we do this in the class definition now.
New `ophyd` land is a …
> BLD: Update to ophyd=1.4.0rc4 and FIX: initialization bugs

- pcdsdevices/state.py
- tests/test_state.py
If `states_list` isn't provided in a states device, use the metadata callback to get it.
Cleans up some device definitions to be simpler and more logically consistent.
Silke asked for not having to make a separate timetool class for each hutch. I want to use this to clean up our device implementations and make it easier going forward.
One test was added
Docstrings and comments
> ENH: make states_list optional

- docs/source/releases.rst
This release probably won't be the newest for too long, but the fact that we're upgrading ophyd versions is enough to warrant a tag
> DOC: add release notes for v2.3.0

- conda-recipe/meta.yaml
- pcdsdevices/signal.py
- tests/test_signal.py
Add `PytmcSignal` to connect to the PVs created by `pytmc` using the same arg as in the `pytmc` pragma.
Should be really straightforward to make these pytmc pvs without picking between classes and typing _RBV in the right places
Added basic tests, checked that the read and write PVs are what I expected, and connected to sample PVs in a live IOC
Included in the autodocs by default
> ENH: add PytmcSignal class

- docs/source/api.rst
- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/epics_motor.py
- pcdsdevices/inout.py
- pcdsdevices/interface.py
- pcdsdevices/mps.py
- pcdsdevices/pim.py
- pcdsdevices/sensors.py
- pcdsdevices/signal.py
- pcdsdevices/state.py
- tests/conftest.py
- tests/test_epics_motor.py
- tests/test_inout.py
- tests/test_pim.py
- tests/test_state.py
Add PPM and XPIM classes. Add various other helper classes that may be useful to people developing with TwinCAT devices. Small fixes.
This is not complete, but it is far enough along for volunteer reviews. I will request reviews once I finish the TODO list.
Gotta get stuff ready
Added tests for the code and checked against real PVs. One more check is needed once I fix the IOCs.
Autodocs and docstrings have been updated appropriately.
> ENH: Add PPM, XPIM, and supporting classes

- .travis.yml
Add build docs to the allowed failures
We DO want the docs to succeed, but we do not want to wait 20 minutes to get the unit test and style pass/fail summary on the PR (which happen on the order of 5 minutes)
> CI: allow docs failure to let build finish before docs are done

- pcdsdevices/mirror.py
Added components for each mirror PVs to `pcdsdevices.mirror.HardOffsetMirror`. These include the motor record of each axis (Yup, Ydwn, Xup, Xdwn, Pitch, Bender), gantry status/configuration (current Y/X gantry, coupling/decoupling signals), and RMS differences between encoder readback and axis setpoints (again for Y, X, Pitch, and Bender). 
These changes are necessary for `lucid` to produce control screens using `typhos` for mirror systems MR1L0, MR2L0, and MR1K4 (1st generation Axilon systems refurbished to use Beckhoff controls)
Ran automated tests within this repository to ensure nothing was broken. Instantiated ophyd object/produced typhon screen through the following code snippet:
On `lfe-console` with `conda-dev` sourced:
```
import importlib.util # for loading dev version
import …
```
> ENH: Filling in stubs for Beckhoff controlled mirror classes, both 1st and 2nd generation

- pcdsdevices/pump.py
changed PIPPLC class by adding state_rbv and SP_DI->HV_DI
Updating ion pump plc logic. The state variable has been addded to report whether or not the pump is off, starting, on, faulted. 
The SP_DI was changed to the HV_DI because the relay output is used to report the ion pump output state.
> MNT: changed PIPPLC class by adding state_rbv and SP_DI->HV_DI

- pcdsdevices/mirror.py
Changed each motor component of `mirror.XOffsetMirror` from `EpicsSignal` to `BeckhoffAxis`
Noticed readback field was always agreeing with its setpoint due to not differentiating the two when using `EpicsSignal`. Instead using `BeckhoffAxis` takes care of this.
Instantiated mirror in IPython session and inspected components:
```
In [1]: from pcdsdevices.mirror import XOffsetMirror
In [2]: mr2l0 = XOffsetMirror('MR2L0:LFE', name='mr2l0_lfe')
In [3]: mr2l0.component_names
Out[3]:
('y_up',
'y_dwn',
'x_up',
'x_dwn',
'pitch',
'bender',
'gantry_x',
'gantry_y',
'couple_y',
'couple_x',
'decouple_y',
'decouple_x',
'couple_status_y',
'couple_status_x',
'y_enc_rms',
'x_enc_rms',
'pitch_enc_rms',
'bender_enc_rms')
In [4]: mr2l0.pitch.component_names
Out[4]:
('user_readback',
'user_setpoint', …
```
> BUG: Changed motor components to BeckhoffAxis to properly capture reaback and setpoints

- pcdsdevices/valve.py
MNT: Fixed Valve.py VGC MPS status with correct PV, MPS_FAULT_OK_RBV
I forgot to put in _RBV in the previous commit and therefore the expert screens don't show up correctly.
> MNT: Fixed Valve.py VGC MPS status with correct PV, MPS_FAULT_OK_RBV

- pcdsdevices/gauge.py
Make GCC protection set point writable. 
Without this cold cathode gauges cannot configure the point at which they enable. 
Unit tests pass.
> BUG: gauge protection setpoint should be treated writeable

- pcdsdevices/epics_motor.py
Just changing the `kind` attribute of `epics_motor.BeckhoffAxisPLC.cmd_err_reset` from `omitted` to `config` so that we have access to it from a Typhos screen.
One needs to write to this variable after an NC error to resume motion through epics and it is convenient to have it on the control screen.
After setting `PYTHONPATH` to look first for a local version, the following command generates a test screen with the reset parameter shown in the `config` window:
`typhos 'pcdsdevices.mirror.XOffsetMirror[{"prefix":"MR1L0:LFE"}]'`
> ENH: changed cmd_err_reset so its accessible from a typhos screen

- pcdsdevices/doc_stubs.py
- pcdsdevices/pim.py
- tests/test_pim.py
Changed hierarchy so that a PIM object has an InOutPositioner instead of being one.
Added classes for multiple configurations for PIMs which have LEDs, focus motors, or both.
Looking for feedback on a bunch of things. e.g. I'm not sure if the way I did some things is allowed/good practice. Also, please let me know if you have any suggestions for better class names or the current ones don't follow naming standards.
Gives a better representation of what's actually on the beamline and allows for better control of the device.
Hasn't yet.
Docstrings
> ENH: Update PIM classes

- pcdsdevices/mirror.py
Simple change: just updated RMS component suffixes to match the PVs I changed to better follow the naming convention.
> MNT: Change encoder rms cpts to match pv name change

- .travis.yml
- conda-recipe/meta.yaml
Remove `defaults` from conda channels list in travis build.
I'm planning to do this on the env builds because of exactly the issue here: https://travis-ci.org/github/pcdshub/pcdsdevices/jobs/661244275
There's some crossplay issues between `conda-forge` and `defaults` that we've been lucky to avoid up to this point. We can no longer ignore it, and we need `conda-forge`, so we're axing defaults.
It was not
It will not be
> CI: ban defaults channel from travis build

- docs/source/releases.rst
Build issue delayed release by a day. Temporary solution is to use an old build of conda. Also adding note for a PR that was merged in during the meantime.
> Update v2.4.0 release notes

- pcdsdevices/inout.py
- tests/test_inout.py
At some point the TwinCAT Enum had a non-standard setup here, but it was fixed and the class was never adjusted.
All devices that use this class with the newest PLC code do not work
> FIX: "typo" in TwinCAT states class

- pcdsdevices/component.py
- tests/test_component.py
Add `UnrelatedComponent` to help handle cases where we create "FrankenDevices" where many unrelated components (in the ophyd sense, with unrelated prefixes) are needed to be included in the same ophyd device. Functionally, the devices behave the same for the end-user, but can be implemented much more succinctly in the library here. See the example from the tests:
```
from ophyd.device import Component as Cpt
from pcdsdevices.component import UnrelatedComponent as UCpt
class Basic(Device):
apple = UCpt(Device)
sauce = UCpt(Device)
empty = Cpt(Device, ':EMPTY')
def __init__(self, prefix, *, name, **kwargs):
UCpt.collect_prefixes(self, kwargs)
super().__init__(prefix, name=name, **kwargs)
basic = Basic('PREFIX', name='basic', apple_prefix='APPLE', sauce_prefix='SAUCE')
```
This works …
> ENH: Add UnrelatedComponent

- pcdsdevices/signal.py
- tests/conftest.py
Extract `FakePytmcSignal` from `conftest.py` to `pcdsdevices/signal.py`
Fake devices that include `PytmcSignal` don't work because `PytmcSignal` is not a suitable base class. The conftest patch fixes this for the tests here, but bringing it out allows us to use fake devices that include `PytmcSignal` in other contexts.
closes #422 
If the tests still pass, this worked.
Docstrings edited as appropriate.
> MNT: Bring FakePytmcSignal into main module

- conda-recipe/meta.yaml
- pcdsdevices/epics_motor.py
Override `ophyd`'s `EpicsMotor` limit signals with `auto_monitor=True`.
Replace our signals with the new names decided upon in `ophyd`.
`subscribe` on a non-auto_monitored signal blocks on connection, which is not ok during init. The subscribe calls were added in a recent `ophyd` PR. This PR would not be needed at all if https://github.com/bluesky/ophyd/issues/847 was solved. I will make an ophyd PR to similarly stopgap this on the ophyd end, but this PR will still be needed after that to keep providing some of the methods here. (and then we'd be able to drop the redundant component definitions)
closes #425
> MNT: kluge to make tests pass for now

- conda-recipe/meta.yaml
- pcdsdevices/attenuator.py
- pcdsdevices/epics_motor.py
- pcdsdevices/interface.py
- pcdsdevices/mps.py
- pcdsdevices/pim.py
- pcdsdevices/slits.py
- pcdsdevices/state.py
- tests/conftest.py
- tests/test_attenuator.py
- tests/test_beam_stats.py
- tests/test_ccm.py
- tests/test_epics_motor.py
- tests/test_gauge.py
- tests/test_mirror.py
- tests/test_sequencer.py
- tests/test_signal.py
- tests/test_slits.py
- tests/test_state.py
- tests/test_valve.py
Update the library for ophyd=1.5.0
The test suite was broken for two main reasons:
- `FakeEpicsSignal` is no longer a usable stand-in for `EpicsSignal` in `EpicsMotor` after the limit-updating patch. Long term I believe this class should be replaced with a true `sim` control layer at `ophyd`.
- `Status` objects are no longer guaranteed to be ready immediately when checked from the same thread that calls `_finished/set_finished/set_exception`... or at least I think that's what's going on. Adding waits fixed it.
Additionally, there was one test that was simply broken and I could not figure out how it originally passed. I adjusted this test appropriately.
The tests are broken, there are new deprecation warnings, and there are new toys.
closes #423 
closes #429 
The tests still pass after my …
> MNT: Ophyd 1.5 Changes

- pcdsdevices/interface.py
- pcdsdevices/utils.py
This is not necessary to actually merge, as we have no _real_ use case for Windows instantiations of pcdsdevices.
However, for typhos testing I wanted to show the same device without copy/pasting it out of the library, and these were the fixes necessary to do so.
Here's what typhos + pcdsdevices on Windows looks like, for those interested:
> FIX: importability on win32

- pcdsdevices/areadetector/detectors.py
- pcdsdevices/areadetector/plugins.py
- pcdsdevices/pim.py
See title
New class heirarchy is:
`PCDSAreaDetectorBase`: Just cam + utility methods
`PCDSAreaDetectorEmbedded`: plugins that are used very very frequently
`PCDSAreaDetector`: all plugins we put on every device
And the embedded version is used as the detector on the PIM, PPM, and XPIM.
See associated issue
closes #421 
In general, having large area detector devices embedded onto motion devices causes degradation of performance, both in `IPython` and in `typhos`. I may even want to reduce this more in the future (to just having cam)
Tests still pass
`typhos` screen loads
Just in docstrings
> ENH: clean up pcds detector and add embedded version

- conda-recipe/meta.yaml
- requirements.txt
- tests/test_sequencer.py
As the title says. The patch is not (at least not anymore) necessary for the tests the pass. Also stuffed a rename of `cf_units` -> `cf-units` in here.
Not really a required change. Just a removal of an obscure vestigial code piece.
Also fixes #318.
Travis build passes.
It hasn't been. This PR should be record enough.
> Remove monkeypatch of EventSequence

- pcdsdevices/absorber.py
- pcdsdevices/sxr_test_absorber.py
Added sxr_test_absorber.py and SxrTestAbsorber class. There are one off components. Although the name is an absorber, its function is a sacrifical stopper for the 1Mhz sxr beam and used when they are ramping up. 
Add the SXR test absorber to pcdsdevices so a gui can appear.
> SXR Test Absorber addition

- tests/test_sequencer.py
I believe this is an upstream bug with bluesky=1.6.2. The easiest resolution for now is to xfail the test so it stops being annoying.
Test passes with bluesky=1.6.1 and fails with bluesky=1.6.2. I'd rather xfail for now and remove xfail once we resolve the upstream bug. This does involve a real issue that breaks scans, so in pcds-envs we'll cap to bluesky=1.6.1 for next release if another bugfix isn't out.
> TST: xfail bluesky bug

- conda-recipe/meta.yaml
- pcdsdevices/utils.py
- pcdsdevices/variety.py
- requirements.txt
- tests/test_variety.py
(Typhos related issue: https://github.com/pcdshub/typhos/issues/332)
This is a first pass at creating a place for more ophyd Device component metadata, which further classify the type of information a signal might hold without requiring a connection to the underlying control system.
Until such metadata is built into ophyd, we plan to have utility functions which add or inspect this additional metadata in `pcdsdevices`. The metadata will be checked with reasonable rigor, such that failures happen sooner (on load) rather than later (on instantiation of your device/screen/etc).
My proposal for the varieties you see in this PR is here, along with the additional metadata keys (anyone at Stanford should be able to comment): https://docs.google.com/spreadsheets/d/1nQQQvR-uqtAohpzqdLGxb8heDeT_sttb …
> ENH: add start of "variety" concept + schema validation

- pcdsdevices/pump.py
This PR adds a subclass of the roughing pump specific for the Ebara EV-A03-1 model of roughing pump. 
The standard roughing pump model neglected a few important PVs. 
Standard tests and style checks succeed. 
A docstring has been added specifically indicating the acceptable pump model No.
> DEV: Add roughing pump subclass specific to the Ebara EV-A03-1

- pcdsdevices/tags.py
- pcdsdevices/variety.py
- tests/test_variety.py
Adds the 'tags' key to all variety metadata schemas.
'tags' is a `set()` of curated string values that classify components.
An example would be that which is presented in this PR: a "protected" signal. If a GUI client sees this tag, it may require a password or mode-dependent (expert vs user) verification before proceeding.
Additional tags will require follow-up PRs, along with single-line explanations as to what the tag means.
Explanations should be written in a way that they can be used consistently from higher-level applications.
`The component: (tag_reason=* May require additional privileges to change.)`
> ENH: add concept of "tags" to variety metadata

- pcdsdevices/pim.py
I added some features to the PLC/IOC and this change to the class reflects the additions.
- LED auto-shutoff after a timeout
- LED auto on/off if we go to the relevant state position
- Ability to lock out zoom/focus motors
Feature requests from the engineers and scientists
I instantiated the XPIM device for IM4L0, called `.get()`, and got a valid readback from every single PV.
> MNT: sync XPIM classes with updated PVs

- pcdsdevices/state.py
Switch spammy twincat config parameters to omitted.
These are definitely configuration parameters, but they are not useful to be seen at all times in the screen since we've allocated a bunch of extra PVs. The intention is for only the states that are relevant to the device should be set to config mode, but I haven't set this up properly yet.
I opened a typhos screen, clicked "hide empty", and was happy with the result.
> MNT: switch spammy components to omitted

- pcdsdevices/epics_motor.py
- pcdsdevices/pim.py
- pcdsdevices/state.py
For LCLS2 imagers and related classes:
- Try out the shiny `variety` schemas on a subset of the component signals
- Fill in the empty `doc` kwargs on many components
- I felt weird poring over `doc=` tags in the new PRs while all of my devices don't have these defined
- Hopefully `doc=` becomes mouse-over help text in a screen somewhere
- Variety will be used in `typhos` at some point, and it will be nice to have some users ahead of that
Tests still pass
This is docs
> DOC: Annotate LCLS2 Imagers and Related Classes

- pcdsdevices/pump.py
- pcdsdevices/valve.py
Add the :ILK_DEVICE* field to the VGC and PIP so it will display in a Typhos screen. This variable tracks the component the VGC or PIP is using to validate its pressure interlocks.
This will allow users to determine which gauges are required for this device to function from the Typhos screen. @slacAWallace 
Standard tests and style checks succeed.
The component docstrings have been updated indicating the goal for this field.
> DOC: Display interlocking vacuum device in Typhos screen for VGC, PIP

- pcdsdevices/epics_motor.py
Link to the motor record's `SPMG` field, which allows you to set the motor to `Stop`, `Pause`, `Move`, or `Go` mode.
This was used in LCLS1 to soft-disable motors at some beamlines by setting them to `Stop` state. I used this yesterday at Bill's request to disable all the motors on the LFE line to prevent MPS issues during accelerator beam dump commissioning.
Now that every LFE motor is in `Stop` mode, it will be useful to have this field on the screen.
I opened up a `typhos` screen with the positioner template and was satisfied.
> ENH: add SPMG for BeckhoffAxis screens

- pcdsdevices/pim.py
- pcdsdevices/tags.py
- pcdsdevices/utils.py
- pcdsdevices/variety.py
- tests/test_variety.py
This PR:
* Pairs with https://github.com/pcdshub/typhos/pull/357
* Adds dotted dictionary support ([example](https://github.com/pcdshub/typhos/blob/91989d836fb76b335900148b80c4f7cc12435fbc/tests/variety_ioc.py#L18-L23))
* Dotted schema dictionaries are automatically expanded prior to schema validation, requiring less nesting on definition.
The vast majority of this PR is the dotted dictionary support, which may well be moved to (e.g.) pcdsutils at some point. The remainder is changes to the schema that are required for https://github.com/pcdshub/typhos/pull/357 and appear to generally be a good thing, based solely on my own use/testing.
> REF: restructure and rework variety metadata: use nested schema, expand dotted dictionaries

- pcdsdevices/epics_motor.py
Switch None-check to TypeError try/except to skip comparison regardless of the failure mode here.
If this subscription fails, the motor will have lots of issues like the `position` property failing to work.
Recently the default value was changed from `None` to `object()` for epics signals. This fixes it so we can bypass an error regardless of why the comparison check fails here.
Works locally in xcs python. Probably passes tests, I did not check.
> MNT: fix issue with failed subscription callback.

- conda-recipe/meta.yaml
- pcdsdevices/utils.py
- requirements.txt
`cf-units` -> `pint`
`cf-units` is not platform-independent because it relies on udunits being installed
`pint` is pure python
Tests still pass
> ENH: swap out cf-units for pint for portability

- pcdsdevices/areadetector/detectors.py
This adds a new class, PCDSAreaDetectorTyphos, for creating areaDetector Typhos screens. This cuts out much of the extra areaDetector plugins and PVs that are not often used, and creates a fairly slim screen for simple AD camera configuration and operation. Includes a pop-up screen for camera viewing. 
Other PCDSAreaDetector classes have a lot of PVs that are not needed most of the time. The other classes also did not allow for viewing the image. 
This
I tested this in the Heinz lab on a Basler camera. 
Not much to document since this is mainly just a pile of PVs. 
See screen shot with the generated screen, compared to the camera viewer. 
I will note one annoyance with this screen right now. When you first open the image viewer, the image is not immediately visible. It appears that the …
> ENH: Add new detector class specifically for creating areaDetector Typhos screens

- pcdsdevices/lasers/qmini.py
I used the write_pv kwarg to combine read and write PVs into one EpicsSignal. This cleans up the screen significantly. I also removed the io_config signals which were pointing to the wrong PVs (oops), and we will likely never use anyway. 
The screen looks more better. 
Tested on a qmini in the Heinz lab.
> STY: Clean up QminiSpectrometer by combining read/write PVs into one signal.

- conda-recipe/meta.yaml
- pcdsdevices/pim.py
Switch from still-too-bulky embedded detector to only-the-things-we-really-need typhos detector on PPM, XPIM.
In cases where we need more, we can instantiate the full device.
In cases where we are setting up all the various motion modes, we care a lot more about having a focused experience than we do about having everything and the kitchen sink.
I opened a screen and I liked it.
> ENH: Update LCLS2 Imagers to use PCDSAreaDetectorTyphos

- conda-recipe/meta.yaml
- pcdsdevices/attenuator.py
- pcdsdevices/inout.py
- pcdsdevices/interface.py
- pcdsdevices/mirror.py
- pcdsdevices/pim.py
- pcdsdevices/rtds_ebd.py
- pcdsdevices/signal.py
- pcdsdevices/slits.py
- pcdsdevices/spectrometer.py
- pcdsdevices/state.py
- pcdsdevices/utils.py
- pcdsdevices/valve.py
The goal is to restore the lightpath interface to working order for all HXR classes.
Lightpath should be able to:
- display status for every pcdsdevices class in use
- display a proper icon for every pcdsdevices class in use
And nothing else is in scope for now since it already does a good job at opening up typhos screens.
There is clamoring for this tool to work again. There is not enough time to do a full rework of lightpath interfaces like I want to do in https://github.com/pcdshub/lightpath/issues/106, instead I will make sure `inserted`, `removed`, `subscribe`, and `transmission` work how lightpath is expecting to properly display status.
I will also need to dig into the attenuator handling logic in lightpath to properly signal when the attenuators are blocking vs not blocking vs …
> MNT: restore lightpath interface

- pcdsdevices/valve.py
The plc requires a rising edge epics open signal in order to open the fast shutter valve. In the past, there was no mention of this and would be confusing to the user.
> MNT: updated doc for FSV open to require rising edge for valve to open.

- pcdsdevices/epics_motor.py
Add support for SmarAct motors.
These are used heavily in the laser control system. Provides an Ophyd object for both encoded and un-encoded stages. 
Tested on motors in the B40 Heinz lab. 
Not much to document. Some docstrings describe the SmarAct open loop PVs.
> ENH: Add Smaract support

- pcdsdevices/lasers/tuttifrutti.py
Adds a module for generating TuttiFrutti classes and instantiating them.
Classes are dynamically created based on the specified diagnostics/devices. In theory there are about factorial(10) combinations of diagnostics/devices, so this seems like the way to go.
A factory function is provided for creating custom TuttiFrutti classes. Another function instantiates the device for you and returns it.
The new laser control system uses TuttiFrutti diagnostic packages all over the place. Each TuttiFrutti is a special snowflake of diagnostics, tailored to the application. The suite of diagnostics used is standardized, and each TuttiFrutti is a single assembly, so it still makes sense to group them. 
Tested using devices in the B40 Heinz lab. Used as components in a forthcoming PR with MODS and TILE …
> ENH: Add support for Tuttifrutti diagnostic stack

- pcdsdevices/attenuator.py
- pcdsdevices/interface.py
- pcdsdevices/state.py
Add the newly added state positioners into the ophyd device for the new hxr fee attenuator.
This PR also contains some backend work on the lightpath interface features that were needed for this device.
Companion to #489 
Needed before we address #495 
The blades move. All PVs connect. The typhos screen looks OK (about as good as a screen with 19 motors and 19 state positioners could look). The lightpath that I'm working on looks good.
> ENH: State positioners for New HXR FEE attenuator

- pcdsdevices/ccm.py
- pcdsdevices/sim.py
- tests/test_ccm.py
Add missing CCM motors (coarse theta, chi)
Fix bad CCM PVs so they all connect for XCS (XPP still has some IOCs down)
Add done flag to the PVPositioner so it will run properly in scans
Update test class to make it useful
Beam time with the CCM soon
Motors were missing
PVs were wrong
Scans need to work
I wanted to verify bluesky scans worked with the energy motor but the test class was non-functional
partially addresses #488 
The tests pass
The logic seems sound
The PVs connect
Test cases:
```
xpp_ccm = CCM(alio_prefix='XPP:MON:MPZ:07A', theta2fine_prefix='XPP:MON:MPZ:08',
theta2coarse_prefix='XPP:MON:PIC:06', chi2_prefix='XPP:MON:PIC:05',
x_down_prefix='XPP:MON:MMS:22', x_up_prefix='XPP:MON:MMS:23',
y_down_prefix='XPP:MON:MMS:24', y_up_north_prefix='XPP:MON:MMS:26', …
```
> ENH: CCM missing motors and TST: Expanded test class

- pcdsdevices/areadetector/detectors.py
Title says it all
People like having the HDF5 plugin apparently
Ran `xcs3` and confirmed an instance of `PCDSAreaDetectorEmbdedded` had the plugin
Added to docstring
> MNT: Add HDF5 plugin to PCDSAreaDetectorEmbdedded

- pcdsdevices/attenuator.py
- pcdsdevices/interface.py
- pcdsdevices/pim.py
- pcdsdevices/sensors.py
Make every PCDS device give a detailed printout of the current status when returned in the IPython terminal. This works by overriding the pretty printing behavior, which is what IPython uses to decide how to represent objects that it returns to the user. The implementation is set up so that you can override the value gatherer and the renderer separately, and so that the default implementation will never throw an exception (it will always show you "something").
This includes only one case of device-specific handling with the attenuators. Positioners and devices with presets also have some special handling in the form of extra data fields.
- Apply the attenuator status to the new hxr attenuator/calculator pair from #495 
- Combine att/3rd harmonic att into one class in a reasonable way (for …
> ENH: IPython status prints

- pcdsdevices/jet.py
IOC had ":SS", class had ":SLIT". Fixed the class to match.
Devices work better when their PVs actually exist.
Ran xcs3, and `ljh` shows as connected now.
Nowhere
> BUG: Fix typo in PV name of BeckhoffJet slits

- pcdsdevices/attenuator.py
Closes #495 
There's a slight issue here as I'm modifying an existing object with an existing happi entry.
Two options that seem obvious to me:
1. Merging/using this will have to wait for a tag as I modified the prefix of the `FEESolidAttenuator` object (was: `ATL0:XTES`, now: `AT2L0`)
2. Or, if needed before a tag, these could become 'UnrelatedComponents' and have two separate prefixes (ignoring the fact that `AT2L0:CALC` and `AT2L0:XTES` do share a base PV)
Opinions?
Screen:
> ENH: include calculator in AT2L0 object

- pcdsdevices/lxe.py
- pcdsdevices/signal.py
- tests/test_signal.py
Adds a new signal class to aid in simple unit conversions.
This is the first part of the upcoming `lxt` motor support.
Though it's preferable to do these at the IOC level so all clients - not just hutch-python/typhos - benefit, it's not always possible.
A simple unit test.
Docstring
> ENH: add UnitConversionDerivedSignal

- .pre-commit-config.yaml
- pcdsdevices/interface.py
Closes #507 
Could use further testing, but in brief poking around the result looks something like:
```
In [22]: class MyDevice(pcdsdevices.interface.BaseInterface, ophyd.Device):
...:     cpt = ophyd.Component(ophyd.EpicsSignal, 'LCLS:HXR:BEAM:EV')
...:
In [23]: dev = MyDevice(name='dev')
In [24]: dev
Out[24]:
dev
---
cpt: 9500 [eV]
```
where `dev.cpt.metadata['units'] == 'eV'`
> ENH: add units to the handy IPython repr

- pcdsdevices/lxe.py
- tests/test_pseudopos.py
Adds "lxt" motor.
* Closes #516 
* Hopefully closes https://github.com/pcdshub/Bug-Reports-and-Requests/issues/27
* Previous PR and PVPositioner made this pretty simple, fortunately!
* Unclear as to whether or not we should implement the `stop` signal here. We know that there's a motor record sitting underneath, but the old code did not touch it (other than using its DMOV flag in a very convoluted way).
* Apologies for the dumb 'lxe' module name. I think this will have to be reorganized, but I don't really know where to put it.
Required from old hutch python config.
Simple unit tests. Also locally with a simple caproto IOC:
```python
mms_ph = SubGroup(FakeMotor, velocity=3., precision=2, prefix=':MMS:PH')
fs_tgt_time = pvproperty(value=0.0, name=':VIT:FS_TGT_TIME')
@fs_tgt_time.putter …
```
> ENH: add LaserTiming PVPositioner

- pcdsdevices/beam_stats.py
- pcdsdevices/ccm.py
- pcdsdevices/pv_positioner.py
- tests/test_ccm.py
Add vernier integration into the CCM class.
This includes a beam requests pv positioner and a vernier with ccm energy motor.
Also adds new positioner base classes whose utility seems to crop up multiple times.
The vernier is something the accelerator crew can use to adjust the beam energy (frequency/color, not intensity).
We manipulate the vernier when it has been agreed upon that we can do so with ACR.
We do this by putting to an energy request PV, then ACR satisfies the request.
We need to move the energy during energy scans that are larger than the SASE bandwidth.
Contributes to #488 
Closes #498
Some unanswered questions:
- Should this really be called the vernier if it is a generic PV that the accelerator chooses how to satisfy?
- Should the vernier move to exactly our energy value? …
> ENH: CCM with Vernier

- docs/pre-release-notes.sh
- docs/source/upcoming_release_notes/531-derived_signal_offset.rst
- docs/source/upcoming_release_notes/532-lxt_hinted.rst
- pcdsdevices/lxe.py
- pcdsdevices/signal.py
- pcdsdevices/utils.py
- tests/test_pseudopos.py
- Add ``user_offset`` to :class:`~pcdsdevices.signal.UnitConversionDerivedSignal`,
allowing for an arbitrary user offset in user-facing units.
- Add ``user_offset`` signal to the :class:`pcdsdevices.lxe.LaserTiming`, by
way of :class:`~pcdsdevices.signal.UnitConversionDerivedSignal`, offset
support.
- Adds hints to the :class:`pcdsdevices.lxe.LaserTiming` class for
``LiveTable`` support.
Tweaks the developer utility script, adding release note files to `git` if the editor reported success.
Closes #531 
Closes #532 
Included unit tests.
Docstrings have been updated.
> ENH/FIX: user offsets for lxt motor and general UnitConversionDerivedSignal

- docs/source/upcoming_release_notes/536-limit-overrides.rst
- pcdsdevices/epics_motor.py
- tests/conftest.py
- tests/test_ccm.py
- tests/test_epics_motor.py
- Provide mechanisms for overriding the epics limits in software without changing them
- Remove all epics gets/puts from limit properties in our `EpicsMotorInterface`
- Use base class's mechanisms for getting epics limits. We had overrided these, but upstream ophyd has fixed this long ago (and handled it better than we were)
https://github.com/pcdshub/pcdsdevices/issues/530#issuecomment-680276993
Added relevant test cases.
Going to write it up right now
> MNT: local limit overrides, rely more on base class after updates

- docs/source/upcoming_release_notes/546-beam-req.rst
- pcdsdevices/beam_stats.py
- pcdsdevices/pv_positioner.py
- tests/test_ccm.py
The beam energy positioner only has a setpoint. The readback I had originally picked was not appropriate for the use case for various reasons. I have resolved this by making a new base class.
closes #546 
Passes old tests
Oops, I'll go write the pre-release docs
> MNT: rework beam energy positioner to be setpoint-only

- pcdsdevices/epics_motor.py
Extend the check to also check `(None, None)` and not just `None`
LXE is not initializing because its newport is initializing to limits `(None, None)`
LXE initializes now
Patches bug that was introduced after to the last tag, so I'll overlook it
> MNT: fix issue with epics setpoint limits being (None, None)

- docs/source/upcoming_release_notes/527-tweak-fixes.rst
- docs/source/upcoming_release_notes/553-umv-fixes.rst
- pcdsdevices/interface.py
- pcdsdevices/sim.py
- pcdsdevices/utils.py
- tests/test_interface.py
- umv displays position at the end of the move
- umv displays complete instead of not complete at the end of the move
- umv and tweak agree on an output format
- tweak doesn't tweak out, it has measured, consistent output
- tweak accepts + and - for increasing or decreasing the scaling
- tweak properly clears lines between prints
- tweak code refactored a bit for cleanliness
closes #553 (umv)
The progress bar / position bar was not guaranteed an update on status completion. This guarantees such an update. Otherwise, you can get stuck with a progress bar that says "move in progress, no real information, blah blah blah"
closes #527 (tweak)
closes #281 (tweak)
Partially addresses https://github.com/pcdshub/Bug-Reports-and-Requests/issues/16 by adding the + and - keystrokes
also closes #481. …
> MNT: Fix umv and tweak issues

- docs/source/upcoming_release_notes/558-slow-ureg.rst
- pcdsdevices/utils.py
Create the `pint.UnitRegistry` at first use only instead of at every conversion call.
The function call is slow, and only needs to be done once.
Contributes to #526, might be related to #550 
Here is the line_profiler output for this method from a software-only motor move:
```
Total time: 6.7158 s
File: /u/lu/zlentz/pydev/pcdsdevices/utils.py
Function: convert_unit at line 91
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
91                                           def convert_unit(value, unit, new_unit):
92                                               """
93                                               One-line unit conversion.
94
95                                               Parameters
96 …
```
> MNT: establish ureg only once, it is a slow process

- docs/source/upcoming_release_notes/557-pseudo-wm.rst
- pcdsdevices/interface.py
- pcdsdevices/lxe.py
`FltMvInterface.wm()` now is aware that float movers could be pseudo positioners that return tuples, and will make sure to return a value from the first element of the tuple if it can.
This bug breaks things like mvr, umvr
closes #557 
Locally...
Added pre-release notes
> MNT: patch wm for pseudo positioner compatibility

- docs/source/upcoming_release_notes/560-tol-lims.rst
- pcdsdevices/beam_stats.py
- pcdsdevices/ccm.py
- pcdsdevices/sim.py
Implement the following fixes as requested by the scientists:
- CCM energy limited to the range of 4 to 25 keV
- CCM theta2fine done moving tolerance raised to 0.01
- beam request default move start tolerance dropped to 5eV
- Fix bug on beam request where you could not override the tolerance via init kwarg (though we will not use this feature here)
- energy limits avoid accidents because the alio has no limits
- theta2fine's tolerance value from old python was wrong
- beam request's move start tolerance from old python was wrong
```
$ happi load xcs_ccm
[2020-08-31 16:11:52] - INFO -  Creating shell with devices ['xcs_ccm']
/reg/neh/home/zlentz/miniconda3/envs/dev/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the …
```
> MNT: various CCM tolerances and limits

- pcdsdevices/interface.py
After a call to any move command, you will be able to call `.wait()` later as a proxy to `status.wait()` for the motor's most recently generated `MoveStatus` object, bypassing the need to keep track of this object yourself.
The weird interactive move shortcuts that were requested of us do not return status objects, so if you don't pass `wait=True` you miss your chance forever. This is used in the "move the whole beamline between pink and mono" script I was asked to write, which heavily leverages the presets system, which doesn't return status objects.
An alternate approach here may have been to add extra presets methods that do return status objects... but this seemed easier to figure out.
Locally
You got me there
> ENH: allow waiting on in-progress moves without caching status object

- docs/source/upcoming_release_notes/565-pp-inout-pvfix.rst
- pcdsdevices/pulsepicker.py
The `PulsePickerInOut` class is meant to grab the first two segments of its PV to use for its in-out motion. At it is currently written, it only grabs the first segment of the PV instead of the first two.
Wanted to implement a `PulsePickerInOut`. It didn't work.
```
In [40]: pp.prefix.split(':')[:1]
Out[40]: ['XCS']
In [41]: pp.prefix.split(':')[:2]
Out[41]: ['XCS', 'SB2']
```
🤷‍♂️
> BUG: Fix pulsepicker so it gets its PV like it says it does

- docs/source/upcoming_release_notes/566-seq-race.rst
- pcdsdevices/sequencer.py
Add a check to make sure that the "done" transitions happen at a timestamp after the last put to `play_control`.
In functions like `trigger`, we return a `SubscriptionStatus` that is to be marked as finished when we transition from state "playing" (2) to state "not playing" (0).
If the python code is running particularly fast (or the network/IOC particularly slow), it can get to the point where it sets up the `SubscriptionStatus` with local function `done`, `run=True` prior to getting an update that the sequencer has started playing (transition from 0 to 2). What happens in this case is that we get a callback with the details from the previous transition, (typically from 2 to 0), and since `run=True` we mark ourselves as `finished` immediately- after all, we just got an update that the …
> MNT: fix done running race condition in EventSequencer class

- docs-requirements.txt
- docs/source/_templates/autosummary/class.rst
- docs/source/conf.py
- docs/source/sample_delivery.rst
(Current master for comparison: https://pcdshub.github.io/pcdsdevices/generated/generated/pcdsdevices.attenuator.AttenuatorCalculator_AT2L0.html)
Attempt 2; I think this looks much better:
Retains the previous method-documenting functionality, but pares it down significantly:
> DOC: ophyd device component helper

- .travis.yml
Doctr deploy is failing on travis-ci due to extreme verbosity.
Limit that here.
> CI: docs deploy fix

- docs/source/upcoming_release_notes/576-tab_completion.rst
- pcdsdevices/interface.py
- tests/test_interface.py
An alternative to holding tab completion state in `BaseInterface`, pulling it out to allow for class or instance-level modification.
If this is deemed acceptable, we can build functionality on top of it for https://github.com/pcdshub/pcdsdevices/issues/576
If not, we can patch in that requested functionality in each subclass.
8d64558 closes #576
> REF: tab completion state in a separate class

- docs/source/upcoming_release_notes/586-wfs.rst
- pcdsdevices/device_types.py
- pcdsdevices/sensors.py
- pcdsdevices/wfs.py
- tests/test_wfs.py
- Add `WaveFrontSensorTarget` class to control the wavefront sensor target
- Add `TwinCATTempSensor` class for `FB_TempSensor` from general lib
- These exist and need to be controlled
- closes #586 
```
In [2]: wfs = WaveFrontSensorTarget('PF1K0:WFS', name='pf1k0')
In [3]: wfs.get()
Out[3]: WaveFrontSensorTargetTuple(target=TwinCATInOutPositionerTuple(state=1, error=0, error_id=0, error_message='', busy=0, done=0, reset_cmd=0, config=TwinCATStateConfigAllTuple(state01=TwinCATStateConfigOneTuple(state_name='OUT', setpoint=-15.0, delta=2.0, velo=5.0, accl=200.0, dccl=25.0, move_ok=1, locked=0, valid=1), state02=TwinCATStateConfigOneTuple(state_name='TARGET1', setpoint=-39.124, delta=2.0, velo=5.0, accl=200.0, dccl=200.0, move_ok=1, locked=0, valid=1), …
```
> ENH: WFS Class

- pcdsdevices/attenuator.py
Closes https://github.com/pcdshub/pcdsdevices/issues/511
To close https://github.com/pcdshub/pcdsdevices/issues/511
Interactively, so far:
```python
In [1]: at2l0.position
Out[1]: 0.09998276656338201
In [2]: at2l0.move(1.0)
Out[2]: MoveStatus(done=True, pos=at2l0, elapsed=0.2, success=True, settle_time=0.0)
In [3]: at2l0.position
Out[3]: 1.0
In [4]: at2l0.mv(0.5)
In [5]: at2l0.position
Out[5]: 0.4997430366337844
In [6]: at2l0(0)
In [7]: at2l0.position
Out[7]: 1.0125629805856235e-78
```
ASCII rendering:
```python
In [1]: at2l0
Out[1]:
filter # |1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|
OUT     |X| | | | | | | | |  |  |  |  |  |  |  |  |  |  |
IN      | |X|X|X|X|X|X|X|X|X |X |X |X |X |X |X |X |X |X |
Transmission (E=9.5 keV): 1.0126E-78
Transmission for 3rd harmonic (E=28.5 keV): …
```
> ENH: move interface for AT2L0

- pcdsdevices/ipm.py
- tests/test_ipm.py
A `target_in` function has been added to the IPMMotion Class
IPM Motion devices can be driven to specific states using the move function - `target_in` is taking as a parameter a "target state" and it is moving the target to that state. 
Trying to close #544
Has only been tested using the `fake_imp` device
N/A
> target_in for IPM

- docs/source/upcoming_release_notes/570-Old_CCM_Energy_Calculation_Reversion.rst
- pcdsdevices/ccm.py
- tests/test_ccm.py
The def `theta_to_alio` and def `alio_to_theta` functions have been reverted to use the `old` calculations.
Trying to close #570
Has only been tested with a `fake_ccm`.
> MNT: revert to old ccm energy calculation

- docs/pre-release-notes.sh
Minor tweaks to the release notes helper script.
* Allows for spaces in the description (`filename ~= s/ /_/g`)
* Auto sets title so you don't forget
> MNT: make doc helper script more user-friendly

- docs/source/upcoming_release_notes/555-Fix_EpicsMotor_limit_clamping.rst
- docs/source/upcoming_release_notes/591-Catch_LimitError.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/interface.py
- tests/test_epics_motor.py
```
- User-facing move functions will not be able to catch the
:class:`~ophyd.utils.LimitError` exception.  These interactive methods are
not meant to be used in scans, as that is the role of bluesky.
- Catch :class:`~ophyd.utils.LimitError` in all
:class:`pcdsdevices.interface.MvInterface` moves, reporting a simple error by
way of the interface module-level logger.
- Allow setting of :class:`~ophyd.EpicsMotor` limits when unset in the motor
record (i.e., ``(0, 0)``) when using
:class:`~pcdsdevices.epics_motor.EpicsMotorInterface`.
```
Closes #555 
Closes #591 
Interactively.
Release notes.
> REF/FIX: Noisy limits and EpicsMotor limit clamping

- docs/source/upcoming_release_notes/614-LAMP_motion_system_class.rst
- pcdsdevices/lamp_motion.py
Added class `lamp_motion.LAMP` which contains motion components for each LAMP stepper motor:
- Gas Jet X/Y/Z (in air)
- Gas Needle X/Y/Z (in air)
- Sample Paddle X/Y/Z (in vacuum)
This class is required for a Python interface to the LAMP motion system.
- Ran test suite locally (no failed tests)
- Instantiated object in Ipython section/inspected components
- Opened test typhos screen
- Docstring for `lamp_motion.LAMP`
> ENH: Include LAMP motion class

- .github/PULL_REQUEST_TEMPLATE.md
I've noticed that the PR template isn't clear enough about documentation nor complete enough to avoid "do the thing" kinds of reviews. I've updated it accordingly, including some minor re-ordering.
> DOC: improve pre-merge checklist

- docs/source/upcoming_release_notes/620-ref-pico.rst
- pcdsdevices/ref.py
Switch the class from `PCDSMotorBase` to `EpicsMotorInterface` because these use the community motor record, unmodified.
`PCDSMotorBase` changes some PVs around, and this breaks the device.
My `typhos` screen is pretty snazzy and responsive. All the PVs connect.
I made a pre-release docs page
> MNT: fix pico motors on l2si ref laser

- docs/source/upcoming_release_notes/619-New_Lcls_object_to_query_machine_status.rst
- pcdsdevices/beam_stats.py
- pcdsdevices/device_types.py
- tests/test_beam_stats.py
A new Lcls class has been added to the `beam_stats` module.
- The Lcls class will be used to query machine status. 
- The `SxrGmd` has been removed from this module because the SXR has been disassembled and the GMD was moved into the EBD, the mj PV was not working anymore.
- This class will have to be revised, because as of now there are probably way too many PVs and we might not care for some of them. 
It is supposed to close https://github.com/pcdshub/Bug-Reports-and-Requests/issues/33
A few tests have been added to test the functionality of the new methods. 
Locally only
> ENH: New lcls object to query machine status

- docs/source/upcoming_release_notes/625-SmarAct-open-loop-scanning.rst
- pcdsdevices/epics_motor.py
Adds a new class, SmarActOpenLoopPositioner for doing open loop motor scanning with SmarAct stages. 
This allows us to scan SmarAct stages that are open loop, such as tip-tilt stages. This will be used for doing laser beam pointing/centering. 
Closes #625 
Tested on a stage in the Heinz lab. 
The code and docstrings.
> ENH: Smaract Open Loop Scanning

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/627-Typhos-cam-viewer.rst
- pcdsdevices/areadetector/detectors.py
- requirements.txt
I added a method to PCDSAreaDetectorTyphos to launch the camera viewer for that camera.  This method is available on Typhos screens via a button. 
The camera viewer is pretty fully featured, and the LCLS staff are used to it. It would be nice to have this easily accessible from automatically generated Typhos screens. 
Closes #627.
Tested on a camera in the Heinz lab. This method uses the get_hutch_name script from engineering_tools, which in its latest release does not include the las or hpl subnets. There is a PR in the rectify this, and will be fixed with the next release of engineering tools. The code still works, though on the las/hpl subnets the viewer is instantiated as 'unknown_hutch' for the --instrument flag. This is fine for now, and will be fixed on the next release of …
> ENH: Add camera viewer to PCDSAreaDetectorTyphos

- docs/source/upcoming_release_notes/641-SmarAct-Tip-Tilt.rst
- pcdsdevices/epics_motor.py
Adds a new class, bundling two open-loop SmarAct classes together. 
The laser system uses tip-tilt mirrors all over the place. This helps create bundled typhos screens for these axes, reducing clutter. 
Closes #641 
Tested on a tip-tilt stage in B40. 
I wrote a docstring for the class that seems fairly comprehensive.
> ENH: Add SmarActTipTilt class for mirror control.

- docs/source/upcoming_release_notes/637-vgs_2s.rst
- pcdsdevices/valve.py
A new ophyd class for the vacuum lib VGC_2S, that extends the VGC with the addition of a second setpoint and hysteresis.
TMO requires to interlock beam line valves with 2 different setpoints instead of 1.
> New VGS with two different setpoints per gauge needed for TMO

- docs/source/upcoming_release_notes/645-elliptec-stop-fix.rst
- pcdsdevices/lasers/elliptec.py
Changed the 'stop' signal to 'stop_optimize' in the elliptec module.
This resolves a conflict with the BlueSky interface. 
Closes #645 
Tested interactively using a stage in the Heinz lab. 
The code.
> MNT: Elliptec 'stop' signal conflict

- docs/source/upcoming_release_notes/647-import_lasers.rst
- pcdsdevices/device_types.py
- pcdsdevices/lasers/__init__.py
* Add laser imports to `pcdsdevices.device_types`
* `test_interfaces` will now pick up laser classes and check their tab completion settings
It may be worthwhile to do an alternative PR to this, moving laser classes to the top level. I think we at least discussed that possibility or we may have had an issue on that at some point?
Related to #647 , but does not close it.
Locally, noting that laser devices are imported and run through `test_interfaces`.
Release notes
> FIX: import laser devices; implicitly test interface through find_all_device_classes

- docs/source/upcoming_release_notes/661-Ophyd_utility_thread_scheduling.rst
- pcdsdevices/utils.py
Ensure that we only try to add put into the queue if `event_thread` is not None.
Closes #661 
Locally and at psbuild using PYTHONPATH pointing to my fix branch.
N/A
> FIX: Check if context.event_thread is not None.

- docs/source/upcoming_release_notes/692-pump_PTMPLC_ILK_status_pv_fix.rst
- pcdsdevices/pump.py
Changes in the pump.py to the PTMPLC interlock_status pv from ILK_STATUS_RBV to ILK_OK_RBV.
The pv was wrong causing 'no connection' error on the typhos screen.
Yes, it has been tested from my local repo.
With pv AT1K0:GAS:PTM:10
ptm.get()
PTMPLCTuple(switch_pump_on=1, reset_fault=0, run_do=1, pump_at_speed=1, pump_accelerating=0, pump_speed=542, fault=0, warn=0, alarm=0, bp_sp=0.800000011920929, ip_sp=0.019999999552965164, interlock_status=1)
Not yet.
> FIX: PTMPLC wrong interlock pv causing no connection

- docs/source/upcoming_release_notes/672-Custom_Status_Prints_for_Slits.rst
- pcdsdevices/slits.py
- pcdsdevices/utils.py
- tests/test_utils.py
Override the status info handler for `Slits`. 
Trying to implement and close #672 
```
In [2]: l = LusiSlits(prefix='XCS:SB2:US:JAWS', name='s2')
In [3]: l
Out[3]:
Slit: XCS:SB2:US:JAWS
(hg, vg): (+9.9997, +9.9995) [mm]
(ho, vo): (+0.0912, -0.1137) [mm]
```
> ENH: Slits custom status

- docs/source/upcoming_release_notes/670-Custom_Motor_Status_Print.rst
- pcdsdevices/epics_motor.py
- Added a custom status print for motors by overriding the status info handler.
- Added a new component for `dial_position`
- Added a new method `check_limit_switches` to check for the limit switches.
Trying to implement and close #670 
```
In [2]: ipm = Motor(prefix='XPP:SB2:MMS:03', name='name')
In [3]: ipm
Out[3]:
IPM2 Target Y: XPP:SB2:MMS:03
Current position (user, dial): 0.0, -0.0 [mm]
User limits (low, high): -200.0, 200.0 [mm]
Preset position: Unknown
Limit Switch: Low [] High []
```
Docstring
> ENH: custom motor status print

- docs/source/upcoming_release_notes/674-PIM_Custom_Status_Print.rst
- pcdsdevices/pim.py
Override the status info handler for pim.
Trying to implement and close #674 
Not sure if I'm testing this correctly:
```
In [3]: pim_f = PIMWithFocus(prefix='CXI:DG1:PIM', name='yag')
In [4]: pim = PIM(prefix='CXI:DG1:PIM', name='yag')
In [5]: pim_f
Out[5]:
CXI DG1 PIM: OUT
Y Position: -51.9995 [mm]
Navitar Zoom: 0.6180 [%]  Focus: ERROR [None]
In [6]: pim
Out[6]:
CXI DG1 PIM: OUT
Y Position: -51.9995 [mm]
Navitar Zoom: 0.6180 [%]
```
Docstring
> ENH: PIM custom status

- docs/source/upcoming_release_notes/703-pp-err.rst
- pcdsdevices/interface.py
Wrap the pretty-print handler to cover unknown exceptions from custom status prints.
Simply viewing the status of an object shouldn't break everything- we should see some information and be made aware that something has gone wrong.
In the qs loader this was causing large issues.
Interactively
```
In [2]: bad = IMS('BAD', name='bad')
In [3]: bad
Out[3]: IMS(BAD, name=bad): Error showing status information. Check IOC connection and device health.
```
The debug message looks like:
```
DEBUG:pcdsdevices.interface:IMS(BAD, name=bad): Error showing status information. Check IOC connection and device health.
File "/u1/zlentz/miniconda3/envs/dev/lib/python3.6/site-packages/ophyd/signal.py", line 1078, in _get_with_timeout …
```
> MNT: wrap all status formatting in an error handler.

- docs/source/upcoming_release_notes/693-rix-optics-classes.rst
- pcdsdevices/mirror.py
- pcdsdevices/spectrometer.py
- Renamed `mirror.XOffsetMirror2` to `mirror.XOffsetMirrorBend` for clarity
- Added `mirror.XOffsetMirrorSwitch` for control of device MR1K2-SWITCH
- This is nearly identical to `mirror.XOffsetMirror`, but with vertical axis PVs `MMS:YLEFT`/`MMS:YRIGHT` instead of `MMS:YUP`/`MMS:YDWN`
- These changes are not ideal. It would be best to change the PVs of all mirror gantry axes to be Y1/Y2 for master/slave, allowing for the same parent class of all systems. This requires changes to each system in `lcls-plc-lfe-optics`, `lcls-plc-tmo-optics`, `lcls-plc-txi-optics`, and `lcls-plc-rixs-optics`, lots of work
- As a first step, it would be ideal to refactor parent class `mirror.XOffsetMirror` so that child classes do not need to set unused components to `None`.
- Python control of RIX optics …
> ENH: RIX Optics Classes

- docs/source/upcoming_release_notes/675-Add_3rd_Harmonic_Status_Print.rst
- pcdsdevices/attenuator.py
- tests/conftest.py
- tests/test_attenuator.py
Refactored the code a bit to allow creating devices with both fundamental frequency and 3rd harmonic frequency instead of creating separated classes for them as it was previously.
Add custom status printout for the Attenuator by overriding the `format_status_info` handler.
Trying to implement #675
```
In [1]: mfx_attenuator
Out[1]:
filter # |0|1|2|3|4|5|6|7|8|9|
OUT     | |X| | | |X|X|X|X|X|
IN      |X| |X|X|X| | | | | |
Transmission for 1st harmonic (E=8.23e+06 keV): 2.3446E-02
Transmission for 3rd harmonic (E=2.47e+07 keV): 2.3446E-02
```
```
In [1]: at1l0
Out[1]:
filter # |0|1|2|3|4|5|6|7|8|
OUT     |X|X|X|X|X|X|X|X|X|
IN      | | | | | | | | | |
Transmission for 1st harmonic (E=8.23e+06 keV): 1.0000E+00
```
> ENH: attenuator 3rd harmonic print

- docs/source/upcoming_release_notes/695-Epics-Motor-Metadata.rst
- pcdsdevices/epics_motor.py
Adds some metadata and updates kind for some motor record fields. Small update to SmarActOpenLoop to clean up the open loop position control because I couldn't resist. 
Closes #695, more details there. 
Tested on a stage in TMO. 
Just the code.
> STY: Epics_motor metadata

- docs/source/upcoming_release_notes/718-Add_get_status_float_function_in_utils.rst
- pcdsdevices/utils.py
- tests/test_utils.py
Added a new function in `utils`: `get_status_float` that is very similar to the existing one `get_status_value` except that this one is formatting the value with the precision that was requested by the user. 
I keep having to format multiple numbers with similar precision of 4 when overriding the `format_status_info`
```
{value:.4f}
```
So this will make it simpler and has an additional check before formatting the value to make sure the value is a float in the first place.
Unit test.
Docstring
> MNT: add get_status_float function

- docs/source/upcoming_release_notes/issue_number-add_ExitSlits.rst
- pcdsdevices/slits.py
New class added to slits.py for the exit slits.
New class added to slits.py for the exit slits. The class contains all the motion pvs, RTDs, Camera and CIL pvs required for the exit slits.
This has been tested from my local directory.
> ENH: Included Exit slits class

- docs/source/upcoming_release_notes/issue_number-LED_power_add_to_Mono.rst
- pcdsdevices/spectrometer.py
Three LED controls have been added to the Mono
Three LED controls have been added to the Mono. They can be controlled on/ off.
Yes, this have been tested from my local directory
> ENH: add LED controls to the Mono

- docs/source/upcoming_release_notes/issue_number-update_ExitSlits.rst
- pcdsdevices/slits.py
Included meta data to the SL1K2-Exit Led control
Included meta data to the SL1K2-Exit Led control
The LED has an analog control, with the meta data the user can control the output via a slide bar.
This has been tested from my local directory
> ENH: Metadata for the SL1K2-Exit LED control - slider widget

- docs/source/upcoming_release_notes/682-Gon_Custom_Status_Print.rst
- pcdsdevices/gon.py
This PR might need some more attention, because as of now I have added a custom status for two different classes: `BaseGon`, and `XYZStage` class. 
Trying to tackle and close https://github.com/pcdshub/pcdsdevices/issues/682#issuecomment-733998450
```
In [1]: xpp_gon
Out[1]:
XPP Goniometer
H, V: 588.6461, 50.4013 [mm]
Theta, Pitch, Roll: -0.0468, 0.0400, 0.0282 [deg]
```
XYZStage:
```
In [5]: s
Out[5]:
XYZStage
X, Y, Z: 8.6988, -12.7856, 0.4693 [mm]
```
> ENH: Gon custom status

- docs-requirements.txt
- docs/source/upcoming_release_notes/720-add_ExitSlits.rst
- docs/source/upcoming_release_notes/721-LED_power_add_to_Mono.rst
- docs/source/upcoming_release_notes/723-update_ExitSlits.rst
- Bump Sphinx requirement to the one I built correctly with locally
- Add missing title information from exit slit pre-release docs
I noticed that the pre-release docs page is empty:
https://pcdshub.github.io/pcdsdevices/v3.3.0/upcoming_changes.html
So I tried to figure out why this could be. These are the only two anomalies I noticed.
My local docs build correctly with this change.
Locally
This is docs
> DOC: Pre-release docs page fix

- docs/source/upcoming_release_notes/725-AvgSignal-Spam.rst
- pcdsdevices/signal.py
The logic in `AvgSignal` (used for gas detector) includes a `wait_for_connection` in a background thread that can time out in many cases with a large traceback.
This pull request replaces that instance with a straightforward `subscribe` call that does not time out, it just sits there and waits for the PV to be connected.
I'm working though a `hutch-python` unit testing bug right now and these tracebacks are annoying.
```
Exception in thread Thread-16:
File "/u1/zlentz/miniconda3/envs/dev/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/u1/zlentz/miniconda3/envs/dev/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/u1/zlentz/miniconda3/envs/dev/lib/python3.6/site-packages/pcdsdevices/ …
```
> MNT: clean up average signal to avoid timeout messages

- docs/source/upcoming_release_notes/739-add_upper_limit_threshold_to_vcn.rst
- docs/source/upcoming_release_notes/issue_number-add_upper_limit_threshold_to_vcn.rst
- pcdsdevices/valve.py
The upper limit of the VCN ( how much the VCN can open) can now be set from epics. This adds another way to safely operate the vcn.
The VCN can be set to fully open, which can lead to vacuum events. Now, the Upper limit can be set from epics to prevent the operator from fully opening the VCN unintentionally.
> Vcn limit 

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/736-sxr_solid_attenuators.rst
- pcdsdevices/attenuator.py
- pcdsdevices/interface.py
- pcdsdevices/utils.py
- requirements.txt
- tests/test_attenuator.py
Preliminary working AT1K4 support (and other 4-blade, <= 8 filter L2SI attenuators).
Closes #736 
Closes #732 (semi-related as prettytable is used here)
Naming was OK'd before making this ready to review, though we all agree that `SXR_` is a bit unsightly.
* Interactive testing. 
* Test suite
Docstrings.
Table and status joining utilities:
Previous ascii art table sadly wasn't enough when you have a bunch of filters per blade. Added new one:
And WIP typhos screen:
IOC support: https://github.com/pcdshub/solid-attenuator/
Screens: https://github.com/pcdshub/typhos/pull/416
> ENH: add support for AT1K4 and some status table utilities

- docs/source/upcoming_release_notes/734-twincat-homing.rst
- pcdsdevices/epics_motor.py
For the TwinCAT motor homing, an alternate PV is used to work around an issue with the motor record driver. This mirrors the IOC change.
Phil wants to home some motors today in like 10 minutes
PVs connected in LFE; more testing later
N/A
> MNT: switch twincat motors to alternate homing PV

- docs/source/upcoming_release_notes/744-cvmi-motion-class.rst
- pcdsdevices/cvmi_motion.py
Added two motion classes: `cvmi_motion.CVMI` and `cvmi_motion.KTOF` including components for the fixed Beckhoff axes of these TMO-IP1 motion systems.
We need motion control of the CVMI/KTOF endstation systems in order to perform Epics checkouts. The current CVMI/KTOF classes are simply a copy/paste of the LAMP class with updated in order to complete the CVMI/KTOF checkouts without modifying the LAMP system. Eventually, it seems worthwhile to restructure the TMO motion classes into a single file `tmo_ip1_motion.py` with `class IP1Base` including the Gas Jet/Gas Needle axis components that `class LAMP` and `class CVMI` could inherit from.
Local testing from psbuild-rhel7-01 using:
```
$ export PYTHONPATH=`pwd`:$PYTHONPATH
$ typhos 'pcdsdevices.cvmi_motion.CVMI[{"prefix":"TMO:CVMI"}]'
$ …
```
> ENH: CVMI and KTOF class, LAMP docstring fix

- docs/source/upcoming_release_notes/742-Fix_3rd_Att_Transmission_Status.rst
- pcdsdevices/attenuator.py
Have corrected the transmission status for the 3rd harmonic by reading this value from the `readback_3rd` which is the signal for `:COM:R3_CUR` this PV - based on a little bit of research this seems the appropriate PV to use for the transmission of the 3rd harmonic. Please see the discussion here: https://github.com/pcdshub/pcdsdevices/issues/675#issuecomment-755131529
Fix the status information for the 3rd harmonic transmission value.
```
happi load mfx_attenuator
In [1]: mfx_attenuator
Out[1]:
filter # |0|1|2|3|4|5|6|7|8|9|
OUT     |X|X| | | |X|X|X|X|X|
IN      | | |X|X|X| | | | | |
Transmission for 1st harmonic (E=13.000 keV): 4.0911E-01
Transmission for 3rd harmonic (E=39.000 keV): 9.2504E-01
```
```
happi load at1l0
In [1]: at1l0
Out[1]:
filter # |0|1|2|3|4|5|6|7|8|
OUT …
```
> Fix 3rd att transmission status

- docs/source/upcoming_release_notes/747-find_all_submodules_in_tests.rst
- tests/conftest.py
Use Python standard library tools to walk every possible submodule in pcdsdevices for the purposes of finding every ophyd device.
* The current `master` branch will skip an arbitrary-depth submodule that is not included by `device_types` such as `.submodule.subsubmodule.subsubsubmodule.NewDevice` whereas this PR will include it. 
* We intend to restructure the package devices significantly. 
* Missing any device - no matter how the package is restructured - in these sweeping tests would be unacceptable.
Ran the test suite and compared it to the old output.
The number of tests has not changed as master branch test fixtures are sufficient for the devices currently in pcdsdevices.
Changelog
> TST/FIX: find all device classes in all submodules

- docs/source/upcoming_release_notes/happi-names-753.rst
- pcdsdevices/happi/containers.py
Companion to https://github.com/pcdshub/happi/pull/211
Pulling in our name restriction to pcdsdevices
See https://github.com/pcdshub/happi/issues/206
> MNT: bring site-specific happi name restriction to site-specific class

- docs/source/upcoming_release_notes/757-att-enum.rst
- pcdsdevices/attenuator.py
- tests/test_attenuator.py
bluesky expects all items to be clearly typed, this makes this item clearly typed.
closes #757
see #757
> MNT: Enum is not a valid read type, IntEnum is

- docs/source/upcoming_release_notes/762-kappa-fix.rst
- pcdsdevices/gon.py
- tests/test_gon.py
- Fix issue where position check used the e motors instead of the k motors
- Fix issue where misplaced minus sign was breaking certain calculations
- Some minor cleanup (do all move checking in check_move, test for None more succinctly, etc.)
- Extend the move table to help me test
- Edit the fake Kappa class to help me test
closes #761 
Before:
```
In [4]: sim.e_chi.move(10)
Do you really intend to do the following motions?
+-------+------------------+-----+------------------------+
| Motor | Current position |  to |    Target position     |
+-------+------------------+-----+------------------------+
|  eta  |        0         | --> |  -4.2099681189703455   |
| kappa |        0         | --> |   13.065802839493314   |
|  phi  |        0         | --> |  -4.2099681189703455   |
| e_eta | …
```
> MNT: Fix Kappa Things

- docs/source/upcoming_release_notes/764-kappa-180.rst
- pcdsdevices/gon.py
- tests/test_gon.py
- If kappa is currently > 180 deg, do the calculation differently
- Code copied/adapted from @dlzhu
- Basically a phase shift
- Add regression tests for this range
- Simplify the calculations a bit
- The original calculations aren't quite correct for large kappa angles, because it makes the eta rotate in the positive direction and collide with the test setup
- In normal operation, the kappa will be set to the correct operating range prior to being used scientifically, so it is sufficient to do the current position check
Added regression tests
Added pre-release documentation
> MNT: alternate calc mode for large kappa angle from Diling

- docs/source/upcoming_release_notes/749-GHC.rst
- pcdsdevices/gauge.py
the GCCPLC class was copied and the word cold was switched out for hot.
Currently the Hot cathodes does not have an expert screen. The stop gap measure was the use a cold cathode expert screen
Yes, the screenshot shows that the expert screen has been tested . Flake8 has already been checked.
There is a comment under the GHCPLC class
> DEV: added GHCPLC class.

- docs/source/upcoming_release_notes/775-sync-refactor.rst
- pcdsdevices/ccm.py
- pcdsdevices/epics_motor.py
- pcdsdevices/interface.py
- pcdsdevices/lxe.py
- pcdsdevices/pseudopos.py
- pcdsdevices/sim.py
- tests/test_pseudopos.py
This PR handles many of the requests for `lxt_ttc` by expanding the sync motor handling. To go through them one by one:
- Fix issues where `lxt_ttc` could have inconsistent offset behavior by allowing the `SyncAxis` to define static offsets (which is going to be the default). Since I'm changing a default, I've decided to deprecate the previous `SyncAxesBase`. (closes #770)
- Add `set_current_position` to all pcdsdevices `PseudoPositioner`s (closes #772)
- Add a warning when any `SyncAxis` subclass has motor positions that do not match each other properly, and provide a method (`fix_sync`) to re-synchronize them (closes #776) 
- Provide an example of a clean way to implement `lxt_ttc` per instrument so that the scientists can reconfigure it as needed (closes #777)
- Add direction inversion …
> ENH: Sync features for lxt_ttc

- docs/source/upcoming_release_notes/791-LaserTiming-hack.rst
- pcdsdevices/lxe.py
- tests/test_lxe.py
Sleep a second whenever we move LaserTiming
Things are bad, this works in prod, I have heard no complaints, and I have other things I'd prefer to work on.
> HACK: include janky LaserTiming fix from xpp/xcs live deployment

- docs/source/upcoming_release_notes/790-delaysync-pp.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/interface.py
- pcdsdevices/pseudopos.py
Add custom status info for DelayBase and SyncAxis, so you'll see these on all delay motors and on lxt_ttc.
SyncAxis includes all the real motor positions:
```
In [5]: fake_lxt_ttc
Out[5]:
SyncAxis: fake_lxt_ttc
lxt position: 1e-06 [N/A]
txt position: -1e-06 [N/A]
Sync position: 1e-06
Sync limits (low, high): (-1e-05, 1e-05)
```
DelayBase is a copy of the pseudosingle delay positioner:
```
In [16]: delay
Out[16]:
Virtual Motor XPP:LAS:MMN:12:delay
Current position (user, dial): 0.000e+00, 0.000e+00 [None]
User limits (low, high): 0, 0 [None]
Preset position: Unknown
In [17]: delay.delay
Out[17]:
Virtual Motor XPP:LAS:MMN:12:delay
Current position (user, dial): 0.000e+00, 0.000e+00 [None]
User limits (low, high): 0, 0 [None]
Preset position: Unknown
```
closes #790 
Interactively …
> ENH: custom status info for DelayBase and SyncAxis

- docs/source/upcoming_release_notes/793-config-soft-limits.rst
- pcdsdevices/epics_motor.py
Set the soft limit kinds to config
We'd like to see these in typhos
closes #793
Opened a screen
> MNT: set epics motor soft limit kinds to config for typhos

- docs/source/upcoming_release_notes/767-fix_ucds_unit_md_callback.rst
- pcdsdevices/signal.py
- tests/test_signal.py
Metadata callbacks did not include appropriate units for UnitConversionDerivedSignal.
Closes #767 
Also ensures that `units` will be included, even if the original signal did not include them in metadata callbacks.
This is, in fact, a bug in upstream ophyd's `FakeEpicsSignal`.
Consider this a pre-requisite to upstreaming the signal class to ophyd.
See new-and-improved test suite.
Pre-release docs incoming
> FIX: pass through derived 'units' in SUB_META callbacks

- docs/source/upcoming_release_notes/issue-add_coating_states_to_XOffsetMirrorState.rst
- pcdsdevices/mirror.py
Implementation of Coating State mover for the MR1L0 and MR2L0 mirrors
Since this hasn't been implemented yet to all offset mirrors additional classes have been added to e used by those two mirrors.
Implementation of Coating State mover for the MR1L0 and MR2L0 mirrors
This has been tested on my local environment
> Coating state

- pcdsdevices/valve.py
Adding a normally open class for VRC gate valves to valve module.
VRCNO exists in the vacuum library on the PLC but was not built out yet in the ophyd pcdsdevices module, Valve.py.
LAMP:ROUGH:VRC:02 is normally open, and the vacuum pydm screen would ideally reflect that.
I tested my new version of valve.py using flake8 and pytest. No violations were reported.
The new class is documented in the class docstring. Additional documentation can be found in the lcls-plc-lamp-vacuum library under ST_VRC_NO.
> Added VRC_NO class to valve module

- docs/source/upcoming_release_notes/805-set-position-bug.rst
- pcdsdevices/__init__.py
- pcdsdevices/epics_motor.py
- Fix an issue where calling ``set_current_position`` on certain motors would cause the ipython session to freeze, leaving the motor in the ``set`` state instead of bringing it back to the ``use`` state.
- Hacky workaround for IMS motor part number strings being unable to be read through pyepics when they contain invalid utf-8 characters. (Is there a better way to do this? Perhaps by picking a different character set for the pyepics string interpretation? There's something I half remember about this)
closes #805 
Locally on `XPP:USR:PRT:MMS:25`
pre-release notes
> MNT: fix set position bug

- docs/source/upcoming_release_notes/812-mirror-states.rst
- pcdsdevices/mirror.py
Twincat mirror coating doesn't have the default in/out states, it has only in states and these are at varying materials.
closes #812 
Interactively:
```
$ happi load mr1l0_homs
[2021-04-06 09:36:35] - INFO -  Creating shell with devices ['mr1l0_homs']
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: mr1l0_homs.coating.position
Out[2]: 'B4C'
In [3]: mr1l0_homs.coating.out_states
Out[3]: []
In [4]: mr1l0_homs.coating.inserted
Out[4]: True
In [5]: mr1l0_homs.coating.states_list
Out[5]: ['Unknown', 'B4C', 'B4C_Ni']
```
oops, forgot to do the pre-release notes, will revisit in a moment
> MNT: fix states on mirror coating

- docs/source/upcoming_release_notes/814-rtdsk0-mpas.rst
- pcdsdevices/rtds_ebd.py
Remove the 2 unused actuators from RTDSK0 so their "INVALID" state has no bearing on the lightpath.
Setting up KFE lightpath today and we're going for accuracy.
Interactively
I will add pre-release notes
> MNT: RTDSK0 is just 2 actuators for now (4 channels total)

- docs/source/upcoming_release_notes/811-Slit_interface_changes_and_precision_in_status_printout.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/slits.py
- tests/test_slits.py
These are two simple changes requested by scientists in XPP/XCS that have been living in a dev checkout for a little while now. Thought it might be a good time to PR them.
First is slit interface changes. Primarily, this change allows users to do things like `s3(4,5)` and adds the aliases, `vo, vg, ho, hg`, for access to the components.
The other thing is specification of precision for the values used in motor status printouts. For now, I've hardcoded a precision of 3 decimal places, but am definitely open to other suggestions. There's probably a good way to use PREC or smth, right?
It would also be nice if we could update precision globally within an hutch-python session. `%precision` doesn't seem to be work for these printouts but might be worth further investigation.
Scientists like …
> ENH: Slit interface changes and precision in status printout

- docs/source/upcoming_release_notes/817-more-lightpath.rst
- pcdsdevices/spectrometer.py
- pcdsdevices/stopper.py
- pcdsdevices/valve.py
- Drop in some "I'm always in, I never block the beam" constants to the mono spectrometer class so it behaves nice and simply inside lightpath.
- Move stoppers to stopper.py so I can find them later
- Add PPSStopperL2SI class for the new stoppers
- The mono device was asked to be in the lightpath, but currently gives errors and doesn't display status.
- I always forget to look in the valve.py file for stoppers
- The new stoppers were asked to be in the lightpath, but the existing classes were not quite suitable.
Interactively
Added docstrings and pre-release notes.
> ENH: 2.2 spectrometer and stopper updates for lightpath

- docs/source/upcoming_release_notes/722-add_confirm_tag.rst
- pcdsdevices/epics_motor.py
Implements my suggestion of the "confirm" tag for homing commands.
Closes #722
Interactively, once, with a simulation motor. See screenshot.
If acceptable, pre-release docs will follow.
> MNT: add 'confirm' tag to home commands

- docs/source/upcoming_release_notes/819-objcpt-cls.rst
- pcdsdevices/device.py
In `ObjectComponent`, instead of just passing `object` as the `cls`, pass the class of the object we're using.
Some classes like `PseudoPositioner` check the `cls` fields of their components as part of the initialization process. This aims to make the `cls` field for an `ObjectComponent` more similar to a normal component.
Interactively in xpp's beamline file
will add pre-release docs
> MNT: pass the object's class to the cpt init so pseudopos work correctly

- docs/source/upcoming_release_notes/822-sim-kind.rst
- pcdsdevices/sim.py
Make the simulated motor utilities hinted by default 
This allows them to show up in the bec LiveTable and LivePlot when instantiated standalone
Interactively
> ENH: make sim devices hinted for bec

- docs/source/upcoming_release_notes/827-add_at2k2.rst
- pcdsdevices/attenuator.py
Closes #827 
A simple addition to add the SXR solid attenuator, AT2K2.
The base class has been tested using AT1K4; this is merely an alias.
Release notes.
> ENH: add AT2K2

- docs/source/upcoming_release_notes/mirror-offsets-829.rst
- pcdsdevices/atm.py
- pcdsdevices/attenuator.py
- pcdsdevices/device.py
- pcdsdevices/epics_motor.py
- pcdsdevices/lic.py
- pcdsdevices/mirror.py
- pcdsdevices/pim.py
- pcdsdevices/slits.py
- pcdsdevices/spectrometer.py
- pcdsdevices/sxr_test_absorber.py
- pcdsdevices/wfs.py
- tests/test_device.py
- Add `UpdateComponent`, a `Component` subclass that allows you to inherit and update a super class's components.
- Add `BeckhoffAxisNoOffset`, a variation on `BeckhoffAxis` that uses `UpdateComponent` to set the user offset related signals to read-only.
- Apply `BeckhoffAxisNoOffset` to all static beamline motors.
For the beamline Beckhoff axes, we don't want to be changing their directions or offsets accidentally. In fact these should always always always be 0/POS in 99% of cases, and some other static value in the other 1% of cases. An easy/clean way to handle this is to prevent the Python from writing to them by making them `EpicsSignalRO`. This has to be specifically targeted at specific instances, both for backcompat and for the end stations that do want to make use of the …
> ENH: UpdateComponent, lock down mirror offsets and others

- docs/source/upcoming_release_notes/834-slit-dmov.rst
- pcdsdevices/slits.py
- tests/conftest.py
- tests/test_slits.py
Clean up the slit done moving handling so that we aren't doing any cagets inside of callbacks.
Error spam in various hutch python sessions, reported in https://jira.slac.stanford.edu/browse/LCLSECSD-105
```
[2021-06-01 22:16:25,494] [ERROR ] - Subscription value callback exception (PytmcSignalRO(read_pv='SL1K4:SCATTER:TOP:DMOV_RBV', name='sl1k4_done_top', parent='sl1k4', value=1, timestamp=1621913588.808209, auto_monitor=False, string=False))
File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/signal.py", line 1113, in _get_with_timeout
self.wait_for_connection(timeout=connection_timeout)
File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/signal.py", line 1067, in wait_for_connection
self._ensure_connected(self._read_pv, timeout=timeout)
File …
```
> MNT: Slit dmov cleanup

- docs/source/upcoming_release_notes/835-st1k2-pps.rst
- pcdsdevices/stopper.py
Convert `PPSStopperL2SI` into `PPSStopper2PV`: a generalized form to support PPS stoppers with two separate PVs that must be checked to determine the PPS state, to support the reality where PPS stoppers have no fixed pattern in their EPICS interfaces.
ST1K2 does not fit the existing PPS stopper PV patterns in any way.
closes #835 
Check to make sure an existing stopper still works with default arguments:
```
$ happi load st3k4_pps
[2021-06-03 10:18:52] - INFO -  Creating shell with devices ['st3k4_pps']
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: st3k4_pps.get()
Out[1]: PPSStopper2PVTuple(in_signal=1, out_signal=0)
``` …
> ENH: PPSStopper2PV

- docs/source/upcoming_release_notes/839-mrco_motion_axis_no_offset.rst
- pcdsdevices/mrco_motion.py
Prevent writes to DIR/OFF from the UI and Python from users.
Make UI for upcoming TMO MRCO experiments as simple as possible, including removing possibilities for users to change settings that generate confusion or errors in motion and position RBVs.
I tested the module with flake8 and pytest and both came back clean.
(pcds-4.1.4) psdev04:pcdsdevices bosum123$ flake8 mrco_motion.py
(pcds-4.1.4) psdev04:pcdsdevices bosum123$
(pcds-4.1.4) psdev04:pcdsdevices bosum123$ pytest mrco_motion.py
================================================= test session starts ==================================================
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
PyQt5 5.12.3 -- Qt runtime 5.12.9 -- Qt compiled 5.12.9
benchmark: 3.4.1 (defaults: timer=time.perf_counter …
> Changed axes definitions to not allow user changes to offset/Dir via the BeckhoffAxisNoOffset class

- pcdsdevices/mirror.py
A typo in KBO Mirror class for DS Bender RMS. Broken PV of DS RMS value for RIX and TMO
> Fixing a typo in KBO Mirror class for DS Bender RMS PV

- docs/source/upcoming_release_notes/845-scp-cleanup.rst
- pcdsdevices/epics_motor.py
If the user puts in a bad value to `EpicsMotor.set_current_position`, this method can abort before restoring the `.SET` field (`set_use_switch`) to the normal value of `0` (`Use`), leaving it at the value of `1` (`Set`). This can cause confusion when someone tries to move a motor manually later, only for the position to be set instead of used.
This is just a simple try/finally block, we still raise the exception caused by the bad input but we clean up after ourselves.
This is a copy of https://github.com/bluesky/ophyd/pull/999 for use until it ends up in a tag
TMO accidentally fed a string into this method, causing set/use to be set to use, causing much confusion.
Interactively
I'll make a doc
> MNT: set_current_position error handling

- conda-recipe/meta.yaml
- pcdsdevices/epics_motor.py
Add the ability to find and apply parameter manager configurations to IMS motors in hutch python.
This requires pmgr R2.0.2 or higher in the conda environment.  This is a first-pass at support, and a quick merge is not anticipated.
Simplify the deployment of IMS motors by allowing the direct application of saved configurations.
Verified that the singleton pmgrAPI object is created, and configurations for a test motor can be set, retrieved, and searched for.
Doc strings.
> First pass parameter manager support for IMS motors

- docs/source/upcoming_release_notes/842-egu-cb-failure.rst
- pcdsdevices/pseudopos.py
Ignore `TimeoutError` when doing the value update in DelayBase.
This method is called at init in ophyd with `run=True`: https://github.com/bluesky/ophyd/blob/705fc9bc0fee41aaca806bb9d66caba7a7cd99e5/ophyd/pseudopos.py#L426-L427
This is a good idea in most cases, but in the case where:
- You are loading many devices at once
- And this callback needs to get an EPICS value
This will cause issues.
This logs an error in XPP during the load:
```
ERROR    Subscription readback callback exception (Newport(XPP:LAS:MMN:16, name=xpp_txt_motor))
File "/u1/xppopr/conda_envs/pcds-4.1.5/lib/python3.8/site-packages/ophyd/signal.py", line 1115, in _get_with_timeout
self.wait_for_connection(timeout=connection_timeout)
File …
```
> MNT: Workaround for error spam at XPP

- docs/source/upcoming_release_notes/846-pmgr-ci.rst
- pcdsdevices/epics_motor.py
- requirements.txt
- Create the pmgr singleton only on first instance of IMS class, we don't need to do it if we aren't using IMS
- Allow us to move on if the pmgr singleton fails to be created
- flake8 edits for style consistency (line length, import sorting)
- Fails travis on import because we are running a script that only exists on NFS when we load the IMS class
- Fails the flake8 check in travis
Locally and hopefully travis passes now
I'll make a release snippit
> MNT: pmgr CI fixes

- docs/source/upcoming_release_notes/847-init-preset.rst
- pcdsdevices/interface.py
Fix issue where motor presets would not load until the first access of the presets object by creating it during `__init__`
See #847 
Diling says it works
> ENH: create presets at init time

- pcdsdevices/targets.py
- tests/test_targets.py
Updates a few things in the fixed target scan code. I think the main part is that it doesn't load the file on every use of most methods.
Loading a large data file every time you want to do something is very slow.
This code has been run during multiple experiments. There's still more to be done but I think this should get merged in as it's better than the previous version of the fixed target code. Also looks like tests were added and pass in Travis.
I'll make a pre-release notes file. Docstrings also look updated.
> MNT:  Fixed Target Scan - split into one file per sample

- MANIFEST.in
- dev-requirements.txt
- docs/source/index.rst
- docs/source/ui.rst
- docs/source/upcoming_release_notes/854-typhos-templates.rst
- pcdsdevices/state.py
- pcdsdevices/ui/AttenuatorCalculatorSXR_Blade.embedded.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade.detailed.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_calc.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_filters.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_overview.ui
- pcdsdevices/ui/AttenuatorCalculator_AT2L0.detailed.ui
- pcdsdevices/ui/AttenuatorCalculator_AT2L0.ui
- pcdsdevices/ui/AttenuatorCalculator_AT2L0_calc.ui
- pcdsdevices/ui/AttenuatorCalculator_AT2L0_filters.ui
- pcdsdevices/ui/AttenuatorCalculator_AT2L0_overview.ui
- pcdsdevices/ui/AttenuatorCalculator_filter.ui
- pcdsdevices/ui/BeckhoffAxis.detailed.ui
- pcdsdevices/ui/BeckhoffAxis.embedded.ui
- pcdsdevices/ui/StatePositioner.detailed.ui
- pcdsdevices/ui/StatePositioner.embedded.ui
- pcdsdevices/ui/TwinCATStatePositioner.detailed.ui
- pcdsdevices/ui/TwinCATStatePositioner.embedded.ui
- pcdsdevices/ui/__init__.py
- pcdsdevices/ui/at2l0_filters.json
- setup.py
- tests/test_ui.py
- Add pcdsdevices/ui directory, which includes typhos templates and an `__init__.py` file that solves for the local path name of the ui folder.
- Add an appropriate typhos.ui entry point to setup.py
- Disable the stop button for state positioners with no stop functionality
- Add a clear_error function for typhos state positioners for the positioner widget to find their error clear
- Typhos shouldn't have pcdsdevices assumptions baked in
- Easiest to version control pcdsdevices screens with the device definitions
- https://github.com/pcdshub/typhos/pull/446
- https://github.com/pcdshub/typhos/pull/447
Added a test (adds typhos test dependency)
Added a page to the docs
> ENH: Typhos templates and entry point

- docs/source/upcoming_release_notes/869-added_GFS_fault_setpoint,_GCC,_PIP_autoOn_and_countdown_timer.rst
- pcdsdevices/gauge.py
- pcdsdevices/pump.py
Dan Flath required to add GFS fault setpoint to readable through EPICS. Alex required to automatically turn on GCC and PIP after power outage. The modification allow user to turn on Auto recover function from EPICS GUI. 
Tested following the confluence page. 
Documented following the confluence page.
> Add gfsplc

- docs/source/upcoming_release_notes/871-ccm-pvs.rst
- pcdsdevices/ccm.py
- pcdsdevices/epics_motor.py
- pcdsdevices/tests/test_ccm.py
- pcdsdevices/utils.py
CCM class currently gets calculation constants from three places:
- defaults in ccm.py
- definitions in beamline.py
- definitions in happi
This replaces all of those options with:
- from PVs defined in the XPP and XCS hutches
This is accomplished using a mix-in class that is applied in several places, along with some light aliasing, so that all of these are valid ways to read/write to the constants:
- ccm.E.theta0.put(15)
- ccm.theta0.put(15)
- ccm.energy.theta0.put(15)
- ccm.E_Vernier.theta0.put(15)
And these will all be synchronized with each other, even between different hutch python sessions.
Note: since this removes configuration options, it will likely require changes to beamline.py and the happi database.
Adjusting the CCM offset manually is a pain. This function helps us do it …
> ENH: CCM calc constant PVs and set_current_position(energy)

- docs/source/upcoming_release_notes/868-filter-motor-spam.rst
- pcdsdevices/__init__.py
- pcdsdevices/epics_motor.py
- pcdsdevices/registry.py
- pcdsdevices/tests/test_ccm.py
- pcdsdevices/tests/test_epics_motor.py
Make the post-move error or warning about alarm levels only appear if we requested the move in the current session.
This is achieved by adding a context-sensitive log filter to the motor's `self.log`.
Note that this has a limitation where it will have unpredictable behavior if we have multiple objects with the same name. This is because the name is the piece of metadata that identifies the log messages.
Related `ophyd` code:
https://github.com/bluesky/ophyd/blob/dd4b3e389a0202ecacce39fc3965d703c616b0d4/ophyd/epics_motor.py#L283-L291
Note how these are run in a callback based on the done moving PV, which applies to all open sessions.
ref https://jira.slac.stanford.edu/browse/LCLSECSD-168
Added some targetted tests that snoop on the logging outputs.
Docstrings and release notes.
> ENH: filter motor status spam from other sessions

- docs/source/upcoming_release_notes/873-slits-template.rst
- pcdsdevices/ui/BeckhoffSlits.detailed.ui
- pcdsdevices/ui/BeckhoffSlits.embedded.ui
- pcdsdevices/ui/PowerSlits.detailed.ui
- pcdsdevices/ui/PowerSlits.embedded.ui
- Make a typhos UI template for the BeckhoffSlits class using @ghalym 's pydm slit elements
- Make an example/guide as to how to make typhos templates
https://confluence.slac.stanford.edu/display/~zlentz/Converting+a+PyDM+UI+to+a+Typhos+Template%3A+Learning+by+Example
(I think some version of this will end up in the typhos docs and in the internal pcds docs)
Image:
- Auto slits screen is kind of rough
- TMO wants the two screens to be the same
- I want the two screens to be the same
- Maggie already had some slit elements available from her previous screen work
- I wanted to make an example/tutorial for how to make typhos templates
Interactively
Added pre-release notes
Recording the development process in my confluence page for use in docs later
> ENH: BeckhoffSlits UI

- docs/source/upcoming_release_notes/876-tmo_spectrometer.rst
- pcdsdevices/spectrometer.py
Added a class at the end of spectrometer.py to connect to motor PVs associated with the TMO Photon Spectrometer.
A tmo_spectrometer class is necessary for creating an entry in the happi database and for connecting to a typhos GUI to control motion along the axes.
I tested the module with flake8 and pytest and both came back clean.
(pcds-4.2.0) psdev04:pcdsdevices bosum123$ flake8 spectrometer.py
(pcds-4.2.0) psdev04:pcdsdevices bosum123$
(pcds-4.2.0) psdev04:pcdsdevices bosum123$ pytest spectrometer.py
============================================================== test session starts ===============================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False …
> TMO Spectrometer Class in Spectrometer.py

- docs/source/upcoming_release_notes/887-lampflowcell.rst
- pcdsdevices/lamp_motion.py
Added LAMPFlowCell class at the end of lamp_motion.py to connect to motor PVs associated with the x454 configuration of LAMP motion components of the LAMP IP1 endstation. 
The dVMI will be taken off of LAMP for x454 in exchange for a 4 axis flow cell manipulator. These axes need to be reflected in the motion control GUI.
I tested the module with flake8 it came back clean.
(pcds-4.2.0) pslogin02:pcdsdevices bosum123$ flake8 ./lamp_motion.py
(pcds-4.2.0) pslogin02:pcdsdevices bosum123$
I also tested whether I can make a device with it to verify the PV and component names:
There is a docstring for the class. 
Confluence documentation is found here: 
https://confluence.slac.stanford.edu/display/L2SI/LAMP+Motion+System#LAMPMotionSystem-MechatronicParameters
> Added LAMPFlowCell class to lamp_motion.py for the x454 configuration

- docs/source/upcoming_release_notes/344-stop_methods.rst
- pcdsdevices/pump.py
- pcdsdevices/sequencer.py
- pcdsdevices/sim.py
- pcdsdevices/state.py
ophyd expects a kwarg-only boolean `success` in `stop` methods.
ref. https://github.com/bluesky/ophyd/blob/810eae0894e3f349ea043f7e22ff49450c88af5a/ophyd/device.py#L1325
Closes #344 
Test suite
> MNT: fix up all stop methods

- docs/source/upcoming_release_notes/905-ephot-pvs.rst
- pcdsdevices/beam_stats.py
- pcdsdevices/tests/test_beam_stats.py
- Update the `BeamEnergyRequest` class to point to the newly defined PVs
- Add support for K line additional letter and 1st vs 2nd bunch for `SET1` vs `SET2`
- Set the defaults for the new arguments such that the correct config is chosen for the existing hutches. That is, existing uses of `BeamEnergyRequest` will continue to work the same, just pointing to the new PV.
- Add tests to make sure I did it right
We're standardizing our PVs that we use to communicate with the ACR about scanning changes for the Vernier and Undulators, so we'll stop using the previous PVs.
I added tests that the setpoint PVs are chosen correctly for XPP and TMO, and that a theoretical 2 bunch TXI would be able to select the PVs it needs.
I've added type annotations and docstrings, I'll also add a pre-release …
> ENH: update to the new ephot pvs and add tests

- docs/source/upcoming_release_notes/900-lodcm-nan.rst
- pcdsdevices/lodcm.py
If our two crystal orientations do not match, make the calculation NaN instead of throwing an exception.
`inverse` is called in a callback, so if it throws an exception it ~barfs all over the screen~
It no longer spams the screen due to other changes since making this PR, but it still spams the logfile and it means we'll either have no value stored for the pseudoposition, or a stale value in the case of this error state.
Added pre-release notes
> MNT: lodcm calc should not raise in background thread

- docs/source/upcoming_release_notes/901-bk-user-enable.rst
- pcdsdevices/epics_motor.py
This PV was added back in March, let's include it in the screen.
This new signal will allow the user to cut power to their motors via EPICS.
This PV exists and would have been useful very recently with a runaway motor.
Only interactively:
Added pre-release notes
> ENH: add user enable PV

- docs/source/upcoming_release_notes/879-Various_changes_from_XPP.rst
- pcdsdevices/ccm.py
- pcdsdevices/epics_motor.py
- pcdsdevices/interface.py
- pcdsdevices/ipm.py
- pcdsdevices/jet.py
- pcdsdevices/pim.py
- pcdsdevices/tests/test_ipm.py
- pcdsdevices/tests/test_pim.py
This is a collection of changes that were being used in the XPP's dev version of pcdsdevices.
This includes:
- updating the default theta0 for CCM objects
- using a hacky version of BeckhoffAxis in the Liquid Jet classes to work with the old version currently used by IOC
- adding the acceleration field to the IMS class
- changing component names, aliases, and tab whitelists
Some parts were done to make things work (better).
Some parts were done because scientists requested them.
Interactively.
Docstrings have (mostly) been updated accordingly, and everything will be covered in the pre-release notes.
> MNT: Various changes from XPP

- docs/source/upcoming_release_notes/908-fix_repr_pretty.rst
- pcdsdevices/ccm.py
- pcdsdevices/interface.py
Status prints should not fail miserably. Make it so.
Closes #908 
Closes #909
Local testing.
Release notes.
> FIX: repr pretty and CCM status print exceptions

- docs/source/releases.rst
- pcdsdevices/signal.py
- Only show the md error log when we've edited the metadata.
- Achieve this by aborting the metadata checker when we did not edit the metadata.
- Add release notes for bugfix release to include in the 5.1.1 env
- closes #914 
- env release is today
Before:
```
In [1]: from pcdsdevices.epics_motor import Newport
In [2]: mot = Newport('XPP:LAS:MMN:02', name='mot')
No enum strings on 'XPP:LAS:MMN:02.RBV'; was 'EpicsSignalROEditMD' used inappropriately?
No enum strings on 'XPP:LAS:MMN:02.RBV'; was 'EpicsSignalROEditMD' used inappropriately?
No enum strings on 'XPP:LAS:MMN:02.VAL'; was 'EpicsSignalEditMD' used inappropriately?
```
After:
```
In [1]: from pcdsdevices.epics_motor import Newport
In [2]: mot = Newport('XPP:LAS:MMN:02', name='mot')
```
(no message after)
Release notes
> MNT: MD error log, DOC: release notes

- docs/source/upcoming_release_notes/919-wave8_device.rst
- pcdsdevices/digitizers.py
Adds a number of classes for the LCLS-II wave8. There are two top level classes, and many supporting classes. These classes largely just aggregate PVs for Typhos and for later hutch python scripting. These classes attempt to achieve feature parity (or better) than what is provided via EDM. 
Closes #919 
Tested using a live Wave8 in the ASC timing lab. Some controls were tested. Many registers are not documented, so I did not try writing to every PV/register that is available. I compared readbacks and control points against existing EDM screens for the Wave8. 
In the code. There is no documentation for these registers, so clearly documenting the purpose of each is difficult.
> Add support for LCLS-II Wave8

- .travis.yml
- docs/source/upcoming_release_notes/927-pmgr-tab.rst
- pcdsdevices/epics_motor.py
The following methods are linked to the pmgr for the IMS class, this exposes them to the tab completion filter:
- configure
- get_configuration
- find_configuration
There is some desire to use these more
n/a, checked the spelling
pre-release notes
> ENH: add pmgr methods to IMS tab whitelist

- docs/source/upcoming_release_notes/923-Add_script_for_generating_ophyd_classes.rst
- make_ophyd_device
- pcdsdevices/make_ophyd_device.py
Adds in a script to help automatically generate an ophyd device from an IOC db file. 
This helps reduce the amount of rote work that happens when writing a device composed of signals. 
Closes #923 
Tested on the pgpWave8 IOC, with lots of structure to the DB file, as well as the qadc IOC, which is a pretty flat db file that is representative of many IOCs that we have. 
Docstrings and comments. The argparser provides some CLI help. 
Output for qadc:
Fraction of the output for the wave8: 
*snip*
> Automated Ophyd Device Generation

- docs/source/upcoming_release_notes/918-Add_classes_for_qadcs.rst
- pcdsdevices/digitizers.py
Adds in classes for the Abaco FMC126 (old) and FMC134 (new) PCIe digitizers. 
Generates typhos screens, enables scripting. 
Closes #918 
Tested by viewing a qadc in CXI, and viewing/configuring a qadc134 in RIX. 
Docstrings. 
Old qadc:
New qadc:
> Add in classes for qadc digitizers

- docs/source/upcoming_release_notes/933-lamp_lv_17.rst
- pcdsdevices/lamp_motion.py
Added LAMPFlowCell class at the end of lamp_motion.py to connect to motor PVs associated with the x454 configuration of LAMP motion components of the LAMP IP1 endstation.
In addition to the Gas Jet, and Sample Paddle manipulators, a 2 axis Detector manipulator has been added for the LV17 configuration of LAMP. These axes need to be reflected in the motion control GUI.
I tested the module with flake8 it came back clean:
I also tested whether I can make a device with it to verify the PV and component names:
There is a docstring for the class.
Confluence documentation is found here:
https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=337052991
> LAMP_LV_17 motion class addition to lamp_motion.py

- docs/source/upcoming_release_notes/932-atten_screens.rst
- pcdsdevices/ui/AT2L0.detailed.ui
- pcdsdevices/ui/AT2L0.embedded.ui
- pcdsdevices/ui/AttenuatorSXR_Ladder.detailed.ui
- pcdsdevices/ui/AttenuatorSXR_Ladder.embedded.ui
- pcdsdevices/ui/detailed_tree.ui
Load correct screens without additional clicks for the solid attenuators
Closes #932 as reported by users
Interactive testing with dev typhos
PR text + issue
> MNT/FIX: add detailed_tree from typhos and soft-link attenuator screens

- docs/source/upcoming_release_notes/930-Add_Cycle_RFoF_classes.rst
- pcdsdevices/lasers/rfof.py
Add in classes for the Cycle RFoF transmitter and receiver. 
These are useful in the new timing system. 
Closes #930 
Tested on RFoF systems in the timing lab. 
Docstrings. 
Example TX screen. Ignore confusing units, that's an issue with Cycle's firmware.
> Add devices for Cycle RFoF systems

- docs/source/upcoming_release_notes/935-fix_edit_md.rst
- pcdsdevices/inout.py
- pcdsdevices/signal.py
- pcdsdevices/state.py
- pcdsdevices/utils.py
This fixes some issues related to a flurry of recent bug reports. The following changes have been made:
- The MD update signal will be more lenient for cases where specific unset values ("Invalid") persist from the TwinCAT PLC. Devices like TwinCAT state positioners will stop throwing large confusing errors related to invalid enum strings.
- The MD update signal will not send metadata updates until all composite signals are ready and have contributed their values.
- State names are no longer case-sensitive: states like "Out", "out", and "OUT" will be understood to be the same.
- HelpfulIntEnum has been temporarily vendored from pcdsutils/pcdsdaq. This will change to an import in a future release.
- Several state devices have spammy errors when created that interfere with our ability to …
> FIX: EpicsSignalEditMD and state positioner-related fixes

- docs/source/upcoming_release_notes/937-sl1k2_targets.rst
- pcdsdevices/signal.py
- pcdsdevices/slits.py
Fix number of targets on sl1k2
Closes #937 
Loaded with happi
PR/ issue
> FIX: sl1k2 only has 2 targets

- docs/source/upcoming_release_notes/943-mr1l0_mr2l0_states.rst
- pcdsdevices/mirror.py
Sets state count for mr1l0_homs and mr2l0_homs mirror stripes.
Closes #943 
`happi load`:
```
In [1]: mr1l0_homs.coating.states_list
Out[1]: ['Unknown', 'B4C', 'B4C/Ni']
In [2]: type(mr1l0_homs.coating).config.kwargs
Out[2]: {'state_count': 2}
```
Release notes, issue, and PR text
> FIX: mr1l0_homs, mr2l0_homs

- docs/source/upcoming_release_notes/945-slow_motor_move_to_start.rst
- pcdsdevices/sim.py
- pcdsdevices/tests/test_interface.py
Simulated Slow motors fail to move in a scan if the first position is the current position. 
Broadly, this issue appears any time sim.slow_motor was moved to its current position with the `wait` argument enabled
This is a functionality that should be included.  
Addresses #945 
Tested interactively, test added to `test_interface.py`
Code has been commented, related issue, this PR.
> BUG: mark success if already at goal

- docs/source/upcoming_release_notes/949-kbo-fixes.rst
- pcdsdevices/mirror.py
* Added cooling flow/pressure sensor readouts in a KBO mirror child class: KBOMirrorHE
* Added Y axis to device status output
New hardware installed.
Ran in local pydev environment and view in a typhos screen with mirror mr2k4.
> ENH: Add KBOMirrorHE and add y axis to KBOMirror status

- docs/source/upcoming_release_notes/955-preset-rbv.rst
- pcdsdevices/interface.py
- pcdsdevices/tests/test_interface.py
Fix the issue where preset state readbacks were wrong.
These state readbacks show up in the terminal pretty printer and are confusing if incorrect.
closes #955 
Added a test to demonstrate the failure, fixed the code appropriately, test now passes.
Only in release notes
> BUG: Fix preset state readbacks

- docs/source/upcoming_release_notes/958-biological_parents_for_GroupDevice.rst
- pcdsdevices/device.py
- pcdsdevices/tests/test_device.py
Adds ``biological_parent`` attribute to GroupDevice objects.  
We orphan the devices to hide them from ``stage`` methods, but then they get lost forever
Ran test suite, opened a few GroupDevices (xrt_m2h, xcs_sb2_ipm)
A line in the docstring
> ENH: Add biological parents to GroupDevice

- docs/source/upcoming_release_notes/963-init_ordering.rst
- pcdsdevices/signal.py
Callbacks *can* happen prior to the rest of `EpicsSignalROEditMD.__init__` being configured, so `.connected` raises AttributeError.
Re-orders initialization of affected classes.
Closes #963 
Test suite and reloading xcspython
> FIX: call super() after setting up enum attrs

- docs/source/upcoming_release_notes/962-device_elog_post.rst
- pcdsdevices/interface.py
With newfound experience posting to the ELog, we can give every device the ability to post its status to the elog.  
The `elog` package comes with a method for registering the elog so we leverage that and use `elog` as an optional dependency.  [(elog is registered on init)](https://github.com/pcdshub/elog/blob/dbe280a04d7f9d0209087b24ad938d25bcb98e5e/elog/elog.py#L146)
[Jira ticket](https://jira.slac.stanford.edu/browse/LCLSPC-124)
We're hoping to provide scientists an easy and accessible way to log their beamline state. 
Interactively.  Tests for this seem redundant with existing status print tests and elog's own tests.  I've chosen to not write any new tests, but this time not out of sloth.
I also accidentally posted `at2l0` status to the xcsp23820 elog, so...
Docstrings, though there's …
> ENH: add post_elog_status to BaseInterface

- docs/source/upcoming_release_notes/966-perf-last-status.rst
- pcdsdevices/interface.py
Under the hood, these `Status` objects create daemon threads for running callbacks.
For one device, this isn't a big deal, but for a large device like xcs_lodcm, this can add up to hundreds of milliseconds.
Determined with the excellent tooling provided by the WIP https://github.com/pcdshub/pcdsutils/pull/47
Let's speed up startup loading.
Locally.
This PR text.
> PERF: remove unnecessary Status objects

- docs/source/upcoming_release_notes/968-PTMPLC.rst
- pcdsdevices/pump.py
Added variable for current monitoring below the pump_speed variable to the PTMPLC class.
Scientists have requested to monitor pump current. The only issue I see here is this is read by serial, so if the serial interface is not working correctly, then both the current and speed will both display zero even when the pump is running fine.
Docstring.
> Added current monitoring PV to PTMPLC class

- docs/source/upcoming_release_notes/971-mirror-tabs.rst
- pcdsdevices/mirror.py
Put `tab_component_names = True` on every mirror device
None of the key parameters e.g. pitch were showing up in the filtered tab completion
See https://jira.slac.stanford.edu/browse/LCLSECSD-403
Release notes
> ENH: set component names to show up on all mirror device tab completion

- docs/source/upcoming_release_notes/967-namespace_elog_post.rst
- pcdsdevices/_html.py
- pcdsdevices/tests/conftest.py
- pcdsdevices/tests/test_utils.py
- pcdsdevices/utils.py
Added a function (and helper function) for gathering up ophyd objects and posting them to the elog.  
Recursively walks through an iterable of devices and formats their `.status()` output into collapsible blocks.  
[Jira ticket](https://jira.slac.stanford.edu/browse/LCLSPC-124).   
Was formerly in nabs [(PR)](https://github.com/pcdshub/nabs/pull/55), now moved over.
Hopefully this will provide another way for scientists to log their beamline state.  
With the new `biological_parents` attribute of `GroupDevices`, we can post entire namespaces without cluttering the post with child devices.  
Interactively, sample posts using devices in xcs hutch python, a few tests have been added to `test_utils.py`
pcds-5.3.0
Docstrings, which have some example code
> ENH: Namespace elog post

- docs/source/upcoming_release_notes/975-tmo_spec_offsets.rst
- pcdsdevices/spectrometer.py
Allow user offsets for TMO spectrometer motors by reading motor Cpts via BeckhoffAxis class instead.
Open loop motors are susceptible to losing position. Once Scientists have tuned everything nicely its a huge hassle to try to realign stuff from scratch.
Docstring
> Allow user offsets for TMOSpectrometer attributes

- docs/source/upcoming_release_notes/963-init_ordering.rst
- pcdsdevices/signal.py
`EpicsSignalBaseEditMD` and related classes can have initialization problems as in #978 and #963.
* Intending to close #978 
* Supersedes my failed fix in #964 
* I'm hoping to come up with a good fix the 2nd time around so a 3rd time around isn't necessary.
* Test suite
* Loaded up LFE screen as in the issue and didn't notice a traceback
* Current `lfe` still shows log-related error messages
* PR and issue text
> FIX: follow-up to #964; subscribe-after-init

- docs/source/upcoming_release_notes/957-twincat-state-velo.rst
- pcdsdevices/state.py
Add a velocity summary for the twincat state movers using the MultiDerivedSignal.
This signal has the following behavior:
- display the highest velocity defined among all the state destinations
- allows a one-step bulk write to all the state velocities for that motor
- Bulk write is a common operation
- It's hard to manage the speeds in a screen as-designed, but with the summary it should be easy
- People keep getting the state velocities (hidden) mixed up with the motor point to point velocity (easy to find)
closes #957
Interactively only. The multi-signal connects for the TMO PPMs and properly shows/updates the velocities.
Pre-release notes only
> ENH: State velo summary

- docs/source/upcoming_release_notes/980-dual-valve.rst
- pcdsdevices/valve.py
Add a dual-acting valve class for the three dual-acting valves that are in RIX.
RIX has dual acting valves and this class can be used for the expert screen.
In conjunction with https://github.com/pcdshub/pcdswidgets/pull/72
here's the expert screen that pops up with all connected PVs, including the omitted PVs for completeness:
There are some inconsistencies in the naming here, but I think that's not up to this class or this PR to resolve. I'd like to see the valve classes in general have some naming consistency at some point.
This class, in my opinion, should just be a simple union of the NC and NO classes.
Pre-release notes only
> ENH: add dual-acting valve class.

- docs/source/upcoming_release_notes/993-new_devices_for_mirrors.rst
- pcdsdevices/mirror.py
- Added class `XOffsetMirrorRTDs`.
- Added class `FFMirrorZ`
- Offset mirrors in the XRT recieved RTDS; make hardware additions reflect in device.
- Dream MR4/5K4 are `FFMirror` with Z axis; add device support for the Z axis.
New Hardware installations.
- Typhos screen for `XOffsetMirrorRTDs` launched using local `pydev_env`:
- `typhos 'pcdsdevices.mirror.XOffsetMirrorRTDs[{"prefix":"MR1L3:HOMS"}]'`
- happi entries made for `mr4k4_kbo` and `mr5k4_kbo`
- `FFOffsetZ` screens tested with `typhos mr*k4_kbo`
- need gateway access for `MR4K4:KBO && MR5K4:KBO` done
- inheriting `FFMirror` in `FFMirrorZ` puts the Z axis in a bit of an awkward position. Worth making its own class? Fixed by re-ordering `_sig_attrs`
Will be documented in release changes.
> Mirror screens

- docs/source/upcoming_release_notes/997-spec-lightpath.rst
- pcdsdevices/spectrometer.py
Add the stock lightpath constants from the 2.2 mono for "optics devices that are always in" to the tmo spec and the hxrsss. This is better than having broken support, though may not be completely accurate.
tmo lightpath has this error repeated infinitely now:
```
[2022-04-14 12:15:08] - ERROR -  Unable to determine device state for TMOSpectrometer(TMO:SPEC, name=sp1k4)
File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/site-packages/lightpath/path.py", line 87, in find_device_state
_in, _out = device.inserted, device.removed
File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/site-packages/ophyd/device.py", line 1197, in __getattr__
raise AttributeError(name)
AttributeError: inserted
```
The HXR spectrometer was in the …
> MAINT: fix lightpath behavior for tmo spec, hxrsss

- docs/source/upcoming_release_notes/998-add_AT1K0_Apertures.rst
- pcdsdevices/attenuator.py
Added two classes, GattApertureY, GatttApertureX to create new typhos screens that will replace the old screens.
A potentially preventable controls hotline call was taken because the old screens did not show all relevant info.
The typhos screens that these are used to build have been tested to move between the aperture and motor states that they interact with while the SXR didn't have beam on 4/14/2022
comments in class declarations
> Device classes for Apertures in AT1K0

- docs/source/upcoming_release_notes/999-optics-notepad.rst
- pcdsdevices/mirror.py
Add device for optics notepad
Create a device to easily generate a screen and interface with python.
happi device optics_homs_notepad and typhos
> Add device for optics notepad

- docs/source/upcoming_release_notes/1001-jj-slits.rst
- pcdsdevices/slits.py
- pcdsdevices/ui/JJSlits.detailed.ui
Added a class for JJSlits_AT_C8_HV within slits.py.  Along with this was the creation of a typhos controls screen.
This is a necessary addition since the new JJ Slits model: AT-C8-HV move as a pair compared to the regular slits which can move individually. With the creation of this class and screen it can easily be used with various JJSlits_AT_C8_HV using happi and typhos.
This has been tested within the Test rack in building 901. Tested to make sure each axis of slits moves correctly and corresponds to controls screen.
There is a comment within the new class describing the parameters and use.
JJSlits have been moved and were not connected when screenshots were taken, hence the red boxes/errors.
> Created a class and screen for JJ Slits

- docs/source/upcoming_release_notes/994-reorder-cpts.rst
- pcdsdevices/mirror.py
- pcdsdevices/tests/test_utils.py
- pcdsdevices/utils.py
Functional proof of concept for a "device rearranger" for typhos screens without any modifications to typhos. This relies on some ophyd internal implementation details, but in the future it could be swapped out for some explicit typhos order-signaling feature.
Usage
```
reorder_components(
XPIM,
start_with=['zoom_lock', 'focus_lock'],
end_with=['target'],
)
```
or, equivalently
```
@reorder_components(start_with=['zoom_lock', 'focus_lock'], end_with=['target'])
class XPIM(Device):
....
```
Result: the `zoom_lock` and `focus_lock` are at the top of the `typhos` screen, the `target` has been shipped from the top to the bottom.
This has been expanded to include the following helpers as well:
```
move_subdevices_to_start
sort_components_by_name
sort_components_by_kind
set_standard_ordering …
```
> ENH: add util for rearranging the component order for typhos screens.

- docs/source/upcoming_release_notes/982-beamreqref.rst
- pcdsdevices/beam_stats.py
Each of these beam request PVs has an accompanying REF PV that is used as a reference by ACR to determine how to change the energy. This PR adds the PV.
James Cryan asked for this and it was really easy to do
PV connects
Not yet, need to add notes
> ENH: add reference PV to the beam request object

- docs/source/upcoming_release_notes/1004-fix_screen_methods.rst
- pcdsdevices/areadetector/detectors.py
- pcdsdevices/epics_motor.py
- pcdsdevices/interface.py
- pcdsdevices/ipm.py
- pcdsdevices/utils.py
- Adds the `.screen` method to `BaseInterface`, which relies on typhos to auto-generate a screen
- Unifies existing `.screen` methods behind `subprocess`, for more flexibility and consistency
- Fixes bugs in existing IPM screen calls
- Adds camviewer-based `.screen` method to AreaDetector class, with option to open "main" edm screen or the python screen by default.
[Jira](https://jira.slac.stanford.edu/browse/LCLSECSD-282)
There can be times where finding screens is difficult, so opening them from hutch-python can be helpful.  Leaning on existing engineering_tools functions seems to be an efficient path forward.  
IPM devices have proved difficult to universally write a screen method for.  The devices present in ipmConfigEpics do not always match devices in the hutch-python sessions, and …
> ENH: Fix / add screen methods

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/1010-pin-qt.rst
Add run constraint on pyqt to avoid the latest version
Does not need to propagate to the conda-forge recipe, probably
Tests crash in the same way as they did for pydm at pyqt 5.15
Hopefully the tests don't crash after this
pre-rel notes only
> BLD: seems like new pyqt breaks the CI, pin for now

- docs/source/upcoming_release_notes/1009-stopper_container.rst
- pcdsdevices/happi/containers.py
- Fixes Stopper Happi container definition
closes https://github.com/pcdshub/happi/issues/245
`happi container-registry` works now
Here
> BUG: fix Stopper container definition

- docs/source/upcoming_release_notes/1011-badpv.rst
- pcdsdevices/beam_stats.py
Remove bunch_charge_2 from beam stats
Super annoying every time on psbuild-rhel7
```
CA.Client.Exception...............................................
Warning: "Identical process variable names on multiple servers"
Context: "Channel: "FBCK:BCI0:1:CHRG", Connecting to: pscag01-build.slac.stanford.edu:45643, Ignored: pscag01-build.slac.stanford.edu:45580"
Source File: ../cac.cpp line 1320
Current Time: Wed May 18 2022 14:19:50.764512834
..................................................................
ERROR    run - Exception occurred during callback <function PyepicsShimPV.get_all_metadata_callback.<locals>.get_metadata_thread at 0x7fe46762a4c0> (pvname='FBCK:BCI0:1:CHRG')
File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.4.0/lib/python3.9/site-packages/ …
```
> MAINT: remove PV that throws errors on psbuild

- docs/source/upcoming_release_notes/1012-btps-min-pixel.rst
- pcdsdevices/lasers/btps.py
- pcdsdevices/ui/btps-camera-summary.ui
Updates to BTPS as per https://github.com/pcdshub/lcls-plc-las-bts/pull/11
- Updated the Laser Beam Transport Protection system configuration to
reflect the latest PLC/IOC changes: the image sum from near and
far-field cameras is now used instead of centroid positioning.
The relevant screens have been updated as well.
Interactively during deployment.
In release notes and this PR text.
> REF: rework btps for minimum pixel change

- .gitignore
- docs/source/upcoming_release_notes/1013-energy-request-waiter.rst
- pcdsdevices/beam_stats.py
- pcdsdevices/pv_positioner.py
- pcdsdevices/tests/test_beam_stats.py
There's a mode that the energy request PVs can run in where done/not-done information is broadcast by ACR to one of a number of status PVs. This PR adds a mode to `BeamEnergyRequest` where motion will wait and report done based on that given PV instead of using the "done immediately" mechanisms.
This is accomplished by using (abusing?) the `__new__` mechanics to pick which subclass to substitute for `BeamEnergyRequest` based on the input arguments. These subclasses each implement `done` in a different way. The parent `BeamEnergyRequest` class continues to implement shared behavior e.g. pv names of the setpoint PV. This is similar to our handling of `PytmcSignal`. At the cost of some implementation complexity, compared to making a factory functions this allows all variants to be isinstance …
> ENH: Energy request waiter

- docs/source/upcoming_release_notes/1016-kbo-coating-states.rst
- pcdsdevices/mirror.py
Coating States implemented for MR2K4 and MR3K4; need classes to support this. MR2K4 has cooling and MR3K4 does not. Therefore we need two new classes for KBO mirrors:
`KBOMirrorHEStates` and `KBOMirrorStates`
Coating States deployed to TMO MR2K4 and MR3K4
Launched each Typhos screen using:
`typhos 'pcdsdevices.mirror.KBOMirrorHEStates[{"prefix":"MR2K4:KBO"}]'`
`typhos 'pcdsdevices.mirror.KBOMirrorStates[{"prefix":"MR3K4:KBO"}]'`
Moved each mirror from one coating state to another and back. `B4C` <-> `Si`
> Add state classes for KBO mirrors with cooling and without cooling

- docs/source/upcoming_release_notes/1023-happi-device.rst
- pcdsdevices/happi/containers.py
happi.device has been deprecated for a long time
In order to keep the existing containers working as-is, vendor it.
Rename from Device to LegacyItem to avoid Device -> Device naming confusion.
At some point we need to rework our containers appropriately- figuring out which things need specific containers and which do not.
https://github.com/pcdshub/happi/pull/266#discussion_r900453184
Devices still load from happi
I'll make a pre-release doc
> ENH: move Device from happi.device and rename

- docs/source/upcoming_release_notes/1025-setup_pmgr_later.rst
- pcdsdevices/epics_motor.py
Rather than setting up pmgr on the first IMS init, do it on the first pmgr usage.
Make `IMS.setup_pmgr` public API.
It takes 3 seconds to setup the pmgr because the import is slow.
Applications that don't use pmgr shouldn't pay this cost.
Applications that do use pmgr may want to set it up manually before using it, so we provide a public API for doing this.
I need to check this a bit on nfs, there's no easy to way to make regression tests here
pre-release notes only
> ENH/FIX: setup pmgr later

- docs/source/upcoming_release_notes/1030-delay-pint.rst
- pcdsdevices/utils.py
import `pint` when it is used and no earlier.
importing `pint` can be slow and should be skipped if it is not used.
`pint` is a module that is used in this repository to handle unit conversions.
During the first import of `pint`, it makes several additional imports whether the resources from those imports are used or not. I assume this is done to ensure that those optional dependencies are fully functional when used in conjunction with `pint`, and there is probably some base assumption that these imports are light operations.
The additional imports that pint makes in `pint.compat` on import of `pint` are:
- `pandas`
- `pyarrow` (via pandas)
- `numpy`
- `xarray`
- `dask`
- `scipy` (via dask)
- `distributed` (via dask)
- `fsspec` (via dask)
`pint` source code: …
> MAINT: delay the pint import, it is slow

- docs/source/upcoming_release_notes/1032-enh_mv_on_requestor.rst
- pcdsdevices/beam_stats.py
Quick fix: upgrade the beam energy requestor from BaseInterface to FltMvInterface for all the movement aliases
James Cryan noticed this was missing on slack.
Interactively + the tests for this device still pass
pre-release notes will have an entry for it
> ENH: add flt mv interface to beam energy request

- docs/source/upcoming_release_notes/1039-Create_separate_module_for_light_control.rst
- pcdsdevices/cvmi_motion.py
- pcdsdevices/device_types.py
- pcdsdevices/light_control.py
Added a separate module, light_control.py, for devices for controlling light brightness. Removed internal module CvmiLed from cvmi_motion.py
https://github.com/pcdshub/pcdsdevices/issues/1039
A lot of the testing was previously done by @Mbosum here: https://github.com/pcdshub/pcdsdevices/pull/1017
> Adding separate module for LED (and other light devices) control

- docs/source/upcoming_release_notes/1038-usb_encoder.rst
- pcdsdevices/pseudopos.py
- pcdsdevices/usb_encoder.py
Add USB encoder class to pcdsdevices. 
This will allow to remove it from the beamline.py files and ensure better uniformity in handling USB encoder devices. A set_zero method has also been added to the DelayBase class. This will allow reset of the delay to the time zero to use the same command as the encoder.
The USB encoder class can take a linked stage and both can be set to 0 using the `set_zero_with_stage` method.
Tested in xpp3. Behaves as expected.
Docstring
> ENH: USB encoder

- docs/source/upcoming_release_notes/1034-Kill_ccm_PID_on_move.rst
- pcdsdevices/ccm.py
- pcdsdevices/tests/test_ccm.py
Kill CCM's PID loop at the end of a move command
The PID loop keeps looking for the final position forever. The motor thus runs at too high duty cycles, heats up and causes vacuum spikes in the chamber. This has led to MPS trips. In addition, there is serious potential to fry the motor itself, as it is run too intensively.
Currently running at XPP for CCM experiments. Still waiting on confirmation that this all works fine before finalizing this pull request
Docstring of the new move function.
> add PID kill at the end of CCM motion

- docs/source/upcoming_release_notes/1047-Adding_LightControl.ui.rst
- pcdsdevices/ui/LightControl.ui
Added a simple gui for controlling fiber-lite intensity
https://github.com/pcdshub/pcdsdevices/issues/1047
The LightControl class has already been tested, the gui has yet to be tested
> ENH: Added ui for LED control

- docs/source/upcoming_release_notes/1055-tst_race_cond_bandaid.rst
- pcdsdevices/tests/test_interface.py
Mark test_presets as xfail for now
We're not actively working on the presets system and the test has a race condition that is giving false failures on pull request builds. See #1050 for details.
I don't immediately have time to fix the test so I thought this was a prudent band-aid.
Via test suite
I'll add a release notes blurb but hopefully we'll remove it before the next tag
> TST: skip race condition test for now, must revisit later

- docs/source/upcoming_release_notes/1057-Enabling_slider_on_LightControl.ui.rst
- pcdsdevices/ui/LightControl.ui
The slider element on the LightControl.ui was not working, this required just a quick change to the pydm options. Also, added the option to manually type in a number for the illuminator percentage, rather than just needing to use the slider.
This was tested by setting PYTHONPATH to my pcdsdevices working directory, and adjusting the slider. This was confirmed with visually inspecting the light on the device.
> Enable slider on LightControl.ui

- docs/source/upcoming_release_notes/1060-Fixing_some_confusing_naming_regard_override_force_close.rst
- pcdsdevices/valve.py
Issues described here: https://github.com/pcdshub/lcls-twincat-vacuum/issues/105
These changes are entirely cosmetic. Making sure the naming scheme for override force open and close are the same.
> Changing naming of override force close and fixing description

- docs/source/upcoming_release_notes/1052-fix_slits_typos.rst
- pcdsdevices/ui/BeckhoffSlits.detailed.ui
- pcdsdevices/ui/PowerSlits.detailed.ui
In the beckhoff and power slits uis (sort of copy pasted from each other) there was a typo on the south blade rows.
This PR fixes the typo.
I noticed this when helping TMO near the end of the run.
I suspect this row of the screen doesn't get much use...
I need to make a pre-release note
> FIX: some of the south slits had north PV references

- docs/source/upcoming_release_notes/1046-pvstate_metadata.rst
- pcdsdevices/pulsepicker.py
- pcdsdevices/signal.py
- pcdsdevices/state.py
- pcdsdevices/stopper.py
- pcdsdevices/tests/test_state.py
`PVStateSignal` has been given `enum_strs` and `write_access` metadata that behaves similarly to how the `EpicsSignal` metadata does.
On the first value calculation, which occurs only after the device is fully ready to go, we check the parent states device for its static state enum to use to collect the enum strings and for a setpoint reference that we can subscribe to for write access metadata updates, forwarding these in the `PVStateSignal` as appropriate.
We noticed in the lightpath that any devices with `PVStateSignal` behaved inappropriately at the pcdsdevices level, creating what naively looks like ui bugs in `lightpath`, while actually being sourced to here.
This signal type is used in the legacy stoppers, gate valves, pulse pickers, and movable stands.
Interactively by loading …
> ENH: make PVStateSignal report enum_strs and write_access metadata

- docs/source/upcoming_release_notes/1037-enh_evr_motor.rst
- pcdsdevices/evr.py
- Add EVR motor as described by James Cryan in https://jira.slac.stanford.edu/browse/LCLSECSD-1299
- Modify slightly for hints etc.
- Add a tolerance for the set/wait routines for the `ns_delay` signal
Two reasons why the ns cannot be scanned:
1. Lingering issue with LCLS2 DAQ interface that rejects objects without .position
2. Waiting for a set fails/times out because the valid values for `ns_delay` must be tick-aligned. One tick is 8.3ns.
Confirmed that the class still loads.
Worked in TMO
Docstrings
Writing pre-release docs
> ENH: add evr motor

- docs/source/upcoming_release_notes/1041-fix_valvebase.rst
- pcdsdevices/valve.py
* Add `valve_position` to `ValveBase`
* Unclear to me if "legacy" classes need reworking (do they have this PV? were they based on `ST_ValveBase`?). I think a further comparison of the PLC library and the pcdsdevices classes is in order.
Closes #1041 
Test suite
Issue + PR
> FIX: add in valve_position to ValveBase

- docs/source/upcoming_release_notes/1065-mnt_backcompat_lightpathitem.rst
- pcdsdevices/happi/containers.py
Makes LCLSItem fully lightpath-compatible.
- adds both input_branches and output_branches as optional fields in LCLSItem
Turns out if we change anything with the happi database, the dev environment will explode. 
This is made possible by #1062, which made keyword arguments optional when creating a Lightpath device
With recent revisions to device_config https://github.com/pcdshub/device_config/pull/31/commits/7b6c15281ee482807d73db4c45fc7da18a4f85fa that return all containers to `LCLSItem`
This PR
> MNT: make LCLSItem fully lightpath compatible, for backcompat

- docs/source/upcoming_release_notes/1069-fix_lp_sub_spam.rst
- pcdsdevices/interface.py
When initializing the lightpath branches from happi, guard against bad input_branches or output_branches.
If one of these lightpath-compatible devices is instantiated from an old happi db without input_branches and output_branches, it initializes the summary signal but everything fails in a spammy way.
Worked in dev
Need to add release notes
> FIX: do not init summary signal unless we have valid branches

- docs/source/upcoming_release_notes/1070-mnt_rm_lightpathitem.rst
- pcdsdevices/happi/containers.py
We made LCLSItem lightpath-compatible but forgot to switch all the other devices from lp_containers.LightpathItem
To fully apply the previous bugfix #1065 
In updating the device_config, lucid screens work, happi audits work
This PR
> MNT: fully remove lp_container.LightpathItem

- docs/source/upcoming_release_notes/1072-bug_mirror_range_sig.rst
- pcdsdevices/mirror.py
I forgot `self`, so callbacks blew up once real values were being passed through.  🤦‍♂️ 
Fixes callback subscriptions blowing up when my helper methods didn't help.
It turns out that there are common scenarios where this function never gets called (when mirrors are removed), so early testing didn't reveal my stupidity.  
I thought I tested the various possibilities manually, but I guess I didn't.  I should add unit tests to this end but we'll punt that in favor of getting the fix in quickly
interactively 
this PR
> BUG: forgot self in _find_matching_range_indices

- docs/source/upcoming_release_notes/1073-New_quadratic_equation_and_soft_limtis_for_VLS_focus_mirror.rst
- pcdsdevices/crix_motion.py
- pcdsdevices/tests/test_crix_motion.py
VLS focusing mirror testing resulted in finding a new linear to angle conversion equation. This PR input these new coefficients into the crix_motion python module, in addition to changing the resulting soft angular soft limit values. This has been tested in production, this PR just ensures that the changes stick when the next tag is released.
> Changing quadratic equation constants and limits

- docs/source/upcoming_release_notes/1075-doc_lp_example.rst
- pcdsdevices/interface.py
Updates the docstring of LightpathMixin to include a useful example
I've already confused one person and would like to stop doing that
This is documentation
This is documentation
> DOC: update LightpathMixin docstring example

- docs/source/upcoming_release_notes/1063-enh_nc_error_status.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/tests/test_epics_motor.py
- Makes the NC error message and error code get into the status output for BeckhoffAxis moves
- Skips normal EpicsMotor move status handling for BeckhoffAxis, which nearly always has a false positive.
EpicsMotor's MoveStatus gives a lot of false positives and doesn't take advantage of the extra information that we have access to in BeckhoffAxis.
Contributes to https://jira.slac.stanford.edu/browse/LCLSPC-397
Added a test case
The old tests currently fail, probably related to the way I messed around with the move method
The test I added passes locally
This needs to be tested on a real motor
pre-release notes
> ENH: NC error status in BeckhoffAxis

- docs/source/upcoming_release_notes/1077-tst_skip_dev_cls.rst
- pcdsdevices/tests/conftest.py
Adds an optional argument to `find_all_classes` (and by extension `find_all_device_classes`) that skips certain class names.  
Filtering based on subclass has worked in the past, but now searching for all subclasses of ophyd.Device can return the lightpathmixins, which need a little more work to subclass properly.  This only appeared as a problem in https://github.com/pcdshub/atef/pull/132
Test suite runs, atef test suite can be modified to pass now too
This PR
> TST: add option to skip device classes in find_all_device_classes

- docs/source/upcoming_release_notes/1076-enh_zero_vel_check.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/tests/test_epics_motor.py
When the user requests a `BeckhoffAxis` move, check that the velocity is nonzero before attempting the move.
If you execute a move with velocity=0, nothing happens and it can be confusing.
This makes it so at least an exception is raised.
This exception shows up in the typhos screen too.
The BeckhoffAxis EPICS motor records default to velocity=0 for safety.
Added unit tests and tested interactively with test PLC
I'll make a pre-release doc
> ENH: add pre-move check for beckhoff axis nonzero velo

- pcdsdevices/ui/BeckhoffAxis.detailed.ui
- pcdsdevices/ui/BeckhoffAxis.embedded.ui
Use https://github.com/pcdshub/typhos/pull/522 to configure the Beckhoff positioner screens to be less trigger-happy about what counts as an "alarming" beckhoff motor.
~Cannot be merged before typhos is tagged with the above.~ Should not tag with this until typhos is tagged with the above. This can be merged so long as it's run in conjunction with a dev typhos build.
Also slightly adjusts the sizing for the detailed screen to make the error text less squished
There are lots of False positives in here related to https://jira.slac.stanford.edu/browse/LCLSPC-350 and this is a simple workaround.
After this PR, only the alarm state of the .RBV signal will be considered.
Need to
> ENH: only hinted beckhoff ui errors

- docs/source/upcoming_release_notes/1080-sattscreens.rst
- pcdsdevices/ui/AttenuatorCalculatorSXR_Blade_config.embedded.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade.detailed.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_all_filters.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_blade_all_filters.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_calc.ui
Updates to the attenuator screens for AT1K4 and AT2K2.
Closes #1079 by removing the rule entirely
Closes #1080 by showing all the filters and the number that will be inserted
Interactively
PR text
Inserted filters and the configuration matrix of per-blade filters:
> MNT: rework for the 4-blade attenuator screens

- docs/source/upcoming_release_notes/1082-Add_3-stage_motion_on_RTDSK0.rst
- pcdsdevices/rtds_ebd.py
Created a new, lightpath enabled class for the 3-stage actuator on RTDSK0 that will be used for solid drilling experiments.
##In-Depth Description
Added class, RTDSX0ThreeStage to rtds_ebd.py. This will track the lighpath status of the solid drilling experiment samples that will be held by the actuator. There are three stages but the only time there is potential to interfere with the beam is when the Y stage is not at it's outer limit. This is additionally tracked as a fast fault in the PMPS system. 
This  setup will be used to conduct solid drilling experiments for SC readiness, we need a way to easily move multiple samples into and out of beam as needed, warranting the addition of this actuator. We further need some indication that it is not intering with the beam, hence inclusion of …
> ENH: create RTDSX0ThreeStage for RTDSK0 solid drilling experiments

- .pre-commit-config.yaml
- docs/source/upcoming_release_notes/1084-maint_auto_fix_precommit.rst
PR generated from script to fix .pre-commit-config.yaml in all repos, switching out the missing flake8 gitlab mirror for github.
> MAINT: scripted fix for precommit

- docs/source/upcoming_release_notes/1085-Add_blades_to_LusiSlits.rst
- pcdsdevices/device_types.py
- pcdsdevices/slits.py
Add controls of the single blades in a slit as per scientists request.
When aligning the slits, it is sometimes desirables to move a single blade a a time. For example when doing precise clipping of all four slits.
Tested with s4 at XPP.
TBD
> add single blades control by making a new LusiSlitsWithBlades class

- docs/source/upcoming_release_notes/1086-Adding_classes_for_AT1K2.rst
- pcdsdevices/attenuator.py
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade.detailed.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade_all_filters.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade_blade_all_filters.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade_calc.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade_filters.ui
- pcdsdevices/ui/AttenuatorCalculatorSXR_TwoBlade_overview.ui
Adding a class for AT1K2 Solid Attenuator, which has two standard 8 filter blades, and one Linear Bellows Drive which requires simple in/out functionality. 
This has not been tested yet with existing PVs, however the screens generate fine.
> ENH: Adds support for Two Bladed SXR Attenuators and AT1K2 class

- docs/source/upcoming_release_notes/1097-enh_readback_desync.rst
- pcdsdevices/pseudopos.py
- pcdsdevices/tests/test_pseudopos.py
Make `PseudoPositioner` devices defined in this module only write to the `ophyd_readback` signal if they were the most recent device to write to the `ophyd_setpoint` signal.
If multiple python sessions are run with slightly different versions of the same pseudo positioner, they can fight over control of the ophyd_readback signal.
see https://jira.slac.stanford.edu/browse/LCLSECSD-1761
I added a unit test here. This should also be tested in a hutch. It's possible that I'll need to make some tweaks.
Adding some release notes
> FIX: pseudopos readback desync issues

- docs/source/upcoming_release_notes/1105-fix_cxi_pim.rst
- pcdsdevices/pim.py
- pcdsdevices/tests/test_pim.py
There is an automatic state discovery mechanism in the state mover code, but this was added after the PIMs were done. This patch activates it for the PIMs.
In CXI, there is a PIM that does not have a "DIODE" state, so the existing hard-coded references to a "DIODE" state were causing issues. See https://jira.slac.stanford.edu/browse/LCLSECSD-1849
I've interactively confirmed that the CXI PIM works now and that at least one other PIM has not been interfered with.
Release notes, this pull request, and Jira only
> FIX: make PIM use auto state discovery

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/1109-max_xraydb_version.rst
- requirements.txt
Specified compatible xraydb and sqlalchemy versions in requirements files.
See related issue: https://github.com/pcdshub/pcdscalc/issues/21
> BLD: use compatible xraydb and sqlalchemy versions

- docs/source/upcoming_release_notes/1111-mnt_xpp_lp_logic.rst
- pcdsdevices/lodcm.py
Fixes a typo and makes the xpp lodcm never attenuate any beam unless blocking
In a quest for a more accurate lightpath displays
Interactively, though more testing should be done
Here
> MNT: Update xpp_lodcm lightpath logic

- docs/source/upcoming_release_notes/1117-Adding_symbolic_links_for_AT1K2.rst
- pcdsdevices/ui/AT1K2.detailed.ui
- pcdsdevices/ui/AT1K2.embedded.ui
AT1K2 screens were not generating with the cascading screen effect, similar to with the standard SXR Attenuator screens. I added symbolic links to the detailed_tree UI files to alleviate this issue.
Trying out these screens in my work area showed that this change was successful. 
NA
<!--
> Fixing AT1K2 Ui

- docs/source/upcoming_release_notes/974-Add_binning_and_region_size_control_to_PCDSAreaDetectorTyphos.rst
- pcdsdevices/areadetector/detectors.py
Add in PVs for binning and camera image size modification. 
Closes #974 
Tested locally on a live camera, as well as typhos screen generation.
> ENH: Add camera binning and region size to PCDSAreaDetectorTyphos class.

- docs/source/upcoming_release_notes/1129-Add_configuration_method_to_LasBasler_camera.rst
- pcdsdevices/areadetector/detectors.py
Adds in a method to use the `Device.configure()` method to apply a dictionary of PV settings to a camera. 
This will make configuring cameras in the MODS system to common, default values easier. 
Closes #1128 
Tested live on a camera in IP1. 
Some docstrings/comments.
> Add configuration method and dictionary for LasBasler cameras.

- docs/source/upcoming_release_notes/1133-Hxrsss_filter_wheel_update.rst
- pcdsdevices/spectrometer.py
Changed previous filter wheel PV that first defined the motor PV to the states PV.
Wanted to add the ability to change states using enums/state names from a hutch-python session instead of remembering motor positions.
Tested from a hutch machine (xcs-control) in a hutch python session using a simplified conf.yml file and custom happi device file that contained the spectrometer device . Also tested physically to make sure the device moved between the desired states.
Updated doc name within filter attribute.
> Hxrsss filter wheel update

- docs/source/upcoming_release_notes/1138-interface_whitelist.rst
- pcdsdevices/interface.py
- pcdsdevices/tests/test_interface.py
* `screen` and `post_elog_status` weren't specifically whitelisted
* Now they are
Slack reported issue
Included tests
> MNT: interface whitelist

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/1140-bld_test_requires.rst
Conda recipe needs test-requires, not test-requirements
Ran into this looking at lucid
The test suite should now have all the necessary test packages (pytest-timeout, for example)
this pr
> BLD: recipe test-requires, not test-requirements

- docs/source/upcoming_release_notes/1143-optics-notepad.rst
- pcdsdevices/mirror.py
Add 2 New PVs for Auto pitching MR2L3 based on CCM inserted and Coating.
`MR2L3:PITCH:CCM:Coating1` and `MR2L3:PITCH:CCM:Coating2`
Beam Delivery wants to auto pitch  MR2L3 based on Coating and Whether or not the CCM is inserted.
Loaded branch and ran typhos optics_homs_notepad to see the new PVs on screen.
> Add New PVs for Channel Cut Monochromator Inserted

- docs/source/upcoming_release_notes/1145-enh_ptmplc_status.rst
- pcdsdevices/pump.py
Add missing state PV to the PTM pump
https://jira.slac.stanford.edu/browse/ECS-911?filter=-1
Something quick to fix before I need to split for a meeting
Interactively only using TMO's beamline vacuum screen, which includes the PV in a typhos:
Release notes only
> ENH: ptmplc status

- docs/source/upcoming_release_notes/1144-enh_limits_setter.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/tests/test_epics_motor.py
Add a setter to the epics motor interface limits attribute.
XCS was having a problem with this line in `LookupTablePositioner`:
https://github.com/pcdshub/pcdsdevices/blob/af187b6b26235f95056cf9b168bb6decf6627c4c/pcdsdevices/pseudopos.py#L990
Where it sets the limits of the real motor.
Rather than consider ways that this could be done differently to avoid EPICS puts on init, I opted to add the missing limits setter as a quick fix.
Live in XCS
Release notes only
> ENH: add a setter to the epics motor interface limits attribute.

- docs/source/upcoming_release_notes/1148-tcinout_2state.rst
- pcdsdevices/inout.py
``TwinCATInOutPositioner`` by default now uses 2 states as its name implies
(excluding the "unknown" transition sate), with one representing the "out"
state and one representing the "in" state.
I recommended Tong use this class directly with st1k4 as the docstring indicated it was ready for usage without subclassing.
Closes #1148 
Interactively with st1k4
Issue and PR text
```
In [3]: import pcdsdevices
In [4]: pcdsdevices.__file__
Out[4]: '/cds/home/k/klauer/Repos/pcdsdevices/pcdsdevices/__init__.py'
In [5]: st1k4.wait_for_connection()
```
> FIX: TwinCATInOutPositioner should have 2 states by default

- docs/source/upcoming_release_notes/1150-enh_update_test_absorber.rst
- pcdsdevices/sxr_test_absorber.py
- ST1K4 has state-based controls now, add them
- include the controls for enabling/disabling auto mode
- include an error message for when you try to do a manual move in auto mode
- Class that shows the states motor + the epics motor will be useful
- There are other controls involved too
- Overall, scope should be slightly higher than just a state device
- interactively via typhos:
I need to write pre-release notes tomorrow morning
> ENH: include states in SxrTestAbsorber and simplify lightpath handling

- docs/source/upcoming_release_notes/925-Add_pvs_for_SmarAct_calibration.rst
- pcdsdevices/epics_motor.py
Adding in PVs related to calibrating encoded SmarAct axes. 
We want this on the Typhos screen.
closes #925 (FINALLY)
Tested on a motor in TMO. 
The code, this PR.
> Add in PVs related to calibrating SmarAct encoded stages.

- docs/source/upcoming_release_notes/1153-add_spectrometer_solid_attenuator.rst
- pcdsdevices/spectrometer.py
Adding 2D motors state move GUI of Sp1K4 solid attenuator the same as Sp1K4 FZP
Adding one class of SOLIDATTStates. Inside TMOSpectrometer class,  shift all the motors sequence per James request. 
Scientists request to add SP1K4 solid attenuator 
not yet. Plan to test the GUI after it is build. 
https://jira.slac.stanford.edu/browse/ECS-1576
> adding sp1k4 att and thorlab len x

- docs/source/upcoming_release_notes/1156-RTD-Cooling.rst
- pcdsdevices/analog_signals.py
- pcdsdevices/mirror.py
- pcdsdevices/pim.py
- Add a new device for FDQ Flow Meter `FDQ` in `analog_signals.py`
- Make a new class for PPMs with FDQ Flow Meters: `PPMCOOL` currently serving IM3/4/5/6K4.
- Fix `KBOMirrorHE`; only needs one flow meter readout. These serve MR2/3K4
- Update `FFMirrorZ` to include chin guard RTDs serving MR4/5K4
- Add Class `KBOMirrorChin` for Optics currently without cooling but with Chin Guard RTDs. Serving MR3K2
Newly installed flow meters and RTDs.
- `FDQ` class was ran locally in a hutch-python session with functions tested. The PLC still needs to stop writing the offset value, but that will be fixed in a different PLC PR for imagers in TMO.
- `PPMCOOL` was launched successfully in a typhos screen.
- `KBOMirrorHE` was launched successfully with MR2/3K4 - an issue of sharing a pressure readout here …
> Cooling/RTD Device Updates

- docs/source/upcoming_release_notes/1157-api_motion_pv_cull.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/eps.py
- pcdsdevices/example.py
- pcdsdevices/state.py
Based on the discussions in https://docs.google.com/spreadsheets/d/1xfSB1mJwVu4tXvxBT85TEYVi29Z7VoQ4w5CXw13rV8A/edit#gid=0, make changes to pcdsdevices to:
- remove PVs that will be removed
- add PVs that were not removed that were kept because they are helpful (so, long overdue inclusions)
This includes the EPS classes added to the PLCs earlier this year.
I want the python classes to match the overall IOCs as much as possible.
- Everything looks good on existing screens for the normal BeckhoffAxis case for all the motors I've checked.
- I couldn't find a live, running case to check for the old version of the class. Comment is below.
- I've adjusted the example PLC to include an EPS example for that variant.
Just this PR so far. I'll make pre-release notes.
> API/ENH: cull state PVs, include helpful motor PVs

- docs/source/upcoming_release_notes/1160-Update_lxt_limits.rst
- pcdsdevices/lxe.py
- pcdsdevices/tests/test_lxe.py
Update the lxt default limits to 100us.
This is needed when laser timing is far back for some reason
Live when laser timing was bad.
N/A
> change lxt limits to +/-100us

- docs/source/upcoming_release_notes/1161-MSC2_PV_returning_SmarAct_device_class.rst
- pcdsdevices/epics_motor.py
Link MCS2 PVs to the SmarAct class.
SmarAct IOCs are defined either with MSC or MSC2 PVs base.
xpp3 with a MSC2 PV defined in the questionnaire
N/A
> link MCS2 PVs to the smaract class

- docs/source/upcoming_release_notes/1159-row_positioner.rst
- pcdsdevices/ui/BeckhoffAxis.detailed.ui
- pcdsdevices/ui/BeckhoffAxis.embedded.ui
- pcdsdevices/ui/QuadraticBeckhoffMotor.embedded.ui
- pcdsdevices/ui/StatePositioner.embedded.ui
- pcdsdevices/ui/TwinCATStatePositioner.detailed.ui
- pcdsdevices/ui/TwinCATStatePositioner.embedded.ui
Switch BeckhoffAxis and TwinCATStatePositioner to the new row positioner widget in typhos
https://github.com/pcdshub/typhos/pull/563
> REF: include row positioner templates for new typhos

- docs/source/upcoming_release_notes/1162-IM3L0_class_and_detailed_screen.rst
- pcdsdevices/pim.py
- pcdsdevices/ui/IM3L0.detailed.ui
I created a subclass of PPM called IM3L0 - no extra code, it just passes and has a comment explaining that it exists only so I can make a device-specific screen for the IM3L0 without changing the screen that all PPM devices use, which is the default detailed_tree.ui, especially since only the IM3L0 has a Keithley. 
https://jira.slac.stanford.edu/browse/ECS-3778
This has been tested by exporting a my ~/typhos directory to PYDM_DISPLAYS_PATH, which contains PPM.detailed.ui, (called IM3L0.detailed.ui in this commit because I will change the type in the happi database after this is merged so the screen is available in the meantime) and running 'typhos im3l0' to ensure that the screen opens properly and looks like what I expect.
This has not been documented.
> Empty IM3L0 subclass of PPM for device-specific screen

- docs/source/upcoming_release_notes/1164-Add_E1C_to_LODCM.rst
- pcdsdevices/lodcm.py
Add energy control for the first crystal only
When sending the beam to the XRT while not multiplexing with XPP, we want to be able to change the tower1 energy only, without changing alignment of the second tower, which is not in the way of the beam.
On xpp3 with XPP LODCM.
Waiting for scientist's confirmation that it works as intended for them.
> add energy_c for first tower only

- docs/source/upcoming_release_notes/1166-xoffset-switch.rst
- pcdsdevices/mirror.py
- Added two flow and one pressure readout.
- Added function decorator to re-arrange typhos components.
- Added Components `cool_flow1`, `cool_flow2`, and `cool_press` to class `XOffsetMirrorSwitch`
- Added function decorator `reorder_components` to fix typhos component ordering for `XOffsetMirrorSwitch`
- Added cooling flow and pressure sensors to MR1K2
- MR1K2 Typhos components not ordered correctly.
- Launched typhos screen using this branch, observed readouts and correct axes ordering.
https://jira.slac.stanford.edu/browse/ECS-3821
> Add flow/press readouts to XOffsetMirrorSwitch for MR1K2.

- docs/source/upcoming_release_notes/1167-maint_state_velo_prec.rst
- pcdsdevices/state.py
Set the precision of state_velo to 3, instead of the default 0.
This signal shows up in typhos with a default precision of 0, which means the ui doesn't show any details past the decimal point.
This is also fixed generically in typhos itself, but it's good to set it here too for the benefit of other applications and to make it work cleanly with older versions of typhos.
We need to see floats as floats and not as ints
Interactively only, see the following which is this PR + typhos's tag without the typhos-side fix:
pre-release notes
> MAINT: include a precision on the state_velo signal

- docs/source/upcoming_release_notes/1171-IM3L0_K2700_template_fix.rst
- pcdsdevices/ui/IM3L0_K2700.embedded.ui
Renamed IM3L0_K2700.detailed.ui as IM3L0_K2700.embedded.ui
Makes it so IM3L0's detailed screen shows IM3L0_K2700's custom template
I'm not sure why the detailed template didn't work; could be because dev_conda uses a different version of typhos than I was using in my previous commit or because last time I adjusted my PYDM_DISPLAYS_PATH envvar. This time I have been testing from dev_conda, only pointing PYTHONPATH to my local pcdsdevices repo and it used the template only after I renamed it.
> BUG: IM3L0_K2700 not using custom template

- docs/source/upcoming_release_notes/1173-fix_att_states.rst
- pcdsdevices/spectrometer.py
Switch state count on this device from 7 to 6
This causes an error when we load the device and breaks the device in general
There is some deeper bug to fix in the library but this at least patches the surface-level behavior
Interactively only (the big traceback goes away, the state enum gets set up properly)
Here only
> FIX: tmo spec satt has 6 states, not 7

- docs/source/upcoming_release_notes/1174-k2700_specify_cpts_are_for_ranges.rst
- pcdsdevices/pim.py
I added 'range' to the doc attributes and names of the components dcv, acv, dci, and aci of the K2700 class.
I originally thought that the pvs associated with these components were to readback the values in their names, i.e. GetDCV would read the direct current voltage, but they actually get the range configured for each measurement. You use :Reading to get the actually measurement.
N/A
New upcoming release notes
> DOC: specify k2700 cpts are for ranges

- docs/source/upcoming_release_notes/1175-mr1l1.rst
- pcdsdevices/mirror.py
- add class `XOffsetMirrorNoBend` for mr1l1
- mr1l1 installed on the beamline
- launched a typhos screen for `MR1L1:HOMS`.
https://jira.slac.stanford.edu/browse/ECS-1222
> ENH: add class for mr1l1

- docs/source/upcoming_release_notes/1155-Add_LCLS-II_timing_support_for_Qadc134.rst
- pcdsdevices/qadc.py
The new firmware for the QADC supports LCLS-II timing, so that's what we need to use now. 
Closes #1155 
Tested on a Qadc running the latest firmware in TMO. I don't have a LCLS-I version of the Qadc to test the restructured Qadc134 class, but I think I was the only one using it anyway. 
The code.
New detailed typhos screen
> Add new LCLS-II timing support to Qadc

- docs/source/upcoming_release_notes/1183-fix_att_move_err.rst
- pcdsdevices/attenuator.py
- pcdsdevices/pv_positioner.py
- pcdsdevices/tests/test_attenuator.py
- pcdsdevices/tests/test_pv_positioner.py
- Adds `PVPositionerNoInterrupt`: a utility class for PV positioners that cannot start a new move until the previous move completes.
- Applies `PVPositionerNoInterrupt` to `AttBase` to gain this behavior for LCLS-I style attenuators.
For the LCLSI attenuators, if you try to start a new move during the previous move, you get a confusing and useless error. This new error makes it very clear that cannot do this.
As implemented, the IOC will not consider new move requests during the previous move, so nothing of value is lost here.
https://jira.slac.stanford.edu/browse/ECS-4099
- Added a few unit tests
- Interactively checked the error message via the testclass
```
In [1]: from pcdsdevices.tests.test_pv_positioner import PVPositionerNoInterruptLocal
In [2]: loc = …
```
> ENH: for LCLS-I att, give proper error for uninterruptable move

- docs/source/upcoming_release_notes/1187-enh_bk_alarm.rst
- pcdsdevices/ui/BeckhoffAxis.detailed.ui
- pcdsdevices/ui/BeckhoffAxis.embedded.ui
- pcdsdevices/ui/QuadraticBeckhoffMotor.detailed.ui
- pcdsdevices/ui/QuadraticBeckhoffMotor.embedded.ui
For the typhos templates that contain BeckhoffAxis instances, set the alarm widget to only check "hinted" signals.
1. All of the sub-fields of this motor record tend to go into an alarm state at the same time. This is very spammy and redundant.
2. Due to the bug described in https://jira.slac.stanford.edu/browse/ECS-847, a bunch of the fields can remain stuck in an alarm state indefinitely, even if the alarm is cleared. This can leave a lot of phantom errors that aren't real.
3. Today, I heard that this perma-alarm was upsetting people.
Due to the nature of the bug, the alarm states clear when the associated value updates.
One setting I can easily change in these widgets is to drop the alarm widget from checking all normal signals to only checking hinted signals. Typically, this is just …
> ENH: set alarm config to hinted only for beckhoff motors

- docs/source/upcoming_release_notes/1189-flow-switch.rst
- pcdsdevices/digital_signals.py
- pcdsdevices/pim.py
- pcdsdevices/slits.py
- pcdsdevices/sxr_test_absorber.py
- pcdsdevices/wfs.py
- added new module digital_signals.py
- added new class `J120K`
- added `J120K` to `SxrTestAbsorber`, `XPIM`, `IM2K0`, `PowerSlits`
- created new class `PPMCoolSwitch`, `WaveFrontSensorTargetCool`
Where all devices in the happi database will get the cooling switch added `J120K` to the class. For devices who otherwise aren't all the same I inherited the base class. 
- Opened typhos screen from happi database where class name didn't change with local python environment and checked for flow_ok signal
- Opened typhos screens with manual module declaration where class name was different than happi database.
- All screens opened correctly.
- Opened a hutch python session with local python module and checked flow switch property reports:
-  `In [8]: sw.flow_switch.get_flow_ok`
-  `Out[8]: 1` …
> Add j120k flowswitch, insert flow switch in appropriate classes.

- pcdsdevices/signal.py
- pcdsdevices/tests/test_signal.py
The ``.set()`` method on the MultiDerivedSignal class accepts and documents the *settle_time* and *timeout* arguments. At the end of ``set()``, ``utils.set_many`` is used to do the actual work, however the *timeout* and *settle_time* arguments are not included.
This change will make the ``set()`` method's behavior consistent with its documentation and how other signal classes' ``set()`` methods work.
I wrote a test and included it in the test suite. I also tried this at my beamline on real hardware.
No change. The documentation was correct, but the behavior was inconsistent with the documentation.
> *settle_time* and *timeout* arguments on MultiderivedSignal.set()

- docs/source/upcoming_release_notes/1198-Modifying_Exit_Slits.rst
- pcdsdevices/slits.py
The new exit slits unit is installed and it has two functional piezo motors.
Added the two piezo motor to the ExitSlit class
yes, followed the confluence page
> ENH: Added the piezo pitch motor to the exit slits

- docs/source/upcoming_release_notes/1184-Add_opcpa_LXT_motor.rst
- pcdsdevices/lxe.py
PR to add a class supporting the new OPCPA laser locker system. This is essentially a copy-paste of the old class, with new PVs, to keep a consistent user interface for the operators. 
I _would_ like to remove the notepad PV setup at some point, because I plan on having a user offset built in to the IOC eventually, but for now it's not there so I'll leave that in. Future PR. 
closes #1184 
Tested on the OPCPA system in the laser hall this weekend.
Comments in the code, with some testing details here: https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=407260134
> ENH: Add OPCPA lxt class

- docs/source/upcoming_release_notes/1206-var-cool.rst
- pcdsdevices/mirror.py
- pcdsdevices/tests/test_mirror.py
Adds variable for activating variable cooling on:
`MR1L0`
`MR2L0`
`MR1L1`
`MR1K4`
`MR1K3`
`MR2K3`
in classes:
`XOffsetMirrorStateCool`
`XOffsetMirrorNoBend`
This currently covers all known mirrors that will receive variable cooling.
Added new test for cooling on offset mirrors: `test_mirror_cooling` in `test_mirror.py`
24V Solenoid water cooling valves installed on listed mirrors.
Currently have tested all valves via the Beckhoff IO.
Pulled up typhos screen for `MR1K4`. Output button appeared as expected. Toggled variable cooling. See screenshot below.
https://jira.slac.stanford.edu/browse/ECS-1410
> Add variable cooling

- docs/source/upcoming_release_notes/1201-modify_sp1k4-att_RTD_PV_to_match_the_prefix_SPEC.rst
- pcdsdevices/spectrometer.py
Remove SPEC:RTD:01:TEMP to RTD:01:TEMP
att_rtd_01 = Cpt(PytmcSignal, ':RTD:01:TEMP', doc="solid attenuator 01 PT100", io='i', kind='normal')
att_rtd_02 = Cpt(PytmcSignal, ':RTD:02:TEMP', doc="solid attenuator 02 PT100", io='i', kind='normal')## Motivation and Context
because sp1k4 has pre-fix TMO:SPEC, if I add SPEC here, then it will look for TMO:SPEC:SPEC:RTD:01:TEMP_RBV
yes, test it in python 
In [1]: from pcdsdevices.spectrometer import TMOSpectrometer
In [2]: ts=TMOSpectrometer('TMO:SPEC', name='sp1k4')
In [4]: ts.att_rtd_01.get()
Out[4]: 19.41
> modify sp1k4 rtd

- pcdsdevices/lic_2d_tmo.py
Create LI2K4 state mover GUI
Scientists insist to have the screen
yes, test the screen locally by command:
pcds-5.8.2) [tongju@psbuild-rhel7-01 pcdsdevices]$ typhos 'pcdsdevices.lic_2d_tmo.TMOLaserCouplingTwoDimention[{"prefix":"LI2K4:IP1"}]'
/cds/group/pcds/pyps/conda/py39/envs/pcds-5.8.2/lib/python3.9/site-packages/trio/_core/_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
warnings.warn(
[2024-03-26 14:40:11] - INFO - Loading 'pcdsdevices.lic_2d_tmo.TMOLaserCouplingTwoDimention[{"prefix":"LI2K4:IP1"}]' ...
[2024-03-26 14:40:12] - INFO - Loading Tools ...
[2024-03-26 14:40:12] - INFO - Adding devices ...
[2024-03-26 14:40:14] - INFO …
> lisK4-ip1 gui

- docs/source/upcoming_release_notes/1204-Add_embedded_gui_for_beckhoff_axis_with_custom_eps_screen.rst
- pcdsdevices/ui/BeckhoffAxisEPSCustom.embedded.ui
Added 'embedded' ui file for motors that have custom eps screens.
Adding the 'embedded' file allows for typhos screens to open using the compact controls.
> [ENH]: Add embedded gui for beckhoff axis with custom eps screen

- docs/source/upcoming_release_notes/1214-SmarAct_Updates.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/happi/containers.py
Introduced a new device under `pcdsdevices/epics_motor.py` that bundles two stages together for a tip-tilt mirror arrangement: `SmarActEncodedTipTilt`. Just specify this device in your HAPPI entry to use it!
Added the following PVs from `ioc/common/smaract/R1.0.20` and newer to all SmarAct devices:
1. `channel_temp`
2. `module_temp` 
Added the following PVs from `ioc/common/smaract/R1.0.19` to `SmarAct` encoded devices as hidden configs:
1. `log_scale_offset`
2. `log_scale_inv`
3. `def_range_min`
4. `def_range_max`
Note: These PVs will timeout and hang if you have not updated your child IOC to these releases. For best results, use `ioc/common/smaract/R1.0.21` which corrected some off-by-one bugs and missing archiver items.
Trying to bring the screens up to date with the latest IOC …
> SmarAct updates

- docs/source/upcoming_release_notes/1216-Fixing_Tpr_Bug_For_MultiDerivedSignals.rst
- pcdsdevices/tests/test_tpr.py
- pcdsdevices/tpr.py
Changed _get_delay, _get_width, and _put_last in tpr.py to signals elements instead of attrs elements as keys for items, since it maps from signal objects to values, not the names of signals
https://jira.slac.stanford.edu/browse/ECS-5093
Interactively, I made a tpr object and manually called the calculate_on_get/put functions for delay and width to make sure they gave the right values and didn't throw errors
Pre-release notes made
> BUG: Tpr ns_delay throwing error

- docs/source/upcoming_release_notes/1219-bug_lp_thread_overschedule.rst
- pcdsdevices/attenuator.py
- pcdsdevices/interface.py
- pcdsdevices/lodcm.py
- pcdsdevices/mirror.py
- pcdsdevices/tests/test_mirror.py
Summary: In the case where the mirror is not initialized, prevent pcdsdevices from scheduling a task every time lightpath_summary is updated.  
https://jira.slac.stanford.edu/browse/ECS-5186
In some more detail: 
We encountered a case where `XOffsetMirrorXYState` would never initialize, so every call to `._get_insertion_state()` would try to schedule a retry thread.  This helper method gets called whenever `lightpath_summary` updates, so for a quickly changing set of `lightpath_cpts`, this would create threads until we hit the limit.  This isn't a problem if the IOC is properly responding, but we can make failure here less catastrophic
`LightpathMixin._retry_lightpath` seems to be a vestigial attribute I reclaimed for this PR.  It was used in the legacy lightpath behavior, for a similar …
> BUG: Prevent lightpath logic from over-scheduling threads

- docs/source/upcoming_release_notes/1221-rtds_and_cooling_readouts.rst
- pcdsdevices/mirror.py
- pcdsdevices/spectrometer.py
- `XOffsetMirrorNoBend` in mirror.py gets 3 new cooling readout components.
- `Mono` in spectrometer.py gets 4 new RTD components and re-named RTDs 1-8. Make cooling component names consistent with mirror cooling component names.
- Wired up cooling panel sensors.
- Found new information about the RTD positions on SP1K1 MONO.
- Ran typhos screens locally.
https://jira.slac.stanford.edu/browse/ECS-4588
> TXI Mirror Cooling, SP1K1 Mono RTDs

- .github/workflows/standard.yml
- docs/source/upcoming_release_notes/1223-bld_unpin_numpy.rst
- Unpins numpy in CI
Numpy was previously pinned due to a numba build not yet existing.  This was pinned in https://github.com/pcdshub/pcdsdevices/pull/1100
through CI in theory
This PR
> CI: unpin numpy in CI

- docs/source/upcoming_release_notes/1226-bug_tprtrigger_fcpt.rst
- pcdsdevices/tpr.py
Fills the requested kwarg in a FormattedComponent of `TprTrigger`
Closes #1225
Interactively
```python
In [1]: from pcdsdevices.tpr import TprTrigger, TimingMode
In [2]: trig0 = TprTrigger('LAS:LHN:TPR:02', name='trig0', channel=00, timing_mode=TimingMode.LCLS2)
In [3]: trig0.connected
Out[3]: True
```
This PR
> BUG: fully fill formatted kwargs in TprTrigger.ns_delay_scan

- docs/source/upcoming_release_notes/1188-update_ebara_eva_class.rst
- pcdsdevices/pump.py
The ebara EVA pump was missing the pv to reset alarm errors
Need to ad the pv to the engineering screen
yes, followed steps in this confluence page https://confluence.slac.stanford.edu/display/PCDS/How+to+add+a+device+to+pcdsdevices#Howtoaddadevicetopcdsdevices-Adddocumentation,please!
> FIX: added signal to reset pump for the EVA

- docs/source/upcoming_release_notes/1230-tst_entrypoint_312.rst
- pcdsdevices/tests/test_entrypoints.py
closes #1229 
Entry point functional API changed back in 3.10, but the default used changed in 3.12.  Adjusts our tests to account for this.
CI
#1229
> TST: backcompat new py3.12 entrypoint types

- docs/source/upcoming_release_notes/1228-fix_ims_set_current_position.rst
- pcdsdevices/epics_motor.py
In the `IMS` class and in similar motor classes, `set_current_position` had a bug where it would refuse to let you set a position that is outside of the limits span.
See https://jira.slac.stanford.edu/browse/ECS-5354
This has been fixed by replacing the deprecated `set_and_wait` call (which threw a warning) with a `put(x, force=True)`, which ignores the limit. This is followed by a manual confirmation because `put` doesn't return a status object and the waiting doesn't work anyway for these specific devices (hence the special function override). I would have preferred to do something like `set(x, force=True).wait(timeout=1)` but `set` doesn't currently support the `force` kwarg. I think this is also a bug, but one I'm less motivated to look into. …
> FIX: IMS class set_current_position limits issue

- docs/source/upcoming_release_notes/1232-Set_delay_setpoint_and_width_setpoint_as_TprTrigger_configuration_attrs.rst
- pcdsdevices/tpr.py
Change TprTrigger `width_setpoint` and `delay_setpoint` to configuration attributes. 
Closes #1232 
Threw in `delay_setpoint` for good measure. 
Tested interactively on a channel in the laser hall. 
This PR.
> Update width and delay setpoints to "config".

- docs/source/upcoming_release_notes/1224-Move_VBAS_and_VMAX_into_PCDSMotorBase,_change_SmarAct_parent_class.rst
- pcdsdevices/epics_motor.py
Moves VBAS and VMAX signals to PCDSMotorBase for access by more sub-classes. 
Change SmarAct to use PCDSMotorBase. 
Closes #1224 
Tested using the same test motor @aberges-SLAC had in his submitted issue. 
This PR.
Typhos suite of that motor with "omitted" signals also shown.
> Add VBAS and VMAX signals to PCDSMotorBase

- docs/source/upcoming_release_notes/1241-Add_default_TprTrigger_timing_mode.rst
- pcdsdevices/tpr.py
Make LCLS2 the default timing mode for the `TprTrigger` class. 
closes #1241 
Tested interactively. 
This PR.
> Add TprTrigger default timing mode

- docs/source/upcoming_release_notes/1238-Add_SmarActPicoscale.rst
- pcdsdevices/epics_motor.py
Added a SmarActPicoscale device as a subclass of SmarAct in `pcdsdevices.epics_motor`. This pulls some Picoscale specific PVs to the display that are necessary for debugging. 
The Out of Loop Mechanical Delay Lines use the Picoscale interferometers and sensor heads for the position encoding in their systems. Picoscale has it own quirks that will render the stages inoperable if violated (i.e. beam interrupted). This is not transparent to the user in the current SmarAct device class. This new subclass of a device brings the necessary diagnostic information forward.
Closes: https://github.com/pcdshub/pcdsdevices/issues/1238
I tested this screen on a currently deployed stage in the FTL and was able to retain normal functionality of the SmarAct and read the Picoscale specific PVs. 
I did the …
> Add SmarAct Picoscale device

- docs/source/upcoming_release_notes/1243-overwrite_SQR1Axis_set_method.rst
- pcdsdevices/sqr1.py
to make it work with Bluesky multi axis scan
overwrite SQR1Axis set method to avoid waiting and setpoints synchronization
James Cryan reported an issue with Bluesky scan which happens with multi-axis scan (i.e.  zigzag scan)
when a Bluesky multi-axis scan starts only one motor moves.
https://jira.slac.stanford.edu/browse/ECS-5539
This modification tested on TMO LAMP SQR1 using hutch-python
I did the test using pcds conda 5.8.4 on TMO LAMP SQR1
> pcdsdevices/sqr1.py: overwrite SQR1Axis set method

- docs/source/upcoming_release_notes/1245-fix_fzp_att_state_count.rst
- pcdsdevices/spectrometer.py
See title
The fzp attenuator lost two targets due to space concerns and this new state count had not propagated down to the Python code. I made the required change here.
There are some confusing errors if the state count doesn't match. This is probably also something to fix.
Ming Fu says he can move the device again
Will make brief pre-release notes
> FIX: drop tmo fzp att from 6 states to 4 to match plc update

- docs/source/upcoming_release_notes/1247-optics-cooling.rst
- pcdsdevices/mirror.py
- MR4/5K4 are the only 2 devices using `FFMirrorZ`. Each mirror has 1 physical flow meter and shares the same physical pressure meter.
- MR1K4 bender is not used, cabled, or supported on the beckhoff DIN rail. Make a new class to get the dead bender readouts off the typhos screen. `XOffsetMirrorStateCoolNoBend`
- Installed cooling sensors
- removed MR1K4 bender beckhoff motor terminal.
- launched typhos screens from this branch.
https://jira.slac.stanford.edu/browse/ECS-903
https://jira.slac.stanford.edu/browse/ECS-5569
> TMO Cooling Sensor Updates MR1/4/5K4

- docs/source/upcoming_release_notes/1248-DOC:ST1K4_decoupling_ST3K4_when_ST3K4_OUT.rst
- pcdsdevices/sxr_test_absorber.py
remove st3k4 auto error so that it will not show error when st1k4 is not flowing st3k4 when st3k4 is OUT
remove error message lines
Do not give error while st1k4 is not out when ST3K4 is OUT
Test it in tmo under dev_conda. It works as expected. 
Dev_conda
(https://jira.slac.stanford.edu/browse/ECS-5586)
> removing st3k4 auto error

- docs/source/upcoming_release_notes/1254-Newport_velocity_PV_fixes.rst
- pcdsdevices/epics_motor.py
The signals for velocity-max (VMAX) and velocity-base (VBAS) were added recently to the EpicsMotorInterface class, but do not connect for the Newport class, causing issues. The proposed changes overwrite these signals to make them compatible with the Newport IOC.
The Newport Epics Motor Record does not have PVs for VMAX and VBAS, but they are expected by the Newport device in hutch-python, as defined in class EpicsMotorInterface. This causes a timeout/crash when calling a Newport device in hutch-python.
We tested the changes in the MFX hutch-python, which uses the dev version of pcdsdevices. We were able to control the Newport motors again without errors.
> fix for Newport for velocity-max and velocity-base

- docs/source/upcoming_release_notes/1244-maint_minor_ui.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/ui/BeckhoffAxis.embedded.ui
- pcdsdevices/ui/BeckhoffAxisEPSCustom.embedded.ui
- pcdsdevices/ui/StatePositioner.embedded.ui
- pcdsdevices/ui/TwinCATStatePositioner.embedded.ui
- Replace the "disabled" broken setpoint widget with a simple bitmask clicker
- Tweak the positioner layouts to enable them to be expandable
- I went through all the options for disabled/DISP and this one looked the least bad
- Minor tweaks based on things I noticed while implementing https://github.com/pcdshub/typhos/pull/611
The other option that sort of worked for the disabled widget was simple text entry but:
- This had the unit attached (0mm is off, 1mm is on...)
- It was awkward to know to type 0 or 1
I couldn't get typhos to assign a custom enum combobox to this widget. There was an option to have two vertical buttons to click but I didn't like it.
Here only, I need to make pre-release notes
Old "disabled" widget (completely inoperable):
New "disabled" widget: …
> MAINT: minor positioner ui tweaks

- docs/source/upcoming_release_notes/4500-Add_motor_class_for_MEC_hexapod_axis.rst
- pcdsdevices/epics_motor.py
Added PI_M824 motor class into epics_motor.py. Modified _getMotorClass to allow PVs with 'HEX' match with available motor types. Added doc string to Motor Class.
https://jira.slac.stanford.edu/browse/ECS-4500
Created a ipython instance and ran:
```
In [1]: from pcdsdevices.epics_motor import Motor
In [2]: m = Motor(prefix='MEC:HEX:01:Xpr',name='tc_hexapod')
In [3]: print(m)
PI_M824(MEC:HEX:01:Xpr, name=tc_hexapod)
In [4]: m.tweak()
tc_hexapod: -1.3220, scale: 0.1
```
> Added PI_M824 motor class for MEC hexapod motors.

- docs/source/upcoming_release_notes/1256-Add_new_source_lines_to_BTMS_and_BTPS.rst
- pcdsdevices/lasers/btms_config.py
- pcdsdevices/lasers/btps.py
- pcdsdevices/ui/btps-camera-summary.ui
- pcdsdevices/ui/btps-overview.ui
- pcdsdevices/ui/btps-source-tabs-config.ui
- pcdsdevices/ui/btps-source-tabs.ui
- pcdsdevices/ui/btps.ui
Update BTMS code to support new bay 2/bay 3 source lines
Update BTPS screens to support new bay 2/bay 3 source lines
Closes #1256 
Tested interactively on the system.
The code, this PR, and (soon) Confluence
New BTPS Screen: 
New BTMS Screen (with supporting updates in this PR: https://github.com/pcdshub/btms-ui/pull/12):
> BTMS/BTPS Updates

- docs/source/upcoming_release_notes/1205-Add_MSTA_field_and_homed_status_to_EpicsMotorInterface.rst
- pcdsdevices/epics_motor.py
Adds in an EPICS signal to bring the the motor MSTA bits. This signal is used to create a dictionary of interpreted values, as well as a "homed" property. 
I would like to implement some automated homing on some finicky motor stacks. I need a way to check that the homing routine has completed.  
Tested live on one of the stages of interest (a SmarAct linear stage). 
This PR. 
Live session (standard motor record):
IMS Motor:
Newport Motor:
> ENH: Add MSTA Bits

- docs/source/upcoming_release_notes/1261-Fix_mis-match_of_LS3_and_LS4.rst
- pcdsdevices/lasers/btps.py
Fixes a mis-match between LS3 and LS4 in the BTMS/BTPS. 
Closes #1261 
Tested on the stages in the laser hall. 
This PR.
> Swap LS4 and LS3 on the BTPS/BTMS to match real mapping.

- docs/source/upcoming_release_notes/1264-Make_SourcePosition_cameras_more_flexible.rst
- pcdsdevices/lasers/btms_config.py
Adds new methods to return the defined happi database names for the cameras in each bay. Updates existing methods to get camera prefixes. This PR extends the flexibility of the existing implementation and adds some new properties while being backwards compatible. 
closes #1264 
Tested interactively using the BTMS in the laser hall. 
This PR, and a related PR on pcdshub/btms-ui.
> ENH: BTMS Camera Updates

- docs/source/upcoming_release_notes/1272-2d-states.rst
- pcdsdevices/mirror.py
Implements a `TwinCATMirrorStripe` with 2D state movers and 4 positions to support MR1L0. This mirror implements 2 Dimensional state mover with 4 positions and PMPS. 2 of the positions are meant to send beam to TXI and are currently invalidated. 
- Add new class `MirrorStripe2D4P` derived from `TwinCATMirrorStripe`
- Add new class to implement `MirrorStripe2D4P`: `XOffsetMirror2D4PState`
- MR1L0 will send beam to TXI and thus the coating and pitch define a single state. 
- Ran PLC program and ensured PMPS parameter neVRanges were loaded according to definitions in the database.
- Ran State position movers from epics and ensured mirrors travel to desired positions.
- Loaded a local copy of pcdsdevices and launched the typhos screen.
- Set state positions from typhos and ensured the mirror …
> Offset Mirror with 2D State Movers and PMPS.

- conda-recipe/meta.yaml
Use bluesky-base in conda recipe instead of bluesky to avoid qt6-main
NOTE: this will require a change in the conda-feedstock.  Without this other packages will fail by installing qt6 dependencies
N/A
This PR.
> BLD: use bluesky-base instead of bluesky(all)

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/1281-bld_lightpath_base.rst
- requirements.txt
- Swaps `lightpath` -> `lightpath-base` in conda recipe
- Specifies >1.0.5 for both, to ensure pypi builds pull from version with GUI extras separated
- Conda builds will fail until the feedstock updates, but I figured it's better to keep the version numbers the same
Stop depending on things we don't need!
go CI go
This PR
> BLD: depend on lightpath-base to avoid ui dependencies in builds

- docs/source/upcoming_release_notes/1287-fix_lowercase_error.rst
- pcdsdevices/tmo_ip1.py
Change state_count from 7 to 8 to add OUT position
Fix the last target name lower case issue. All other targets are uppercase in the GUI
yes, it works now. attach picture here.
https://jira.slac.stanford.edu/browse/ECS-4824)
> adding OUT state in pcdsdevice so that the last target name will be override by uppercase Letter

- docs/source/upcoming_release_notes/1290-rix-states.rst
- pcdsdevices/mirror.py
- pcdsdevices/spectrometer.py
- add `MonoGratingStates` Class for use in `Mono`.
- add `grating_states` to `Mono` in `spectrometer.py` for `SP1K1`
- add `coating` to `XOffsetMirrorSwitch` for `MR1K2`
- add `MirrorStripe2D2P` for use in `XOffsetMirrorBend`
- add `coating` to `XOffsetMirrorBend` `for MR1K1`
rix request state movers and PMPS for X-Ray Optics
- Launched all typhos screens and moved between states
https://jira.slac.stanford.edu/browse/ECS-936
> Add state support for MR1K2, SP1K1, and MR1K1

- docs/source/upcoming_release_notes/848-create_new_VCNOpenLoop_device_class.rst
- docs/source/upcoming_release_notes/848-create_new_VFV_device_class.rst
- pcdsdevices/valve.py
Added VCN_OpenLoop device class to pcdsdevices valve.py. VCN_OpenLoop uses VCN as a template w/ the removal of 'open' and 'position_readback' commands. The 'state' member vairable has been renamed to 'control_mode' and the associated doc string was been updated.
https://jira.slac.stanford.edu/browse/ECSENG-848
Used Typhos to check if device would load correctly.
> Added new VCN_OpenLoop device class

- docs/source/upcoming_release_notes/1292-recoving_sp1k4-att_targets.rst
- pcdsdevices/spectrometer.py
SP1K4-ATT targets change from three targets to five targets so I need to update the devices
Change state count from 4 to 6
Scientists add target 4 and 5 back after swapping hardware
> recover sp1k4-att target from 3 to 5

- docs/source/upcoming_release_notes/1293-enh_tmo_mpod_apalis_hotfix.rst
- pcdsdevices/mpod_apalis.py
- pcdsdevices/tests/test_mpod_apalis.py
Add the following components to `MPODApalisChannel`:
- `desc` signal: Description of the mpod channel, used to configure what gets showed on the screen and to check the description during experiments.
- `last_voltage_set` signal: The setpoint of the MPOD channel, again. When we `put` to the `voltage` signal it also uses the setpoint PV, but having this as a separate signal lets you quickly see what the last value set was, and compare it to the apparent readback voltage of the channel. This is aliased to `voltage_setpoint` for some dev-time backwards compatibility for tmo. The new name is more clear.
- `is_trip` signal: `True` if the channel is tripped, which is helpful for some recovery automation and error reporting.
- Add long docstrings in various places to explain how signals are …
> ENH/FIX: apply TMO's mpod apalis hotfixes, adding features and fixing a major bug

- pcdsdevices/signal.py
Subclassed AvgSignal in order to allow averaging of a signal within a bluesky scan.
Sometimes there are cases where one wants to average a signal before moving to the next scan point.
Tested in xcs3 using 'XCS:SND:DIO:AMPL_8' wave8 signal, with the following test:
```
d1 = AvgSignalTriggered(EpicsSignalRO('XCS:SND:DIO:AMPL_8'),120,1,name='d1')
RE(scan([d1],sim.fast_motor1,0,120,num=11))
Transient Scan ID: 1     Time: 2024-10-11 12:23:24
Persistent Unique Scan ID: '567b8720-03ad-4ed6-a837-5effa5ac3058'
New stream: 'primary'
+-----------+------------+-------------+------------+
|   seq_num |       time | fast_motor1 |         d1 |
+-----------+------------+-------------+------------+
|         1 | 12:23:25.8 |           0 |      0.833 |
|         2 | 12:23:26.8 |          12 |       0.21 | …
```
> Add triggered signal

- docs/source/upcoming_release_notes/1297-avgsignal_trigger.rst
- pcdsdevices/signal.py
- pcdsdevices/tests/test_signal.py
- Take the features implemented by @mseaberg in #1297 and pull them into the parent class.
- Refactor the original class slightly to make `reset_buffer` usable directly.
- Fix some old documentation issues and add type annotations
- Add unit tests
- The features in #1297 are useful and fit seamlessly into the main class, this consolidates the similar features in one place.
- Avoids the small oddity of setting the average count back to itself in order to reset the buffer
- I like type annotations
- Unit tests protect us against regressions
- I added unit tests
- I redid the tests Matt did in xcs in #1297 and had similar results.
- I added release notes
> ENH: merge AvgSignalTriggered into AvgSignal

- docs/source/upcoming_release_notes/1274-Adding_base_class_for_hxr_diffractometer..rst
- pcdsdevices/gon.py
- Tiny tweaks to `HxrDiffractometer`'s documentation to make it more like other devices
- Remove the nearly no-op init method. Note that the original init method made it so you could pass in `name` as a position argument which is intentionally not allowed in most ophyd devices, this feature is removed.
- `HxrDiffractometer` was added in #1274
- I forgot about this and rediscovered it during https://jira.slac.stanford.edu/browse/ECS-6333 since it's in xpp3 as a hotfix
- When evaluating the hotfix, I made a mental note of a few edits to make while submitting the hotfix
- I saw that it was already here so I applied the changes I intended in pcdsdevices
- I also cleaned up the language in the pre-release notes (for example, this isn't a base class, it's just a device, and other minor …
> MNT: clean hxr diffractometer

- docs/source/upcoming_release_notes/1301-enh_config_las_timing.rst
- pcdsdevices/lxe.py
- pcdsdevices/tests/test_lxe.py
- Add cxi3's `invert` argument for `LaserTiming` that allows them to un-invert their laser timing device.
- Add init-time configuration of the `LaserTiming` limits so cxi3 doesn't need to override the class limits
- Add the above to `Lcls2LaserTiming` too while I'm here
- Ignore cxi3's other hotfix- it isn't actually needed to achieve these
- Apply cxi3's hotfix so they don't have to run out of dev in the future
- Add limit handling for the same reason
- I made unit tests
- I made pre-release notes
> ENH: las timing configurables (cxi3 hotfix)

- docs/source/upcoming_release_notes/1303-PowerMeter_responsivity_update.rst
- pcdsdevices/custom_units.py
- pcdsdevices/pim.py
- pcdsdevices/tests/test_units.py
- pcdsdevices/utils.py
Changing responsivity io to be input only so it displays without a connection error
Renaming manual pvs to be less similar to auto background pvs
Adding microjoule mirror of calibrated_mj
Added manual collection in progress indicator
Replaced references to passive mode with auto mode
https://jira.slac.stanford.edu/browse/ECS-875
Interactively
upcoming-release notes
> PPM Screen Changes

- docs/source/upcoming_release_notes/1304-chin-rtds.rst
- pcdsdevices/mirror.py
- add mirror sensor component to `KBOMirrorHE`
- this will affect:
```
| name             | mr3k2_kbh
| name             | mr4k2_kbv
| name             | mr2k4_kbo
| name             | mr3k4_kbo
```
All tested locally.
- RTDs installed on mirror
- ran locally and launched screens
https://jira.slac.stanford.edu/browse/ECS-6616
https://jira.slac.stanford.edu/browse/ECS-6705
> Add mirror sensors to KBOMirrorHEStates

- docs/source/upcoming_release_notes/1305-Adding_one_more_target_into_TM1K4.rst
- pcdsdevices/atm.py
target number changes from 8 to 9
TMO laser scientists put a new paddle and it holds 9 targets instead of 8.
GUI works already.
https://jira.slac.stanford.edu/browse/ECS-6744
> adding one more target for TM1K4

- docs/source/upcoming_release_notes/1306-Fixing-imprecise-TPR-TICK-NS-constant.rst
- pcdsdevices/tpr.py
Changing TPR_TICK_NS from 5.384 to 70/13. 5.384 is imprecise enough to cause large errors in _get_delay used by TprMotor.readback.get() and TprTrigger.ns_delay.get().
#1302 
Interactively (The error was due to a misspelling)
> Fixing imprecise TPR_TICK_NS constant

- docs/source/upcoming_release_notes/1310-mr1k1-1d-state.rst
- pcdsdevices/mirror.py
In `mirror.py` change `XOffsetMirrorBend`, `coating` to `TwinCATMirrorStripe` for 1D motion.
MR1K1 suffered a catastrophic motor failure on its X axis, so it can no longer move in 2 dimensions.
launch the typhos screen for local environment and made test state move.
https://jira.slac.stanford.edu/browse/ECS-6792
> Change MR1K1 Coating State to 1d state mover

- docs/source/upcoming_release_notes/1311-tst_failing_on_pip.rst
- pcdsdevices/tests/conftest.py
- pcdsdevices/tests/test_attenuator.py
Fix an issue where one of the attenuator tests started failing in the pypi builds.
This is done by waiting a bit, so the background threads have time to update all the metadata etc. or whatever they're doing. The fake epics signals do similar background thread work to what the real epics signals do which causes issues sometimes that can be solved by waiting.
https://github.com/pcdshub/pcdsdevices/pull/1307#issuecomment-2518532901
The tests pass now.
I made a little utility function because it was simple to do and it may be used again.
Docstrings only
> TST: reproduce and fix pypi failures

- docs/source/upcoming_release_notes/1313-Improving_Qmini_spectrometer_GUI_and_adding_save_functions.rst
- pcdsdevices/lasers/qmini.py
- pcdsdevices/ui/QminiSpectrometer.detailed.ui
- pcdsdevices/ui/QminiSpectrometer.embedded.ui
Gave a face-lift to the Qmini embedded & (new) detailed screen(s) to better suit the needs of SRD in MODS.
Closes #1313 
Adds a shiny new save-spectrum feature so that scientists aren't tempted to disconnect the spectrometers and plug it into their laptops ;]
I've tested this in the pcds-5.9.1 environment and pretty extensively:
https://github.com/user-attachments/assets/fb2ba094-2165-40a2-9e9b-bd6075e3bb4e
In this PR and in the code!
> Improve Qmini spectrometer GUI

- docs/source/upcoming_release_notes/1317-perf_preset_loading.rst
- pcdsdevices/interface.py
- pcdsdevices/tests/sim_fast_presets/sim_fast.yml
- pcdsdevices/tests/test_interface.py
- pcdsdevices/tests/test_lens.py
Delays preset file reading until tab-completion has been attempted.  Stashes this information on the device instance itself.  This is not the default behavior, and you must opt into this by supplying the optional argument `defer_loading` to `setup_presets_paths`
Also tracks the modification time of the preset file on sync, making the `Preset` instance the source of truth to see if the presets need to be synced.
Presets have taken a very long time to load recently, and the first place to look is often file i/o.  This delays this as long as possible while attempting to preserve the behavior hutch scientists use: tab completion.
This has also been made optional.  Both `setup_presets_paths` and `Presets.sync()` now take an optional `defer_loading` argument, that if true will skip the preset …
> PERF: delay preset sync until tab completion / attribute access, track file desync

- docs/source/upcoming_release_notes/1319-bug_preset_error.rst
- pcdsdevices/interface.py
Makes Preset `Preset.device.wm_*` and `Presets.state` methods more tolerant of missing or uninitialized device positions.  
This changes the signature of the `wm_*` methods slightly to also return "Unknown" if the position cannot be resolved.  
closes #1236 
As these are autogenerated methods, it's a little harder to confirm that this return type change won't break downstream consumers.  At least within `pcdsdevices`, the only method that calls a `device.wm_*` method is `Presets.state`.  It's possible that some script very strictly requires the output of a preset to be a numeric, but if the position was uninitialized, those scripts would throw exceptions anyway (no return would be reached)
Checking that CI passes. 
By manually setting `device.postition` to `None` and seeing the output not …
> BUG: make Presets.status more tolerant of unknown/uninitialized positions

- docs/source/upcoming_release_notes/1329-SmarActTipTilt_update.rst
- pcdsdevices/ui/SmarActTipTilt.embedded.py
- pcdsdevices/ui/SmarActTipTilt.embedded.ui
Add the wrapper approach from SmarActEncodedTipTilt when adding PVs to layout objects. Technically more verbose, but more scalable?
Also adding line-edits for `step_size` signals without having to open the pop-up screen.
Laser folks pointed out a good point about the tip-tilts:
* The tilt axis affects vertical, and while the vendor defines positive = piezo pushes away from the rear mechanical end stop, this necessarily steers the beam down
* Users want to be able to dictate if the "up" button corresponds to the motion they expect on some detector that is monitoring the steering
* Periscopes make simple inversion of `STEP_FORWARD` and `STEP_REVERSE` complicated, and we don't want to be too granular.
Solution:
Added the `step_size` signals to the embedded screen so users could invert the …
> SmarActTipTilt updates

- docs/source/upcoming_release_notes/1327-LasBasler_User_Presets.rst
- pcdsdevices/areadetector/detectors.py
- pcdsdevices/ui/SmarActTipTilt.embedded.py
Added UserPresetSelector PVs for the default selector and current selector. This is a feature exposed in the gigecam IOC for Basler cameras that allows the user to save hardware settings to a preset for a given stream. There are also several factory settings available as well (high gain, color raw, etc.).
Changing `UserPresetDefaultSe` will load that preset upon `ARAVIS_RESET` commands.
Try to fix day-to-day operations pains for Laser folks as it will make restoring giges after planned/unplanned power cycling of cams much easier.
Also closes #1327 
Tested on pretty much every chemRIXS Basler in their MODS, and a few in TMO IP1.
In this PR and the code! See also https://jira.slac.stanford.edu/browse/ECS-4805 for quirks about how camera firmware messes with the behavior of these pvs due to …
> LasBasler User Presets

- docs/source/upcoming_release_notes/1329-SmarActTipTilt_update.rst
- docs/source/upcoming_release_notes/1331-SmarActTipTilt_invert_axes.rst
- pcdsdevices/ui/SmarActTipTilt.embedded.py
- pcdsdevices/ui/SmarActTipTilt.embedded.ui
1) Got rid of some text labels for the embedded screen to reduce footprint.
2) Added checkboxes for inverting the `tip` or `tilt` axes
3) Add logic to change which channel is assigned to which `pushbutton` for jogging the each stage. This lets the user functionally, and in real time, invert the directional pad to suit their needs/alignment/design.
Found a _neat_ ~~bug~~ feature in `pydm` when using `set_channel` sequentially on objects who may or may not have those channels set already. If you are re-assigning the channels on a pydm widget, explicitly set the channels to blank strings before proceeding or you _will_ have callback bugs.
Unfortunately #1329 did not fix the issue the Laser team presented, due to how the protocol file works in the common IOC. Turns out `asyn` doesn't do math, …
> SmarActTipTilt Invert Open-loop Axes

- docs/source/upcoming_release_notes/1334-Elliptec_slider_update.rst
- pcdsdevices/lasers/elliptec.py
Changed `channel` to be a mandatory arg in `EllBase` constructor for consistency in API usage. All our devices in the wild (as far as lasers are concerned) call the channel prop from their `happi` entry anyway. In `hutch_python` sessions this will now be more obvious to the user what information they need before device instantiation.
Also overloaded `done_comparator` to just use `readback` and `setpoint` methods if using `Ell6` or `Ell9`. No need to call a `numpy.isclose()` on `enums`.
Couple of JIRA tickets on user frustration and terminal spam when opening LUCID with `Ell6` or `Ell9` implemented. Easy fix for root causes. See ECS-7383 and ECS-7390.
Tested with the same sliders specified in the above tickets using the CRIX_MODS toolbar and LUCID. 2 birds, 1 stone: no terminal spam now …
> Elliptec updates for Sliders

- .github/workflows/standard.yml
- docs-requirements.txt
Though we unpinned numpy in the written requirements, we had a few straggling pins in the pip-testing extras and docs-extras
New Env time
CI
This PR, release notes maybe
> BLD: unpin numpy in pip test suite as well

- docs/source/upcoming_release_notes/1333-SmarAct_detailed_maintenance.rst
- pcdsdevices/ui/SmarAct.detailed.ui
Fixed a bad PV macro for `TTZ_THRESHOLD` setter. Originally both the `PyDMLabel` and `PyDMLineEdit` were set to `TTZ_THRESHOLD_RBV`. Fixed some aesthetics on size hints.
Noticed a setter didn't work out in the wild in TMO IP1, dug to find root cause and fixed it.
Tested in my dev branch on the offending IP1 motors.
In this PR
> SmarAct detailed screen maintenance

- docs/source/upcoming_release_notes/1332-enh_mpod_polarity.rst
- pcdsdevices/mpod_apalis.py
- pcdsdevices/tests/test_mpod_apalis.py
Sets channel limits based on the value obtained from `.max_voltage` and the model number from the parent module.
In response to TMO's recent troubles setting the voltage limits on the mpod channels.  Our previous application of the hotfix (#1293) only assumed positive definite voltage limits, and failed to cover the negative or bipolar channels.
According to James, the simplest way to grab this information is from the model number of the parent module.  All channels in a given module have the same polarity.
Also, it seems our approach to imposing limits on the MPOD channels is to monitor the max voltage PV and set the limits in python-land.  This was a bit misleading, and I'd like to document this more thoroughly (TODO)
Interactively, though tests will be added I swear.
This PR
> ENH: set mpod voltage limits based on parent module

- .github/CODEOWNERS
- .pre-commit-config.yaml
- pcdsdevices/lodcm.py
Update codeowners to use more verbose syntax
Codeowners files actually use fnmatch, not glob like we initially thought.  They also don't support some of the convenient syntax that .gitignore files use
I spammed pcds-ci-test-repo-python
This PR
> MNT: update codeowners filters to explicitly list extensions

- docs/source/upcoming_release_notes/1347-adding_targets_into_tm2k4.rst
- pcdsdevices/atm.py
Changing statemover count to 9 (including OUT)
Scientists require this.
Not yet because laser scientists want to test it later. This is for dream. 
Currently the state mover only shows 6 targets and we need 9 targets, so I need to complete this.
(https://jira.slac.stanford.edu/browse/ECS-7475)
(https://github.com/pcdshub/lcls-plc-tmo-motion/pull/148)
> adding tm2k4 targets to 8 from 6

- docs/source/upcoming_release_notes/1352-hide-pa1k4-targets.rst
- pcdsdevices/tmo_ip1.py
change state count from 8 to 6
Scientists make decision to make sure that it will not repeat again during beam time
(https://github.com/pcdshub/lcls-plc-tmo-motion/pull/149)
(https://jira.slac.stanford.edu/browse/ECS-7882?inline=true&decorator=dialog&_=1747152209196)
> pa1k4 hide 6 and 7

- docs/source/upcoming_release_notes/1357-mnt_presets_sync_2.rst
- pcdsdevices/interface.py
- pcdsdevices/tests/test_interface.py
Also sync presets when accessing the `presets.position` attribute
https://jira.slac.stanford.edu/browse/ECS-8086
James had a few scripts that were trying to check if presets existed before moving them.  Our deferred sync update broke this for him.
The desync test I have now syncs more aggressively, so one test has been adjusted.
This PR
> MNT: also sync presets when accessing presets.position (ECS-8086)

- docs/source/upcoming_release_notes/1375-sl2k4-colors.rst
- pcdsdevices/ui/SL2K4Slits.ui
Switched the indicator color and background for sl2k4 slits ui
https://jira.slac.stanford.edu/browse/ECS-8015
Requested by Tong/James
Interactively
Before
After
> switching sl2k4 slit colors

- docs/source/upcoming_release_notes/1376-add_new_targets.rst
- pcdsdevices/spectrometer.py
Scientists add four more targets
Change target number from 5 to 9
Scientists request it
Yes, I test it. I move from OUT to target 1 without any issue. Will ask scientists to move all of them later. 
https://jira.slac.stanford.edu/browse/ECS-8796
> update sp1k4-att targets from 5 to 9
