- pcdsdevices/epics/mirror.py
- pcdsdevices/sim/mirror.py
- tests/epics/test_mirror.py
- tests/sim/test_sim_mirror.py
Added soft limits to the mirrors along with accompanying tests. And as an added bonus, found the hidden sleep and silenced it, for good.. or until someone decides to re-enable it
> Soft Limits, tests, and the phantom sleep

- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/pim.py
- pcdsdevices/sim/mirror.py
- tests/epics/conftest.py
- tests/epics/test_mirror.py
- tests/sim/test_sim_mirror.py
Finally added docs for mirror and pim. Unified the interface differences between sim mirror, epics mirror and the tests but this means we need to change pswalker to match it.
> Docs for mirror and pim, beware the mirror API change

- pcdsdevices/epics/areadetector/base.py
- pcdsdevices/epics/areadetector/plugins.py
- pcdsdevices/epics/pim.py
- pcdsdevices/sim/pim.py
- run_tests.py
> ENH: Stage and unstage of stats2 and image1 for PIMPulnix.

- pcdsdevices/epics/attenuator.py
This is a device we needed for the alignment setup. This file looks gross because there are a lot of subtle difference between the fee attenuator and the rest of the attenuators, but there is also enough the same that it would be problematic to duplicate code. I'm sure this isn't perfect, but it's a start.
> ENH: Fee Attenuator

- .travis.yml
- requirements.txt
> FIX: Adding prettytable to requirements.txt

- pcdsdevices/epics/pim.py
- pcdsdevices/sim/pim.py
Image2 is still the viewer stream, so it's what I want to monitor for the skywalker gui.
> ENH: Include image2

- pcdsdevices/epics/slits.py
- tests/test_epics_slits.py
Added tests for slits methods as well as making lightpath compliant. Used an interesting schema to handle the strange-ness of the slits interaction with the beam. See the notes in the class doc-string.
> ENH: LightInterface for slits

- .travis.yml
- pcdsdevices/happireader.py
* Allow kwarg renaming / class specification in happi load
* Install mongomock / happi from conda so we can run the appropriate tests on Travis
> ENH: Flexible happi loading

- pcdsdevices/happireader.py
> FIX: Fix device creation with happi info

- docs/source/device.rst
- pcdsdevices/epics/__init__.py
- pcdsdevices/epics/mirror.py
- pcdsdevices/epics/mps.py
- pcdsdevices/epics/valve.py
- tests/test_mps.py
Add a base MPS device to summarize faults. Added this as a subcomponent of:
* GateValve
* Stopper (both kinds)
* OffsetMirror
Closes #41
> ENH: MPS Devices

- pcdsdevices/epics/mirror.py
- tests/test_epics_mirror.py
- tests/test_happi.py
Changes and tests for implementation of `BranchingInterface` for OffsetMirror
> ENH: Mirror branching

- .travis.yml
- pcdsdevices/epics/lodcm.py
- tests/test_lodcm.py
Please don't merge yet unless we need it fast, this branch still needs docs and tests.
This is the LODCM fit into the branching interface. It has achieved the minimal amount of features needed for lightpath while having room to expand the class in the future.
> ENH: LODCM

- pcdsdevices/epics/pim.py
"YAG" is not inserted
"OUT" mean removed
Live!
> FIX: Out means out

- .travis.yml
- conda-recipe/meta.yaml
- requirements.txt
There maybe be non backwards compatible changes in the happi directory soon. I locked the version number down until these are done.
Trying to avoid accidentally breaking things
Tested via Travis. Using the tagged happi build should be no different than using the current master
> CI: Use fixed happi version

- .travis.yml
The incorrect syntax was used, probably due to  a typo. I have changed the == to =.
https://travis-ci.org/slaclab/pcds-devices/jobs/308017828#L2468
Let travis take the wheel
.
> CI: Fix typo in travis env creation

- conda-recipe/meta.yaml
Typo in conda-recipe causes failure when building
Builds locally.
> BLD: Correctly specify happi version

- pcdsdevices/epics/mps.py
- tests/test_mpslimits.py
Not sure if the test file I added with it properly tests it... it passes the call of function for various values of the fault value
> MPS Limits

- .travis.yml
- README.rst
- conda-recipe/meta.yaml
- setup.py
pcds-devices -> pcdsdevices
Module name should not be different from the import name if the module is meant to be imported.
> API: Rename module

- pcdsdevices/pulsepicker.py
- pcdsdevices/state.py
- tests/test_pulsepicker.py
Picks the pulses, as a state positioner. I also expanded the features of the pvstate logic to accommodate the inout picker.
PP is relatively clean now. Brain is fried trying to debug, so I might have missed some things. There might be a subscription bug in `AggregateSignal`, but it seems to be very subtle... I might tackle it once we finish everything else unless it comes up again, in which case I'll tackle it sooner.
Passes tests
docstrings
> ENH: Picker

- pcdsdevices/device_types.py
- tests/test_device_types.py
Simple top-level namespace to avoid diving deep into the library:
```python
from pcdsdevices import device_types
slits = device_types.Slits("HX2:SB1:JAWS", name="HX2 Slits")
```
Add a simple test to ensure that we update this namespace if devices move around.
> ENH: Namespace

- pcdsdevices/beam_stats.py
- tests/test_beam_stats.py
> ENH: Add basic BeamStats

- pcdsdevices/attenuator.py
> FIX: typo in auxilliary stuck pv

- pcdsdevices/epics_motor.py
> FIX: IMS velocity has limits

- pcdsdevices/areadetector/detectors.py
- pcdsdevices/pim.py
- tests/test_pim.py
> MNT: Clean up ad detector classes

- pcdsdevices/lodcm.py
- Fix pv name for lom readback prefix
- `Cmp` -> `Cpt`
- It was broken
- Conventions are good
closes #231
Probably still passes tests
No real change
> FIX: Lom readback bug

- tests/test_mv_interface.py
So that Yesenia has something to test with for tweak 2d
> TST: Add a 2d motor for testing

- .travis.yml
- pcdsdevices/attenuator.py
- pcdsdevices/beam_stats.py
- pcdsdevices/epics_motor.py
- pcdsdevices/ipm.py
- pcdsdevices/lodcm.py
- pcdsdevices/mirror.py
- pcdsdevices/movablestand.py
- pcdsdevices/mps.py
- pcdsdevices/pim.py
- pcdsdevices/pulsepicker.py
- pcdsdevices/sequencer.py
- pcdsdevices/slits.py
- pcdsdevices/state.py
- pcdsdevices/valve.py
Added `Kind` specification to every Device in the library. 
I tried to keep a consistent methodology (mostly using `EpicsMotor` as a guideline), but happy to debate any specific signals that are in the wrong category. I'm taking a guess that most people won't care as almost all of them were in the wrong category before this PR 😄 
Closes #237
> MAINT: Kind

- pcdsdevices/attenuator.py
- pcdsdevices/mirror.py
- pcdsdevices/movablestand.py
- pcdsdevices/mps.py
- pcdsdevices/slits.py
- pcdsdevices/valve.py
Hit all the files in the main level. Did not touch sim or area detector, which need other reworking anyway.
> STY: standardize on Cpt

- pcdsdevices/mv_interface.py
Tweak base function created so Tweak function can be used to move one or two motors. 
Issue https://github.com/pcdshub/pcdsdevices/issues/174 
Tested using the TwoMotor class in the tests folder.
<!--- Why is this change required? What problem does it solve?
> Add Tweak_base and Tweak functions

- pcdsdevices/mv_interface.py
Once more, with feeling: through branch mishaps and whatnot, let's finally merge this in. Continuation of #258 thanks to @matthooverslac
> ENH: Add matt's ginput code

- pcdsdevices/attenuator.py
> FIX: att names no longer accumulate

- pcdsdevices/lens.py
Add a basic XYZ stack for the be lens alignment/calibration classes
This had to be done eventually, and is a good starting point for Matt and Yesenia to implement the xy calibration and spot size calculations respectively
This breaks flake8 but I want to put it in here anyway
> ENH: Lens stack starting point

- pcdsdevices/state.py
> FIX: check all invalid states, not just unknown

- pcdsdevices/sim.py
Some more testing classes, including a fake lens stack
> ENH: expand the sim classes

- pcdsdevices/lens.py
- pcdsdevices/mv_interface.py
- pcdsdevices/sim.py
- tests/test_mv_interface.py
Some code cleanup, some tests added, some bugs fixed. Not much changed in the way of functionality. I'm going to self-merge because Teddy is out, but we can revisit when he returns.
First step towards the next release. I don't want to release untested code now that I know how to properly test thinks like `mv_ginput`, `tweak`, etc.
I'm doing this myself rather than assigning it to Matt/Yesenia because it's my job to deploy this stuff. It isn't very instructive to levy out manifestos of style preferences.
Tests added
Some docstrings have been updated too
> MNT: Style cleanup

- .travis.yml
- tests/test_sequencer.py
- tests/test_signal.py
- Need to explicitly ask for python version in conda build
- Some changes for testing compatibility with newest ophyd (would not effect live devices)
Adding Teddy as a reviewer but merging without review since no code was changed
> CI: Fix travis

- pcdsdevices/attenuator.py
Zach wanted a separate FEE attenuator class
> FEE attenuator

- pcdsdevices/attenuator.py
- pcdsdevices/ipm.py
- pcdsdevices/lens.py
- pcdsdevices/lodcm.py
- pcdsdevices/mirror.py
- pcdsdevices/pim.py
- pcdsdevices/pulsepicker.py
- pcdsdevices/slits.py
- pcdsdevices/valve.py
A first pass at adding all symbols for lightpath devices. Happy to show these to anyone who wants to help me pick these. The good news is we can always adjust these at a later date.
Used to render symbols for the PCDS Lightpath after https://github.com/pcdshub/lightpath/pull/85
> MAINT: Add icons for lightpath

- pcdsdevices/inout.py
Did not properly heed @ZLLentz warning. Fixing docstring muddling.
> FIX: Ensure docstring extension is present post #289

- conda-recipe/meta.yaml
- docs/source/epics_types.rst
- pcdsdevices/device_types.py
- pcdsdevices/epics_motor.py
- pcdsdevices/pseudopos.py
- pcdsdevices/utils.py
- tests/test_pseudopos.py
Delay stage, fully generalized with real motor and delay motor units.
Laser delay etc etc
A single sanity test
Added to docs
> ENH: Delay stage

- pcdsdevices/lens.py
- pcdsdevices/mv_interface.py
- lens stack can't move to the exact limits in the real hardware
- tweak should catch and report motion errors without stopping
- tweak should announce that it is tweaking
I want to edit this some more but I'm putting it as a PR so I don't forget about it. These were the changes that Matt and I made to the Be lens axis calibration that made it work.
> FIX: Lens calibration edge cases

- docs/source/releases.rst
Oh boy, `1.0.0`. We haven't done a release in 4-5 months.
> DOC: v1.0.0 release notes

- .travis.yml
- Add a py37 build to the travis that is allowed to fail. It will fail until the dependencies allow py37.
- Nitpick the inconsistent spacing in the travis file
Bored on a friday night
> CI: add py37

- docs/source/releases.rst
> DOC: add release notes

- pcdsdevices/signal.py
Marginally safer than an if statement.
> MNT: use mod to wrap index

- pcdsdevices/analog_signals.py
- pcdsdevices/device_types.py
- tests/test_analog_signals.py
Added classes for new devices that can be read by happi with questionnaire backend (https://github.com/pcdshub/happi/pull/94).
Imported `PCDSDetector` in `device_types` (already defined in `areadector.detectors`).
Created new file `analog_signals` containing the class `Acromag` and started to include some mesh functions - also imported in `device_types`
Created file for testing `analog_signals` and started constructing tests - still a WIP.
> Add more qs devs

- pcdsdevices/signal.py
- setup.cfg
Add a clean error message instead of the ugly one that usually happens.
closes #347 
Hopefully the tests still pass, but I've interactively seen that this is enough to make it obvious what went wrong.
> MNT: Clean Error Message for #347

- docs/source/releases.rst
- pcdsdevices/epics_motor.py
Release notes for v2.1.0 to be released tomorrow (yay friday releases)
It's been almost 6 months since the last release and there are new things.
> DOC: Rel 2.1.0

- docs/source/releases.rst
Release requested by @ZryletTC to start using new vacuum classes in the field
> DOC: v2.2.0 release notes

- pcdsdevices/kmono.py
> DEV: added kmono.py

- docs/source/releases.rst
Added docs for new release. Probably too detailed.
> DOC: add release notes for v2.4.0

- pcdsdevices/valve.py
The altered field should be writable from the Typhos generated screens.
> BUG: VCN state must be write-able

- docs/source/releases.rst
Add docs for next feature release
Tag with bugfixes soon
> DOC: add v2.5.0 release notes to docs

- pcdsdevices/valve.py
In valve.py, added VFS class.
Valve Fast Shutter does not have an expert screen yet so this is the first version of it.
> DEV: In valve.py, added VFS class.

- pcdsdevices/valve.py
Fixed incorrect PV in FSV class.
In the FSV class, I used the incorrect PV for vac_fault_ok. Here is the fix.
> MNT: Updated valve.py, FSV class, vac_fault_ok PV to correct one.

- pcdsdevices/valve.py
Fixed string=True kwarg described in conversation of #465
> MNT: updated valve.py/classVFS/gfs_name with string=True

- docs/source/releases.rst
Tag will contain contributions from everyone listed as a reviewer
> DOC: release notes for v2.7.0

- pcdsdevices/pump.py
- pcdsdevices/valve.py
Updated VGC and PIPPLC with string=True.
Current these string entries show up as a graph.
> MNT: Updated VGC and PIPPLC with string=True.

- pcdsdevices/state.py
`omitted` -> `config` for state error reset
Change order in class so config is before omitted
Should not be hidden on the screen
> ENH: State Error Reset Kind

- pcdsdevices/lasers/qmini.py
Provides support for the RGB Photonics/Broadcom Qmini spectrometer. 
Adds support for a device we need. Generates reasonable Typhos screens. 
Tested using a spectrometer in the Heinz lab.
> Qmini Spectrometer

- pcdsdevices/slits.py
Lock the slits callbacks to not put to live PVs until there is a move request from this python object
Multiple inactive clients should not be putting to random PVs
> MNT: do not put to PVs until the user asks

- docs/source/releases.rst
Update the release notes page in advance of a tag
Tag is actually overdue at this point.
Reviewers are all commit authors since the last tag, plus people who reviewed at least one PR since the last tag.
> DOC: add release notes for v2.8.0

- pcdsdevices/attenuator.py
Pairs with https://github.com/pcdshub/hxr-attenuator caproto IOC work
<details>
<summary>attempt 1</summary>
</details>
> ENH: add initial attenuator calculator devices - separate from the motion components for now

- pcdsdevices/lasers/elliptec.py
Updated the elliptec classes to use formatted components to make dealing with some of the elliptec IOC PV weirdness easier. 
Restructured the code to clean up some of the screens. 
Added more docstrings. 
This fixes some of the components, and makes the screens cleaner.
Tested in on stages in the Heinz lab. 
Docstrings.
> Update Elliptec 

- docs/source/releases.rst
See title
Like always, I requested reviews from all contributors, as a notification that a release with your commits is being tagged soon.
> DOC: add v2.9.0 release notes

- pcdsdevices/lasers/thorlabsWFS.py
Adds in a new device for the Thorlabs WFS40 detector. 
This device is used in the laser control system. 
Tested using a WFS-40 in the B40 Heinz lab. The component PVs work, but Typhos hangs when attempting to create a screen. This appears to be related to the parent class PCDSAreaDetectorTyphos, rather than the WFS class, but that can be fixed in a different PR. 
It hasn't, outside of the source. However, I think the component names are pretty self-explanatory.
> ENH: Add support for Thorlabs WFS-40 detector

- docs/source/upcoming_release_notes/0529-mv-info.rst
- pcdsdevices/interface.py
Log what we're moving, where we're moving from, and where we're moving to in the `mv` family of functions.
- Tim said this would be helpful, and it seemed easy to implement.
- Will not spam during scans because those don't use `mv`
I moved some motors
> ENH: log calls to mv, umv at level info.

- docs/source/upcoming_release_notes/545-add_hutch.rst
- pcdsdevices/interface.py
- tests/test_interface.py
> MNT: add_hutch("preset") -> add_hutch_here("preset")

- .travis.yml
Attempt to update to the shared CI scripts (stopgap solution for docs build failure in #581)
> CI: update to pcds-ci-helpers shared scripts

- docs/pre-release-notes.sh
- docs/source/upcoming_release_notes/568-DelayBase_offset_support.rst
- pcdsdevices/pseudopos.py
- tests/test_pseudopos.py
* Add `set_current_position` and `user_offset` to `DelayBase`
Closes #568 
* Basic unit tests
* Interactively
* Docstrings
* Release notes
> ENH: DelayBase offset

- docs/release_notes.py
An uncoordinated simultaneous effort with a similar goal as #583
> DOC: release note extender

- docs/source/conf.py
Cleaned unused imports + sorted them (remnants from previous documentation attempts)
> CLN: isort / import fix

- pcdsdevices/gauge.py
Minor fix.
No other `RBV`-related read-only items found.
Closes https://github.com/pcdshub/pcdsdevices/issues/380
> FIX: RBV is read-only

- pcdsdevices/state.py
> FIX: ValueError typo

- docs/source/upcoming_release_notes/599-tmo-ccs.rst
- pcdsdevices/areadetector/detectors.py
- pcdsdevices/atm.py
- pcdsdevices/device_types.py
- pcdsdevices/epics_motor.py
- pcdsdevices/lic.py
- pcdsdevices/pim.py
- pcdsdevices/pmps.py
- pcdsdevices/ref.py
- pcdsdevices/state.py
- pcdsdevices/wfs.py
- tests/test_atm.py
- tests/test_lic.py
- tests/test_ref.py
- tests/test_wfs.py
- EPICS checkouts
- Commissioning utilities
Added super basic tests, opened all the typhos screens
Documented in-line
Added pre-release page
> ENH: L2SI CCs for use in TMO

- docs/source/upcoming_release_notes/311-valueerror_typo.rst
- docs/source/upcoming_release_notes/380-rbv_read_only.rst
- docs/source/upcoming_release_notes/511-at2l0_interface.rst
Fixes previous PRs where I neglected to follow protocol (oops...)
I think this is it - hopefully.
> DOC: missing release notes updates

- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/releases.rst
- add release notes using the script
- add a pre-merge-checklist to the issue template
I thought the API changes were enough to warrant a v3.0.0
As usual, reviewers are everyone who contributed to the tag.
> DOC: add release notes for v3.0.0

- docs/source/upcoming_release_notes/623-elliptec-update.rst
- pcdsdevices/lasers/elliptec.py
Various updates to the elliptec module to include new PVs added in recent IOC updates, as well as clean up the Typhos screens a bit. 
This will greatly improve these device's usability. 
Closes #623 
Tested on an Ell6, Ell14, and Ell20 in the Heinz lab. 
The code, some docstrings.
> MNT: Elliptec update

- docs/source/upcoming_release_notes/648-SmarAct-Steps.rst
- pcdsdevices/epics_motor.py
Changed SmarActOpenLoop total_step_count to read-only. Added some docs metadata. 
Closes #648 
Tested on a stage in the Heinz lab. 
The code, new docs.
> MNT: Change SmarActOpenLoop step count signal to RO.

- docs/source/upcoming_release_notes/649-Baser-Reset-PV.rst
- pcdsdevices/areadetector/detectors.py
Adds some new camera classes that deal with Basler-specific PVs. 
Closes #649, more details there. 
Tested on a camera in the Heinz lab. 
The code, docstrings, and some meta-data.
> ENH: Add new Basler camera classes, with Basler specific PVs.

- docs/source/upcoming_release_notes/654-Tuttifrutti-LasBasler.rst
- pcdsdevices/lasers/tuttifrutti.py
Changes the class for TuttiFrutti NF/FF cameras. 
This new class provides some features that we want for the Baslers. 
Closes #654 
Tested on a TuttiFrutti in the Heinz lab
The code, pre-release notes
> MNT: Update TuttiFrutti to use new camera class

- docs/source/upcoming_release_notes/662-MPOD_Channels.rst
- pcdsdevices/device_types.py
- pcdsdevices/mpod.py
- tests/test_mpod.py
Added a MPODChannel object. 
Trying to implement and close https://github.com/pcdshub/Bug-Reports-and-Requests/issues/50
Locally only.
Doctring.
> Mpod channels

- docs/source/epics_types.rst
- docs/source/upcoming_release_notes/664-Acromag_channels_prefixed.rst
- pcdsdevices/analog_signals.py
- pcdsdevices/device_types.py
- pcdsdevices/happi/containers.py
- tests/test_analog_signals.py
Added `AcromagChannelInput` and `AcromagChannelOutput` devices - they will help create an `Acromag` object per channel.
Still trying to figure out what to do here.....
Partially addresses https://github.com/pcdshub/Bug-Reports-and-Requests/issues/51
> Acromag channels prefixed

- docs/source/upcoming_release_notes/673-IPM_Custom_Status_Print.rst
- pcdsdevices/ipm.py
Override the status info handler. 
Trying to implement and close #673 
```
In [5]: i
Out[5]:
XPP SB2 IPM: Target 5 OUT
Target Position: 0.0 [mm]
IPIMB Diode Position(x, y): 0.1063, -45.9985 [mm]
```
Docstring
> ENH: IPM custom status

- docs/source/upcoming_release_notes/679-Mirrors_Custom_Status_Print.rst
- pcdsdevices/mirror.py
Add custom status print for `XOffsetMirror`, `OffsetMirror`, `KBOMirror`, `FFMirror`.
Tackling #679 
`XOffsetMirro`
```
In [1]: mr1l0_homs
Out[1]:
MR1L0:HOMS (LFE Mirrors)
------
x_up: (MR1L0:HOMS:MMS:XUP)
------
position: 201.148
user_setpoint: -201.071 [um]
description: Main.M3 / M1L0-Xup
------
pitch: (MR1L0:HOMS:MMS:PITCH)
------
position: 0.024583
user_setpoint: -0.000758 [urad]
description: Main.M5 / M1L0-Pitch
pitch_enc_rms: 0.029404574106026576
```
`OffsetMirror`
```
In [1]: xrt_m3h
Out[1]:
XRT:M3H (PBT)
------
pitch: (MIRR:XRT:M3H)
------
position: 98.99555206298828
setpoint: 99.0 [urad]
```
`KBOMirror`
```
In [1]: mr2k4_kbo
Out[1]:
MR2K4:KBO (TMO Mirrors)
------
x_up: (MR2K4:KBO:MMS:X)
------
position: 0.94904
user_setpoint: 0.948485 [mm]
description: Main.M7 / M2K4-X
------ …
```
> Homs custom status

- docs/source/upcoming_release_notes/740-status_print_checks.rst
- pcdsdevices/analog_signals.py
- pcdsdevices/attenuator.py
- pcdsdevices/gon.py
- pcdsdevices/ipm.py
- pcdsdevices/lens.py
- pcdsdevices/movablestand.py
- pcdsdevices/pim.py
- pcdsdevices/slits.py
- pcdsdevices/spectrometer.py
- pcdsdevices/utils.py
- pcdsdevices/valve.py
- tests/conftest.py
- tests/test_interface.py
Attempt to instantiate all fake devices and print status information.
Non-instantiable devices are skipped (about 13 classes).
* Status information has close to 0 test coverage
* Generically performing these tests may catch problems in the future
This is testing things.
In this PR text.
> TST: try to get status printouts from all fake devices

- .travis.yml
- dev-requirements.txt
- docs/source/upcoming_release_notes/745-pypi-testing.rst
Test Python 3.6 with pip/PyPI-installed dependencies
Closes #745 
Waiting on Travis CI results
Included release notes
> CI: test Python 3.6 with pip/PyPI-installed dependencies

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/recipe-cleanup-733.rst
- Refer to conda-forge's current recipe
- Reorder based on conda-forge (python first, then alphabetical)
- Take highest pins comparing the two recipes
- Remove no longer used periodictable dependency
- Closes #733
TBH I'm just hoping the CI passes first try
> BLD: Clean up recipe

- docs/source/upcoming_release_notes/650-WFS-Wavefront.rst
- pcdsdevices/lasers/thorlabsWFS.py
- Change ThorlabsWfs40 base class
- Add some docs
- Add Wavefront_RBV PV and a small image viewer for it
This is a PV that the laser group is interested in. The spot field is already taking up IMAGE1, and it's a small array, so we can just make a small viewer for it.
Closes #650 
Testing is WIP. Waiting on laser group. 
Docstrings, docs metadata.
> ENH: Update the ThorlabsWfs40 class

- docs/source/upcoming_release_notes/782-fix-kind.rst
- pcdsdevices/signal.py
Apply Ken's patch file linked in https://github.com/pcdshub/pcdsdevices/issues/782#issuecomment-793267474
Seems to fix the kind issue
closes #782 
Made a `LaserTiming` object and verified the hints looked correct:
```
In [4]: lt.hints
Out[4]: {'fields': ['lt_setpoint']}
```
> MNT: apply Ken's gist patch

- docs/source/upcoming_release_notes/781-newport-md.rst
- pcdsdevices/epics_motor.py
- pcdsdevices/signal.py
- tests/test_signal.py
Overwrite the incorrect metadata from the user_readback signal
closes #781 
Created the device
> MNT: Add the newport metadata

- docs/source/upcoming_release_notes/785-virtual-motor.rst
- pcdsdevices/interface.py
- pcdsdevices/positioner.py
- pcdsdevices/sim.py
- tests/test_positioner.py
Intended replacement for blbase.VirtualMotor to help me spend less time supporting hutches (my job is not to support hutches and I spent half my time on this send help)
closes #785
Added tests and also ran interactively for a bit
> ENH: func positioner

- docs/source/upcoming_release_notes/802-vrcno.rst
> Completed pre-release-notes and documentation page from the premerge checklist on #802 

- docs/source/upcoming_release_notes/809-teardown-spam.rst
- pcdsdevices/__init__.py
Oops
See https://github.com/pcdshub/pcds-envs/pull/185#issuecomment-812811420
> FIX: undo accidental destruction of pyepics

- docs/source/upcoming_release_notes/816-lightpath-stuff.rst
- pcdsdevices/interface.py
- pcdsdevices/lic.py
- pcdsdevices/slits.py
- pcdsdevices/sxr_test_absorber.py
Accumulated updates to make devices work in the KFE lightpath
They asked for a lightpath, and it will be more useful if all the elements work
Interactively
> ENH: Updates for lightpath

- README.md
- dev-requirements.txt
- docs/source/README.inc
Remove codecov. We aren't using it and they had a security breach
> MNT: remove codecov after security breach

- docs/source/upcoming_release_notes/830-kmono-threshold.rst
- pcdsdevices/spectrometer.py
Fix kmono threshold to show beam passing, as per slack thread
Shows blocking beam when only "near out"
Interactive
> MNT: update kmono threshold

- docs/source/upcoming_release_notes/833-mrco_motion.rst
- pcdsdevices/mrco_motion.py
Module containing class to control motors fixed to the  MRCO motion system for the IP1 endstation in TMO.
An mrco_motion class is necessary for creating an entry in the happi database and for connecting to a typhos GUI to control motion along the axes.
I tested the module with flake8 and pytest and both came back clean.
(pcds-4.1.4) psdev04:pcdsdevices bosum123$ flake8 mrco_motion.py
(pcds-4.1.4) psdev04:pcdsdevices bosum123$
(pcds-4.1.4) psdev04:pcdsdevices bosum123$ pytest mrco_motion.py
================================================= test session starts ==================================================
platform linux -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
PyQt5 5.12.3 -- Qt runtime 5.12.9 -- Qt compiled 5.12.9
benchmark: 3.4.1 (defaults: timer=time.perf_counter …
> Added mrco_motion module from lamp_motion template

- docs/source/upcoming_release_notes/840-kbo-typo.rst
Jyoti didn't do this step in #840 and I couldn't do it since she made the PR on her master branch.
Important to keep the repo changelog documented
> DOC: add pre-release notes for #840

- .travis.yml
- docs/source/upcoming_release_notes/844-im2k0-setup.rst
- pcdsdevices/pim.py
Add a special class for IM2K0's new configuration.
IM2K0 is now a unique combination of devices and requires a special class, pulling from parts of PPM and parts of XPIM.
Works in prod
Added pre-release notes and descriptive docstrings
> ENH: add special class for new IM2K0 setup

- docs/source/upcoming_release_notes/843-vfs-veto.rst
- pcdsdevices/valve.py
Add the :VETO_DEVICE_RBV to the VFS class
closes #843 
Interactively via typhos and happi
Added docstring and release notes
> ENH: add VFS Veto PV

- docs/source/releases.rst
- setup.py
Include the typhos ui files properly in the installed distribution.
> MNT: v4.7.1 fix missing ui files

- docs/source/upcoming_release_notes/916-Add_slice-dhv.rst
- pcdsdevices/piezo.py
Add two sub classes, and a top-level class, for the Slice-DHV piezo driver. This driver will be used in the new LCLS timing system. 
Closes #916 
Tested on a controller in the ASC lab, using a typhos screen generated by this class.
The code, and docstrings. The PVs are fairly self-explanatory.
> Add code and release notes for SliceDhv* devices.

- docs/source/upcoming_release_notes/920-Add_DiCon_switch.rst
- pcdsdevices/lasers/dicon.py
Added a new class for the DiCon fiber switch. 
This device will be used in the LCLS-II timing system.
Tested using a live unit in ASC. 
The code.
> Add DiCon Switch

- docs/source/upcoming_release_notes/940-Agilent_53201A_device.rst
- pcdsdevices/lasers/counters.py
Added a device for the Agilent 53201A frequency counter. 
Closes #940 
Tested using a frequency counter in the laser hall. 
Docstrings?
> Agilent 53210A

- docs/source/upcoming_release_notes/959-Added_HXRSpectrometer_class.rst
- pcdsdevices/spectrometer.py
- pcdsdevices/tests/test_spectrometer.py
Created this HXRSpectrometer class to use with the hxr spectrometer happi device. 
It contains all the motors used in the device.
Change is required to allow the device to be used across all hxr hutches.
Edits were made in my own pcdsdevices dev directory. Then an ipython session was created that uses my working directory as the python path. From there I was able to load in the happi device and perform various commands to ensure the motor objects were being read.
A docstring was written.
> Hxr spectrometer

- docs/source/upcoming_release_notes/984-tweak_step_size.rst
- pcdsdevices/interface.py
Simple addition of `scale` optional keyword argument to the tweak function.  
[Jira](https://jira.slac.stanford.edu/browse/LCLSECSD-937)
interactively with simulated motors. 
Added relevant bits to docstrings
> ENH: add scale argument to tweak function

- docs/source/upcoming_release_notes/992-tm1k4.rst
- pcdsdevices/atm.py
Added a new class for TM1K4 Positioner in atm.py
Added a new class for TM1K4 in atm.py
TMO requested 2 additional target positions on their ATM TM1K4. The underlying PLC code has been updated but the Lucid GUI still only shows 5 positions.
flake8:
ipython
1. Docstring
2. JIRA
3. To be added to confluence
> Added new class for TM1K4 ATM in TMO 

- docs/source/index.rst
- docs/source/signals.rst
* A start to documenting our available signal types and providing examples for them
* This isn't perfect - I didn't get nearly as in-depth as I wanted to - but it's better than what we have now
* Contributions/rewrites/additions/etc fully welcome
Related: https://confluence.slac.stanford.edu/display/PCDS/How+to+add+a+device+to+pcdsdevices
> DOC: add some basic documentation about signals

- docs/source/upcoming_release_notes/1029-tm2k4.rst
- pcdsdevices/atm.py
Added a new class for TM2K4 Positioner in atm.py
Added a new class for TM2K4 in atm.py
TMO requested 4 target positions on their ATM TM2K4. The underlying PLC code has been updated but the Lucid GUI still only shows 5 positions.
ipython
pre-commit 
1. Docstring
> Added new class for TM2K4 ATM in TMO

- pcdsdevices/lasers/btps.py
- pcdsdevices/ui/btps-camera-summary.ui
- pcdsdevices/ui/btps-overview.ui
- pcdsdevices/ui/btps-range-config.ui
* Minor fixes and updates to #1042 
* This is an ongoing initial deployment of the system.
* The previous PR had the bulk of the implementation, and this PR will fix it up as we proceed.
* I don't expect to add a release changelog here except for in the PR text:
* Some PV naming fixes in the btps screens
* Fixed tooltips that were confusing
* Fixed set_nominal to use the correct components
Interactively
~- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page~
~- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate~
> MNT/FIX: post-merge fix-up for the laser hall beam transport motion/protection systems

- docs/source/upcoming_release_notes/1054-radiation-sensor.rst
- pcdsdevices/radiation.py
Added radiation.py
Added class HPI6030 for 6030 sensor data readout
Provides a place to write radiation modules.
Provides a container for 6030 sensor data.
Sourced my local pcdsdevices branch containing radiation.py
Ran typhos to display readouts.
Changes will be documented in pre-release notes.
> Add new module for python radiation

- docs/source/upcoming_release_notes/1022-add_RSpowersupply.rst
- pcdsdevices/rs_powersupply.py
Add new Rohde SchwarzPowerSupply
https://jira.slac.stanford.edu/browse/LCLSECSD-313
In [1]: from pcdsdevices.rs_powersupply import RohdeSchwarzPowerSupply
In [2]: rs = RohdeSchwarzPowerSupply('TMO:IP1:HMP:01', name='TMO_RSPowersupply')
In [3]: rs.ch2.voltage.get()
Out[3]: 0.0
In [4]: rs.ch1.current.get()
Out[4]: 0.0
source/upcoming_release_notes/1022-add_RSpowersupply.rst
> ENH: add RohdeSchwarzPowerSupply

- docs/source/upcoming_release_notes/1058-Add_new_motors_into_spectrometer.rst
- pcdsdevices/spectrometer.py
Add two linear thorlabs motors into spectrometer 
Add EL3074, EL9505, EL1124, EK1100, Thorlabs ZST213 x 2 motors and PLC code change
TMO wants to remotely control the camera in spectrometer instead of manually move by hands
From typhos screen , two motors can be moved.
From python environment, it is tested too:
In [2]: from pcdsdevices.spectrometer import TMOSpectrometer
In [3]: lx = TMOSpectrometer('TMO:SPEC', name='sp1k4')
In [4]: lx.lens_yaw.get()
Out[4]: BeckhoffAxisTuple(user_readback=0.999594, user_setpoint=1.0, user_offset=0.0, user_offset_dir=0, offset_freeze_switch=0, set_use_switch=0, velocity=0.1, acceleration=0.02, motor_egu='mm', motor_is_moving=0, motor_done_move=1, high_limit_switch=0, low_limit_switch=0, high_limit_travel=0.0, low_limit_travel=0.0, direction_of_travel=0, …
> Tmo spectrometer

- docs/source/upcoming_release_notes/1064-enh_qmini.rst
#960 but + release notes and not from a master branch
Read #960
> ENH: qmini screen

- docs/source/upcoming_release_notes/1094-tst_att_smoke.rst
- pcdsdevices/tests/test_attenuator.py
Follow-up to #1086 
Supercedes #1093 
Good to make sure we don't completely break this later. It works now but it's easy to mess things up.
Unit tests only
I'll make one
> TST: add smoke tests for AT1K2 and AT2K2

- pcdsdevices/fms.py
pep8 touchups on fms.py before I forget
Touching up style
This is style
These are style fixes
> STY: pep8 fms.py

- .travis.yml
- docs/source/upcoming_release_notes/1101-numpy-pin.rst
See #1099 (https://github.com/pcdshub/pcdsdevices/pull/1099#issuecomment-1370374728)
Closes #1100
On Travis CI. The first build passed, indicating this should be a suitable (temporary) bandage.
> CI: try numpy 1.23 per recommendation

- docs/source/upcoming_release_notes/1098-enh_remove_kill_print.rst
- pcdsdevices/ccm.py
Remove leftover debug print
https://jira.slac.stanford.edu/browse/LCLSECSD-1743?jql=project%20%3D%20LCLSECSD%20AND%20component%20%3D%20hutch-python
n/a
Release notes only
> ENH: remove CCM kill print

- docs/source/upcoming_release_notes/1099-enh_vat590.rst
- pcdsdevices/valve.py
Add a class for controlling the VAT590 needle valve.
For now, it's just the EPICS control points.
There are data types for this in TwinCAT and one valve installed in TMO: https://jira.slac.stanford.edu/browse/LCLSECSD-1026
Not at all, the IOC for this is offline
Pre-release notes only
> ENH: VAT590 needle valve

- conda-recipe/meta.yaml
- docs/source/upcoming_release_notes/1110-test_deps.rst
* Copy `dev-requirements` into the test requirements for conda builds
* Will be required by change in the GitHub Actions workflow: https://github.com/pcdshub/pcds-ci-helpers/pull/99
* PR will need to be cycled once that one has been merged
> BLD: dev requirements for conda go in the recipe

- docs-requirements.txt
- docs/source/upcoming_release_notes/1170-docs_ipython.rst
IPython is required to build the docs as we use its Sphinx extensions.
> DOC/FIX: IPython is required for docs

- docs/source/upcoming_release_notes/1178-new-tpr-class.rst
- pcdsdevices/tests/test_tpr.py
- pcdsdevices/tpr.py
Tpr analogue to evr.Trigger
https://jira.slac.stanford.edu/browse/ECS-3903
#1119 
Interactively and with test_tpr.py based on test_evr.py.
Upcoming release notes
> Add new tpr class

- docs/source/upcoming_release_notes/1179-tmo_gmd_classes.rst
- pcdsdevices/attenuator.py
- pcdsdevices/energy_monitor.py
- pcdsdevices/keithley.py
- pcdsdevices/pim.py
Adding devices from /cds/group/pcds/pyps/apps/hutch-python/tmo/tmo/tmo_beamline_control.py
https://jira.slac.stanford.edu/browse/ECS-4058
Has not been tested, but will do so programmatically
>  TMO GMD device classes

- docs/source/upcoming_release_notes/1181-adding_sp1k4-att-rtd.rst
- pcdsdevices/spectrometer.py
adding two lines of code to add RTD gui in Sp1K4-TMO spectrometer
Scientists request
[tongju@tmo-control ~]$ caget SP1K4:ATT:RTD:01:TEMP_RBV
SP1K4:ATT:RTD:01:TEMP_RBV      19.88
[
](https://jira.slac.stanford.edu/browse/ECS-3982)
> ENH:adding sp1k4-att-rtd into sp1k4 gui

- .pre-commit-config.yaml
- docs/source/upcoming_release_notes/1196-bug_at2l0_clear_error.rst
- pcdsdevices/attenuator.py
- pcdsdevices/make_ophyd_device.py
- pcdsdevices/tests/test_analog_signals.py
- pcdsdevices/tests/test_attenuator.py
Fix regressions in at2l0 in the mds signals
I also ran pre-commit autoupdate and fixed the "new" flake8 things. I did this because the existing version was giving nonsense errors on my machine.
See https://jira.slac.stanford.edu/browse/ECS-4470
This is tests
Here
> TST/BUG: tests and bugfixes for at2l0

- docs/source/upcoming_release_notes/1199-cool-updates.rst
- pcdsdevices/atm.py
- pcdsdevices/attenuator.py
- pcdsdevices/device_types.py
- pcdsdevices/mirror.py
- pcdsdevices/pc.py
- pcdsdevices/wfs.py
- in `atm.py` add `flow_meter` to `ArrivalTimeMonitor`, add new class for `MFXATM`
- in `attenuator.py` add `flow_meter` to `AttenuatorSXR_Ladder`
- in `attenuator.py` add `flow_meter` to `AttenuatorSXR_LadderTwoBladeLBD`
- in `device_types.py` add `WaveFrontSensorTargetCool` , `WaveFrontSensorTargetPF2K2`
- in `mirror.py` add flow sensor variable to `FFMirror`
- create a new sub module `pc.py` and class `PhotonCollimator` to readout `flow_switch`
- in `wfs.py` add new class: `WaveFrontSensorTargetFDQ` with `flow_meter` 
- newly installed flow sensors.
- opened all typhos screens, verified working.
https://jira.slac.stanford.edu/browse/ECS-1248
https://jira.slac.stanford.edu/browse/ECS-1186
https://jira.slac.stanford.edu/browse/ECS-1514
https://jira.slac.stanford.edu/browse/ECS-1482
> Add flow sensor to devices

- docs/source/upcoming_release_notes/1208-add_temporary_li2k4_gui.rst
This was missed in #1208 so let's include it here
In progress release notes make it possible to compile full tag release notes with so many contributors
> DOC: merge tong's release notes for li2k4

- docs/source/upcoming_release_notes/1211-add-status-signals-to-mpod-apalis-module.rst
- pcdsdevices/mpod_apalis.py
add missing epics signals to MPODApalisModule.
James P. Cryan asked for missing functionality at MPODApalisModule (https://jira.slac.stanford.edu/browse/ECS-4984)
tested manually using hutch-python on TMO MPOD 1 
pcda conda version 5.8.2
> add status signals to mpod apalis module

- docs/source/upcoming_release_notes/1235-Fix_SmarActEncodedTipTilt_typo.rst
- pcdsdevices/epics_motor.py
Fixes a typo in `SmarActEncodedTipTilt`.
Closes #1235 
Also we should close #1197 
Closes #1197 
Tested interactively. 
This PR. 
Before:
After:
> Smaract tt

- docs/source/upcoming_release_notes/1240-mfx_6crystal_spec.rst
- pcdsdevices/spectrometer.py
Class for the MFX 6 crystal spectrometer
CLI control of the device
WIth mfx3
Docstring
> Mfx spectrometer

- docs/source/upcoming_release_notes/1273-adding_pa1k4-pf_device.rst
- pcdsdevices/tmo_ip1.py
Adding a new device: PA1K4-PF
Scientists require this device to work as calibrating photon energy
Run command to show the GUI. 
https://jira.slac.stanford.edu/browse/ECS-4824
> adding PA1K4-PF device in TMO  beamline

- docs/source/upcoming_release_notes/1275-doc_clarify_sections.rst
- docs/source/upcoming_release_notes/1280-doc_clarify_sections.rst
- docs/source/upcoming_release_notes/6079-Fix_pos_ao_pv_connection_timeout_in_VCN_valve_class.rst
- docs/source/upcoming_release_notes/6090-Added_HI_DI_PV_to_PIPPLC_class_to_show_high_voltage_input_for_pump_diagnostics.rst
- docs/source/upcoming_release_notes/template-full.rst
- docs/source/upcoming_release_notes/template-short.rst
Rename "Features" to "Library Features" and "Device Updates" to "Device Features" to make the sorting more intuitive.
Apply the name changes to existing pre-release notes and resort appropriately.
Most contributors miss-sorted "Device Updates" into the "Features" section which is not their fault, we can make this more intuitive.
I was able to generate a new pre-release notes stub with the new headers.
The release notes accumulator makes no assumptions about header contents.
Here only
> DOC: clarify sections

- docs/source/upcoming_release_notes/1286-adding_more_targets_into_pa1k4.rst
- pcdsdevices/tmo_ip1.py
Change target number from 5 to 7
Scientists request to have 7 targets instead of 5 in PA1K4:PF motor
Not yet because hardware are not ready.
(https://jira.slac.stanford.edu/browse/ECS-4824)
> changing targets number from 5 to 7

- docs/source/upcoming_release_notes/1292-recoving_sp1k4-att_targets.rst
> Recovering sp1k4 attenuator targets number to 5

- docs/source/upcoming_release_notes/1321-cvmi-bootstrap.rst
- pcdsdevices/cvmi_bootstrap.py
the motor name
Remove gas needles X-Z and rename gas jet, sample paddle. 
Scientists request to change to run RP boot strap experiment
yes. It is working for test environment 
(https://jira.slac.stanford.edu/browse/ECS-6347)
> updating CVMI chamber gui to bootstrap experiment

- docs/source/upcoming_release_notes/1324-edit_gas_needle_axes_names.rst
- pcdsdevices/lamp_motion.py
gas needle X -> gas jet X
gas needle Y-> gas jet Y
gas needle Z -> gas jet Z
Scientists request it
> edit gas needle axes

- docs/source/upcoming_release_notes/1343-changing-gas-needle-y_to_eps.rst
- pcdsdevices/lamp_motion.py
gas needle Y is changed from beckhoffaxis to beckhoffaxisEPS
It will give scientist more information of EPS status
I test it under tmo-control
> edit gas jet y into EPS beckhoff

- docs/source/upcoming_release_notes/1348-fms-devices.rst
- pcdsdevices/fms.py
- Added new classes to fms.py:
- `SRCController`
- `RaritanSensor`
- `Floor`
- `PCWFlow`
- `PCWTemp`
- `AMBTemp`
- `Rack`
Deployed new FMS sensors in MEC.
launched lucid screen with happi database at:
`/reg/g/pcds/pyps/apps/fms/db.json`
https://jira.slac.stanford.edu/browse/ECS-4884
> Add fms sensor classes

- docs/source/upcoming_release_notes/1361-IntegralSigned-Addition-AdcSample-BracketRemoval.rst
- pcdsdevices/digitizers.py
Goes along with https://github.com/slac-epics/rogueRegister/pull/1 and https://github.com/pcdshub/ioc-common-pgpWave8/pull/6
Removing brackets from AdcSample PVs to match new version of rogue register
Adding IntegralSigned component
https://jira.slac.stanford.edu/browse/ECS-8137
https://jira.slac.stanford.edu/browse/ECS-7953
> Adding integral signed, removing sample brackets

- docs/source/upcoming_release_notes/1364-improve_smarpod_class.rst
- pcdsdevices/smarpod.py
- use PVPositionerIsClose instead of raw records
- add mutli axis move
- add checking reachability
James Cryan asked for improving smarpod class as listed at description
> from pcdsdevices.smarpod import SmarPod
> spd = SmarPod(prefix="TMO:SPD:01", name="tmo_spd1_01")
> spd.z.move(-2.8) # works
> spd.z.move(-7) # valueError raised with "Position is unreachable !!!" message
> spd.multi_axis_move(x_sp=1.0, y_sp=1.0, z_sp=1.0) # only x,y,z will move
> spd.multi_axis_move() # try to move to the current setpoints
TMO pcsd dev-conda env
> improve smarpod class

- docs/source/upcoming_release_notes/1371-recovering_targets_of_pak4.rst
- pcdsdevices/tmo_ip1.py
Scientists require to fix this.
just recover from 5 targets to 7 targets after they fix the motor issues.
[
](https://jira.slac.stanford.edu/browse/ECS-8521)
> recover pa1k4 targets 6 and 7
